
##############################################################################
#
# Copyright (c) 2003-2018 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

import os
Import('*')
local_env = env.Clone(tools=['pdflatex'])

tex_src = Glob('*.tex')+Glob('*.bib')+Glob('*.sty')+Glob('*.cfg')+Glob('*.cls')
#fig_src = Glob('figures/*.png') no figures yet

if local_env['pdflatex']:
    if local_env['verbose']:
        interaction='-interaction=nonstopmode'
    else:
        interaction='-interaction=batchmode'

    # Define command to include SVN revision 
    local_env.Append(PDFLATEXFLAGS=[interaction,'\\\\newcommand{\\\\RepVersion}{%s\\\\xspace}\\\\input{install.tex}'%(local_env['svn_revision'])])
    pdf=local_env.PDF(target='install.pdf', source='install.tex')
    Depends(pdf, tex_src)

    pdf_path=os.path.join(release_dir, 'install', 'install.pdf')
    pdf_inst=local_env.InstallAs(target=pdf_path, source='install.pdf')
    env.Alias('install_pdf', pdf_inst)
else:
    env.Alias('install_pdf', '', '@echo "Not building install guide: PDF output not supported!"')
    env.AlwaysBuild('install_pdf')

