# Scons configuration file for CppUnitTest

#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       
#                                                          
#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

libdir = Dir(str(esysroot) + '/tools/CppUnitTest/lib')
Export(["libdir"])

Export(["cxx"])
Export(["cxx_flags"])
Export(["ar_flags"])

#
# print out build configuration for this module

print "Build configuration for module: CppUnitTest"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# call the SConscript to do the actual build

SConscript('src/SConscript', src_dir='src', build_dir='obj', duplicate=0)
