libinstall = None

Import('*')

import os
import string

finley_path = str(esysroot) + '/finley/src/finley'
finley_cppadapter_path = str(esysroot) + '/finley/src/finley/CPPAdapter'
paso_path = str(esysroot) + '/paso/inc'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'

cpp_path = [finley_path,
            finley_cppadapter_path,
            paso_path,
            escript_path,
            esysUtils_path,
            python_path,
            boost_path]

lib = 'finleycpp'

sources = ['Assemble_addToSystemMatrix.c',
           'Assemble_CopyElementData.c',
           'Assemble_CopyNodalData.c',
           'Assemble_getAssembleParameters.c',
           'Assemble_getSize.c',
           'Assemble_gradient.c',
           'Assemble_handelShapeMissMatch.c',
           'Assemble_integrate.c',
           'Assemble_interpolate.c',
           'Assemble_NodeCoordinates.c',
           'Assemble_PDE.c',
           'Assemble_PDEMatrix_Single2.c',
           'Assemble_PDEMatrix_System2.c',
           'Assemble_PDE_RHS.c',
           'Assemble_RHSMatrix_Single.c',
           'Assemble_RHSMatrix_System.c',
           'Assemble_RobinCondition.c',
           'Assemble_RobinCondition_RHS.c',
           'Assemble_setNormal.c',
           'ElementFile_allocTable.c',
           'ElementFile.c',
           'ElementFile_copyTable.c',
           'ElementFile_gather.c',
           'ElementFile_improveColoring.c',
           'ElementFile_markNodes.c',
           'ElementFile_optimizeDistribution.c',
           'ElementFile_prepare.c',
           'ElementFile_relableNodes.c',
           'ElementFile_scatter.c',
           'ElementFile_setNodeRange.c',
           'Finley.c',
           'IndexList.c',
           'Mesh.c',
           'Mesh_findMatchingFaces.c',
           'Mesh_getPattern.c',
           'Mesh_glueFaces.c',
           'Mesh_hex20.c',
           'Mesh_hex8.c',
           'Mesh_joinFaces.c',
           'Mesh_line2.c',
           'Mesh_line3.c',
           'Mesh_markNodes.c',
           'Mesh_merge.c',
           'Mesh_prepare.c',
           'Mesh_prepareNodes.c',
           'Mesh_print.c',
           'Mesh_read.c',
           'Mesh_rec4.c',
           'Mesh_rec8.c',
           'Mesh_relabelElementNodes.c',
           'Mesh_resolveNodeIds.c',
           'Mesh_saveDX.c',
           'Mesh_saveVTK.c',
           'Mesh_write.c',
           'NodeFile_allocTable.c',
           'NodeFile.c',
           'NodeFile_copyTable.c',
           'NodeFile_gatter.c',
           'NodeFile_scatter.c',
           'NodeFile_setCoordinates.c',
           'NodeFile_setIdRange.c',
           'Quadrature.c',
           'ReferenceElements.c',
           'ShapeFunctions.c',
           'Util.c',
           'CPPAdapter/FinleyError.cpp',
           'CPPAdapter/MeshAdapter.cpp',
           'CPPAdapter/MeshAdapterFactory.cpp',
           'CPPAdapter/SystemMatrixAdapter.cpp',
           'CPPAdapter/finleycpp.cpp']

finley_env = Environment(ENV = os.environ)

finley_env.Replace(CC = cc)
finley_env.Replace(CXX = cxx)
finley_env.Replace(CCFLAGS = cc_flags)
finley_env.Replace(CXXFLAGS = cxx_flags)
finley_env.Replace(SHOBJSUFFIX = '.lo')
finley_env.Replace(CPPPATH = cpp_path)

finley_lib = finley_env.SharedLibrary(lib, sources)
finley_env.Install(libdir, finley_lib)

if libinstall != None:
  finley_env.Install(libinstall, finley_lib)
