
########################################################
#
# Copyright (c) 2003-2008 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################


import os
Import('*')

local_env = clone_env(env_mpi)

# get the relevant file names:
src_dir = local_env.Dir('.').srcnode().abspath
filenames = [ x for x in os.listdir(src_dir) if os.path.splitext(x)[1] in [".h", ".c", ".cpp"] ]

sources = [x for x in filenames if os.path.splitext(x)[1] in ['.cpp', '.c']]

local_env.Append(LIBS=['finley', 'escript', 'paso', 'esysUtils', 'CppUnitTest'] + env['sys_libs'])

# compile test
program = local_env.Program('finley_UnitTest', sources)
env.Alias('build_tests', program)

# run the tests - but only if test_targets are stale
local_env.RunUnitTest('finley_UnitTest')
test_targets = os.path.splitext('finley_UnitTest')[0]+'.passed'
Alias("run_tests", test_targets)

local_env.SConscript(dirs = ['#/finley/test/python'], build_dir='python', duplicate=0)
