#!/bin/bash
# $Id: unit_test 206 2005-11-23 05:03:42Z jgs $
# simple script to run all finley unit tests

MODULES="MeshAdapterTest.exe"

for module in $MODULES ; do
  echo Testing: $module
  ./$module
  if [ $? != 0 ]
  then
    echo Unit Testing FAILED for module: $module
    exit 1
  fi
done
exit 0
