
##############################################################################
#
# Copyright (c) 2003-2018 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
#
##############################################################################

from os.path import splitext
Import('*')

local_env = env.Clone()

# files defining test runs (passing in a release)
testruns = []
testruns += ['run_savevtk_tests.py']
testruns += ['run_savesilo_tests.py']

# files defining tests run locally (not as part of a release)
localtestruns = [x for x in Glob('*.py', strings=True) if not x.startswith('run_')]

# all tests
alltestruns = testruns + localtestruns

# test files are just compiled
test_pyc = env.PyCompile(alltestruns)
env.Alias('build_py_tests', test_pyc)

# add unit test to target alias
local_env['ENV']['WEIPA_TEST_MESHES']=env.Dir('#/weipa/test/python').abspath
local_env.PrependENVPath('PYTHONPATH', Dir('.').abspath)
local_env.PrependENVPath('PYTHONPATH', env.Dir('$BUILD_DIR/$PLATFORM/weipa/test/python').abspath)
local_env['ENV']['WEIPA_TEST_MESHES']=env.Dir('#/weipa/test/python/meshes').abspath
local_env['ENV']['WEIPA_WORKDIR']=Dir('.').abspath
env.Alias('local_py_tests',[splitext(x)[0]+'.passed' for x in alltestruns])
env.Alias('py_tests', [splitext(x)[0]+'.passed' for x in testruns])

# run all tests
program = local_env.RunPyUnitTest(alltestruns)
Depends(program, 'build_py_tests')
if env['usempi']:
    Depends(program, env['prefix']+"/lib/pythonMPI")

# add a group of tests
from grouptest import GroupTest
tgroup=GroupTest("weipa", "$PYTHONRUNNER ", (("WEIPA_TEST_DATA","$BATCH_ROOT/weipa/test/python"),('WEIPA_WORKDIR','$BUILD_DIR/weipa/test/python')), "$BATCH_ROOT/escriptcore/test/python:$BATCH_ROOT/weipa/test/python", "$BATCH_ROOT/weipa/test/python", testruns)
tgroup.makeDir("$BUILD_DIR/weipa/test/python")
TestGroups.append(tgroup)

