
##############################################################################
#
# Copyright (c) 2003-2018 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

import os
Import('*')

doxy_dir=os.path.join(release_dir, 'doxygen')
env.Command(doxy_dir, [], [Mkdir(doxy_dir)])

# Now some magic from the doxygen FAQ to get the global revision number into
# the doxyfile
if os.name=='posix':
    env.Alias('api_doxygen',[doxy_dir],['(cat doc/doxygen/doxygen_esys; echo "PROJECT_NUMBER=\"Revision_`svnversion`\""; echo OUTPUT_DIRECTORY=\"'+doxy_dir+'\" ) | doxygen - '])
else:
    env.Alias('api_doxygen',[doxy_dir],["doxygen doc/doxygen/doxygen_esys"])

env.AlwaysBuild('api_doxygen')

