#!/bin/bash
# $Id$
if [ ! -e Makefile ]; then ln -s ./multi_arrayTest.mk Makefile; fi
make -f ./Makefile clean
make -f ./Makefile DODEBUG=YES
./multi_arrayTest.exe
if [ $? != 0 ]
then
  make -f ./Makefile clean
  exit 1
else
  make -f ./Makefile clean
  exit 0
fi
