##############################################################################
#
# Copyright (c) 2003-2026 by the esys.escript Group
# https://github.com/LutzGross/esys-escript.github.io
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
#
##############################################################################

Import('env')
if 'finley' in env['domains']:
    if not env['paso'] and not env['trilinos']:
        print("Finley requires a solver library! Please either enable Paso or Trilinos.")
        env.Exit(1)

    # configure C++ library
    env.SConscript('src/SConscript', duplicate=0)

    # configure python module
    env.SConscript('py_src/SConscript', variant_dir='py', duplicate=0)

    # configure unit tests
    env.SConscript('test/SConscript', duplicate=0)

