
##############################################################################
#
# Copyright (c) 2003-2013 by University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development since 2012 by School of Earth Sciences
#
##############################################################################

import os
Import('*')
local_env = env.Clone()

# get the source file names
sources = Glob('*.py')
sym_sources = Glob(os.path.join('symbolic','*.py'))

# compile
pyc = local_env.PyCompile(sources)
sym_pyc = local_env.PyCompile(sym_sources)

# install
runmodel_inst = local_env.Install(local_env['bininstall'], 'runmodel.py')
py_inst = local_env.Install(os.path.join(local_env['pyinstall'],'escript'), pyc)
sym_py_inst = local_env.Install(os.path.join(local_env['pyinstall'],'escript','symbolic'), sym_pyc)
env.Alias('install_escript_py', [runmodel_inst, py_inst, sym_py_inst])

