
########################################################
#
# Copyright (c) 2003-2011 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################

import os, re
Import('*')
local_env = env.Clone()

# get the test source file names
sources = Glob('*.cpp')+Glob('*.c')

# some of these test files are too large to optimize
local_env['CCFLAGS'] = re.sub('-O[0-9]', '-g', str(local_env['CCFLAGS']))
local_env.Append(LIBS=['escript', 'esysUtils', 'paso'])

# build the executable
program = local_env.Program('PasoTests', sources)

