# Scons configuration file for documentation

#
# set appropriate defaults for configuration variables

esysroot=str(Dir('..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

#
# call appropriate SConscripts

target_scripts = ['doxygen/SConscript',
                  'epydoc/SConscript']

SConscript(target_scripts, duplicate=0)
