# top-level Scons configuration file for all bruce unit tests

#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       
#                                                          
#
import os

#
# ensure correct versions of python and scons

EnsurePythonVersion(2,3)
EnsureSConsVersion(0,96)

#
# retreive command-line arguments if any
# these are passed through to SConscripts

if ARGUMENTS.get('usegcc',0):
  usegcc = 1
else:
  usegcc = 0
Export(["usegcc"])

if ARGUMENTS.get('options',0):
  options = ARGUMENTS.get('options',0)
else:
  options = None
Export(["options"])

#
# set and export esysroot

esysroot = Dir('#../..')
Export(["esysroot"])

#
# call appropriate SConscripts

target_scripts = ['Bruce/SConscript',
                  'BruceFactory/SConscript']

SConscript(target_scripts, duplicate=0)
