#!/bin/bash

# $Id$
# An explicit testing script for esys

# list of users to email test results to
MAIL_RECIPIENTS="jgs@esscc.uq.edu.au gross@esscc.uq.edu.au cochrane@esscc.uq.edu.au elspeth@esscc.uq.edu.au matt@esscc.uq.edu.au"

# define compiler executable and library locations
export PATH=/opt/intel/cmplrs/80.058/intel_cc_80/bin:$PATH
export LD_LIBRARY_PATH=/opt/intel/cmplrs/80.058/intel_cc_80/lib

echo cd $1
cd $1
if [ $? != 0 ]
then
  echo couldnt cd $1
  echo "couldnt cd $1" | mail -s "esys autotest results" $MAIL_RECIPIENTS
  exit 1
fi

echo loading esys setup
. ~/bin/esys_setup
if [ $? != 0 ]
then
  echo couldnt load esys setup
  echo "couldnt load esys setup" | mail -s "esys autotest results" $MAIL_RECIPIENTS
  exit 2
fi

echo running cvs update
cvs update -P -d
if [ $? != 0 ]
then
  echo cvs update failed
  echo "cvs update failed" | mail -s "esys autotest results" $MAIL_RECIPIENTS
  exit 3
fi

echo running mk uninstall
./mk uninstall
if [ $? != 0 ]
then
  echo ./mk uninstall failed
  echo "./mk uninstall failed" | mail -s "esys autotest results" $MAIL_RECIPIENTS
  exit 4
fi

echo running mk clean
./mk clean
if [ $? != 0 ]
then
  echo ./mk clean failed
  echo "./mk clean failed" | mail -s "esys autotest results" $MAIL_RECIPIENTS
  exit 5
fi

echo running mk install
./mk install DEBUG
if [ $? != 0 ]
then
  echo ./mk install failed
  echo "./mk install failed" | mail -s "esys autotest results" $MAIL_RECIPIENTS
  exit 6
fi

echo running mk unit_test
./mk unit_test
if [ $? != 0 ]
then
  echo ./mk unit_test failed
  echo "./mk unit_test failed" | mail -s "esys autotest results" $MAIL_RECIPIENTS
  exit 7
fi

echo running mk py_test
./mk py_test
if [ $? != 0 ]
then
  echo ./mk py_test failed
  echo "./mk py_test failed" | mail -s "esys autotest results" $MAIL_RECIPIENTS
  exit 8
fi

echo "success" | mail -s "esys autotest results" $MAIL_RECIPIENTS
exit 0
