
##############################################################################
#
# Copyright (c) 2003-2018 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

Import('*')
local_env = env.Clone()

# get the test source file names
sources = Glob('*.py')

# compile
pyc = local_env.PyCompile(sources)
local_env.Depends(pyc, 'build_weipa')

# install
py_inst = local_env.Install(Dir('weipa', local_env['pyinstall']), pyc)
env.Alias('install_weipa', py_inst)

