#!/usr/bin/env python
# 
# run all of the examples
#
# $Id: run_escript,v 1.1 2006/01/03 08:21:37 paultcochrane Exp $

# process arguments if any
import sys
numArgs = len(sys.argv)
if numArgs == 1:
    renderer = "vtk"
else:
    renderer = sys.argv[1]

# the list of files to process
Files = (
    "escript_scalarData1D.py",
    "escript_scalarData2D.py",
    "escript_scalarData3D.py",
    "escript_twoDVectorData1D.py",
    "escript_twoDVectorData2D.py",
    "escript_twoDVectorData3D.py",
    "escript_threeDVectorData1D.py",
    "escript_threeDVectorData2D.py",
    "escript_threeDVectorData3D.py",
    "escript_twoByTwoTensorData1D.py",
    "escript_twoByTwoTensorData2D.py",
    "escript_twoByTwoTensorData3D.py",
    "escript_threeByThreeTensorData1D.py",
    "escript_threeByThreeTensorData2D.py",
    "escript_threeByThreeTensorData3D.py",
)

print "Running all examples"

# run the examples
import os
err = open("run_escript.errs", "w")
for file in Files:
    print ""
    print 70*"#"
    print "Running %s" % file
    print 70*"#"
    print ""
    result = os.system("python %s %s" % (file,renderer) )
    if result != 0:
        print "Error running example script: %s" % file
        err.write("Error running example script: %s\n" % file)

err.close()

# vim: expandtab shiftwidth=4:
