--- !ditz.rubyforge.org,2008-03-06/project 
name: libsc
version: "1.1"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: libsc
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.5"
  status: :released
  release_time: 2008-10-17 16:34:16.044402 Z
  log_events: 
  - - 2008-10-17 16:33:46.621384 Z
    - Carsten Burstedde <carsten@ices.utexas.edu>
    - created
    - This release is included with the p4est-0.2 branch in Deal.II.
  - - 2008-10-17 16:34:16.044418 Z
    - Carsten Burstedde <carsten@ices.utexas.edu>
    - released
    - Current maintenance revision of this release is 0.5.4.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.6"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-10-17 16:34:49.627202 Z
    - Carsten Burstedde <carsten@ices.utexas.edu>
    - created
    - This release is developed alongside p4est-0.3.
