#!/bin/bash

# $Id: autotest-scons 162 2005-11-11 00:09:59Z svn $
# An explicit testing script for esys using the scons build system

# list of users to email test results to
MAIL_RECIPIENTS="jgs@esscc.uq.edu.au gross@esscc.uq.edu.au cochrane@esscc.uq.edu.au elspeth@esscc.uq.edu.au matt@esscc.uq.edu.au"
#MAIL_RECIPIENTS="jgs@esscc.uq.edu.au"

# modules to test
TESTS="escript bruce finley"

# the python tests to run
FINLEY_PYTESTS="ImportTest.py finleyTest.py SimpleSolve.py GradTest.py RecTest.py test_linearPDEsOnFinley.py test_generators.py test_visualization_interface.py test_utilOnFinley.py test_symbolsOnFinley.py"
ESCRIPT_PYTESTS="ImportTest.py BinaryOps.py UnaryOps.py SliceGetting.py SliceSetting.py MiscTests.py ArchiveTests.py escriptTest.py newEscriptTests.py DataVariableTests.py test_xml.py"
BRUCE_PYTESTS="ImportTest.py BruceTest.py test_utilOnBruce.py test_symbolsOnBruce.py"

echo cd $1
cd $1
if [ $? != 0 ]
then
  echo couldnt cd $1
  echo "couldnt cd $1" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  exit 1
fi

PWD=`pwd`
echo working in: $PWD

# define compiler executable and library locations
export PATH=/opt/intel/cmplrs/80.058/intel_cc_80/bin:$PATH
export LD_LIBRARY_PATH=/opt/intel/cmplrs/80.058/intel_cc_80/lib

# define python location
export PATH=/raid2/tools/python-2.3.4/bin:$PATH

# set library and openmp settings
export LD_LIBRARY_PATH=$PWD/lib:/raid2/tools/boost/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$PWD
export OMP_SCHEDULE="dynamic"
export OMP_NUM_THREADS=4
export OMP_DYNAMIC=TRUE
export OMP_NESTED=FALSE

FAIL=0

echo running svn update
svn update
if [ $? != 0 ]
then
  echo svn update failed
  echo "svn update failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  exit 2
fi

echo running scons debug=1
scons debug=1
if [ $? != 0 ]
then
  echo scons failed
  echo "scons failed - see autotest-scons logfile" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  exit 3
fi

echo running bruce unit_tests
cd bruce/test
./unit_test-scons
if [ $? != 0 ]
then
  echo bruce unit_test failed
  echo "bruce unit_test failed - see autotest-scons logfile" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  FAIL=1
fi
cd ../..

echo running escript unit_tests
cd escript/test
./unit_test-scons
if [ $? != 0 ]
then
  echo escript unit_test failed
  echo "escript unit_test failed - see autotest-scons logfile" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  FAIL=1
fi
cd ../..

echo running finley unit_tests
cd finley/test
./unit_test-scons
if [ $? != 0 ]
then
  echo finley unit_test failed
  echo "finley unit_test failed - see autotest-scons logfile" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  FAIL=1
fi
cd ../..

echo running esysUtils unit_tests
cd esysUtils/test
./unit_test-scons
if [ $? != 0 ]
then
  echo esysUtils unit_test failed
  echo "esysUtils unit_test failed - see autotest-scons logfile" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  FAIL=1
fi
cd ../..

for module in $TESTS
do
    echo "running python tests for: $module"
    cd $module/test/python
    if [ "$module" == "finley" ]
    then
        for pytest in $FINLEY_PYTESTS
        do
            echo "Running python test: $pytest"
            python $pytest
            if [ $? != 0 ]
            then
              echo Python Testing FAILED for $pytest in module $module
              echo "finley py_test: $pytest failed - see autotest-scons logfile" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
              FAIL=1
            fi
        done
    elif [ "$module" == "escript" ]
    then
        for pytest in $ESCRIPT_PYTESTS
        do
            echo "Running python test: $pytest"
            python $pytest
            if [ $? != 0 ]
            then
              echo Python Testing FAILED for $pytest in module $module
              echo "escript py_test: $pytest failed - see autotest-scons logfile" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
              FAIL=1
            fi
        done
    elif [ "$module" == "bruce" ]
    then
        for pytest in $BRUCE_PYTESTS
        do
            echo "Running python test: $pytest"
            python $pytest
            if [ $? != 0 ]
            then
              echo Python Testing FAILED for $pytest in module $module
              echo "bruce py_test: $pytest failed - see autotest-scons logfile" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
              FAIL=1
            fi
        done
    fi
    cd ../../..
done

if [ $FAIL == 0 ]
then
    echo success
    echo "success" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
fi
exit 0
