#!/bin/sh
#############################################
# This file is autogenerated by scons.
# It will be regenerated each time scons is run
#############################################

failed () {
    echo "Execution failed for $@"
    exit 1
}

if [ $# -lt 2 ]; then
    echo "Usage: $0 build_dir wrapper_options [groupname]"
    echo Runs all or a group of unit tests. Options must be a single string.
    exit 2
fi

case "$1" in
   /*) ;;
   *) echo "build_dir needs to be an absolute path"; exit 4;;
esac

NUMPROCS=1
NUMNODES=1
while getopts ':n:p:' option $2
do
    case "$option" in
        "n")  NUMNODES=$OPTARG ;;
        "p")  NUMPROCS=$OPTARG ;;
    esac
done
MPIPROD=$(($NUMPROCS * $NUMNODES))
BUILD_DIR=$1/posix
if [ ! -d $BUILD_DIR ]
then
    echo Can not find build directory $BUILD_DIR
     exit 2
fi
MPITYPE=`/home/lgross/PycharmProjects/esys-escript.github.io/bin/run-escript -c | grep mpi=`
BATCH_ROOT=`pwd`            
export LD_LIBRARY_PATH=/home/lgross/PycharmProjects/esys-escript.github.io/lib:$LD_LIBRARY_PATH
export OLD_PYTHON=/home/lgross/PycharmProjects/esys-escript.github.io:$PYTHONPATH
BINRUNNER="/home/lgross/PycharmProjects/esys-escript.github.io/bin/run-escript -b $2"
PYTHONRUNNER="/home/lgross/PycharmProjects/esys-escript.github.io/bin/run-escript $2"
PYTHONTESTRUNNER="/home/lgross/PycharmProjects/esys-escript.github.io/bin/run-escript $2 /home/lgross/PycharmProjects/esys-escript.github.io/tools/testrunner.py"
escript () {
	export ESCRIPT_TEST_DATA_ROOT=$BATCH_ROOT/escriptcore/test/python
	export ESCRIPT_WORKDIR=$BUILD_DIR/escriptcore/test/python
	if [ ! -d $BUILD_DIR/escriptcore/test/python ]
	then
		mkdir -p $BUILD_DIR/escriptcore/test/python
	fi
	export PYTHONPATH=$BATCH_ROOT/escriptcore/test/python:$OLD_PYTHON
	cd $BUILD_DIR/escriptcore/test/python
	echo Starting run_units.py
	date
	$PYTHONTESTRUNNER run_units.py -failfile=$BUILD_DIR/escriptcore/test/python/run_units.failed -skipfile=$BUILD_DIR/escriptcore/test/python/run_units.skipped || failed run_units.py
	echo Completed run_units.py
	echo Starting run_data_access.py
	date
	$PYTHONTESTRUNNER run_data_access.py -failfile=$BUILD_DIR/escriptcore/test/python/run_data_access.failed -skipfile=$BUILD_DIR/escriptcore/test/python/run_data_access.skipped || failed run_data_access.py
	echo Completed run_data_access.py
	echo Starting run_testdomain.py
	date
	$PYTHONTESTRUNNER run_testdomain.py -failfile=$BUILD_DIR/escriptcore/test/python/run_testdomain.failed -skipfile=$BUILD_DIR/escriptcore/test/python/run_testdomain.skipped || failed run_testdomain.py
	echo Completed run_testdomain.py
}
escript () {
	export ESCRIPT_TEST_DATA_ROOT=$BATCH_ROOT/escript/test/python
	export ESCRIPT_WORKDIR=$BUILD_DIR/escript/test/python
	if [ ! -d $BUILD_DIR/escript/test/python ]
	then
		mkdir -p $BUILD_DIR/escript/test/python
	fi
	export PYTHONPATH=$BATCH_ROOT/escript/test/python:$OLD_PYTHON
	cd $BUILD_DIR/escript/test/python
	echo Starting run_minimizer.py
	date
	$PYTHONTESTRUNNER run_minimizer.py -failfile=$BUILD_DIR/escript/test/python/run_minimizer.failed -skipfile=$BUILD_DIR/escript/test/python/run_minimizer.skipped || failed run_minimizer.py
	echo Completed run_minimizer.py
}
finley () {
	if [ ! -d $BUILD_DIR/finley/test/python ]
	then
		mkdir -p $BUILD_DIR/finley/test/python
	fi
	export FINLEY_TEST_DATA=$BATCH_ROOT/finley/test/python
	export FINLEY_WORKDIR=$BUILD_DIR/finley/test/python
	if [ ! -d $BATCH_ROOT/finley/test/python ]
	then
		mkdir -p $BATCH_ROOT/finley/test/python
	fi
	export PYTHONPATH=$BATCH_ROOT/escriptcore/test/python:$BATCH_ROOT/finley/test/python:$OLD_PYTHON
	cd $BATCH_ROOT/finley/test/python
	echo Starting run_escriptOnFinley.py
	date
	$PYTHONTESTRUNNER run_escriptOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_escriptOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_escriptOnFinley.skipped || failed run_escriptOnFinley.py
	echo Completed run_escriptOnFinley.py
	echo Starting run_generators.py
	date
	$PYTHONTESTRUNNER run_generators.py -failfile=$BUILD_DIR/finley/test/python/run_generators.failed -skipfile=$BUILD_DIR/finley/test/python/run_generators.skipped || failed run_generators.py
	echo Completed run_generators.py
	echo Starting run_inputOutput.py
	date
	$PYTHONTESTRUNNER run_inputOutput.py -failfile=$BUILD_DIR/finley/test/python/run_inputOutput.failed -skipfile=$BUILD_DIR/finley/test/python/run_inputOutput.skipped || failed run_inputOutput.py
	echo Completed run_inputOutput.py
	echo Starting run_linearPDEsOnFinley1_2D1.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnFinley1_2D1.py -failfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_2D1.failed -skipfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_2D1.skipped || failed run_linearPDEsOnFinley1_2D1.py
	echo Completed run_linearPDEsOnFinley1_2D1.py
	echo Starting run_linearPDEsOnFinley1_2D2.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnFinley1_2D2.py -failfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_2D2.failed -skipfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_2D2.skipped || failed run_linearPDEsOnFinley1_2D2.py
	echo Completed run_linearPDEsOnFinley1_2D2.py
	echo Starting run_linearPDEsOnFinley1_3D1.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnFinley1_3D1.py -failfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_3D1.failed -skipfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_3D1.skipped || failed run_linearPDEsOnFinley1_3D1.py
	echo Completed run_linearPDEsOnFinley1_3D1.py
	echo Starting run_linearPDEsOnFinley1_3D2_part1.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnFinley1_3D2_part1.py -failfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_3D2_part1.failed -skipfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_3D2_part1.skipped || failed run_linearPDEsOnFinley1_3D2_part1.py
	echo Completed run_linearPDEsOnFinley1_3D2_part1.py
	echo Starting run_linearPDEsOnFinley1_3D2_part2.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnFinley1_3D2_part2.py -failfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_3D2_part2.failed -skipfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_3D2_part2.skipped || failed run_linearPDEsOnFinley1_3D2_part2.py
	echo Completed run_linearPDEsOnFinley1_3D2_part2.py
	echo Starting run_linearPDEsOnFinley1_3D2_part3.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnFinley1_3D2_part3.py -failfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_3D2_part3.failed -skipfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley1_3D2_part3.skipped || failed run_linearPDEsOnFinley1_3D2_part3.py
	echo Completed run_linearPDEsOnFinley1_3D2_part3.py
	echo Starting run_linearPDEsOnFinley2.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnFinley2.py -failfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley2.failed -skipfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley2.skipped || failed run_linearPDEsOnFinley2.py
	echo Completed run_linearPDEsOnFinley2.py
	echo Starting run_linearPDEsOnFinley3.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnFinley3.py -failfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley3.failed -skipfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinley3.skipped || failed run_linearPDEsOnFinley3.py
	echo Completed run_linearPDEsOnFinley3.py
	echo Starting run_linearPDEsOnFinleyMacro.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnFinleyMacro.py -failfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinleyMacro.failed -skipfile=$BUILD_DIR/finley/test/python/run_linearPDEsOnFinleyMacro.skipped || failed run_linearPDEsOnFinleyMacro.py
	echo Completed run_linearPDEsOnFinleyMacro.py
	echo Starting run_mklSolverOnFinley.py
	date
	$PYTHONTESTRUNNER run_mklSolverOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_mklSolverOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_mklSolverOnFinley.skipped || failed run_mklSolverOnFinley.py
	echo Completed run_mklSolverOnFinley.py
	echo Starting run_mumpsComplexSolverOnFinley.py
	date
	$PYTHONTESTRUNNER run_mumpsComplexSolverOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_mumpsComplexSolverOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_mumpsComplexSolverOnFinley.skipped || failed run_mumpsComplexSolverOnFinley.py
	echo Completed run_mumpsComplexSolverOnFinley.py
	echo Starting run_mumpsSolverOnFinley.py
	date
	$PYTHONTESTRUNNER run_mumpsSolverOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_mumpsSolverOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_mumpsSolverOnFinley.skipped || failed run_mumpsSolverOnFinley.py
	echo Completed run_mumpsSolverOnFinley.py
	echo Starting run_nonlinearPDEsOnFinley.py
	date
	$PYTHONTESTRUNNER run_nonlinearPDEsOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_nonlinearPDEsOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_nonlinearPDEsOnFinley.skipped || failed run_nonlinearPDEsOnFinley.py
	echo Completed run_nonlinearPDEsOnFinley.py
	echo Starting run_pasoSolversOnFinley.py
	date
	$PYTHONTESTRUNNER run_pasoSolversOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_pasoSolversOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_pasoSolversOnFinley.skipped || failed run_pasoSolversOnFinley.py
	echo Completed run_pasoSolversOnFinley.py
	echo Starting run_trilinosComplexSolversOnFinley.py
	date
	$PYTHONTESTRUNNER run_trilinosComplexSolversOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_trilinosComplexSolversOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_trilinosComplexSolversOnFinley.skipped || failed run_trilinosComplexSolversOnFinley.py
	echo Completed run_trilinosComplexSolversOnFinley.py
	echo Starting run_trilinosSolversOnFinley.py
	date
	$PYTHONTESTRUNNER run_trilinosSolversOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_trilinosSolversOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_trilinosSolversOnFinley.skipped || failed run_trilinosSolversOnFinley.py
	echo Completed run_trilinosSolversOnFinley.py
	echo Starting run_umfpackSolverOnFinley.py
	date
	$PYTHONTESTRUNNER run_umfpackSolverOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_umfpackSolverOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_umfpackSolverOnFinley.skipped || failed run_umfpackSolverOnFinley.py
	echo Completed run_umfpackSolverOnFinley.py
	echo Starting run_utilOnFinley.py
	date
	$PYTHONTESTRUNNER run_utilOnFinley.py -failfile=$BUILD_DIR/finley/test/python/run_utilOnFinley.failed -skipfile=$BUILD_DIR/finley/test/python/run_utilOnFinley.skipped || failed run_utilOnFinley.py
	echo Completed run_utilOnFinley.py
}
oxley () {
	if [ ! -d $BUILD_DIR/oxley/test/python ]
	then
		mkdir -p $BUILD_DIR/oxley/test/python
	fi
	export OXLEY_TEST_DATA=$BATCH_ROOT/oxley/test/python
	export OXLEY_WORKDIR=$BUILD_DIR/oxley/test/python
	if [ ! -d $BATCH_ROOT/oxley/test/python ]
	then
		mkdir -p $BATCH_ROOT/oxley/test/python
	fi
	export PYTHONPATH=$BATCH_ROOT/escriptcore/test/python:$BATCH_ROOT/oxley/test/python:$OLD_PYTHON
	cd $BATCH_ROOT/oxley/test/python
	echo Starting run_PASOSolversOnOxley.py
	date
	$PYTHONTESTRUNNER run_PASOSolversOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_PASOSolversOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_PASOSolversOnOxley.skipped || failed run_PASOSolversOnOxley.py
	echo Completed run_PASOSolversOnOxley.py
	echo Starting run_customAssemblersOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_customAssemblersOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_customAssemblersOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_customAssemblersOnMultiRes.skipped || failed run_customAssemblersOnMultiRes.py
	echo Completed run_customAssemblersOnMultiRes.py
	echo Starting run_customAssemblersOnOxley.py
	date
	$PYTHONTESTRUNNER run_customAssemblersOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_customAssemblersOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_customAssemblersOnOxley.skipped || failed run_customAssemblersOnOxley.py
	echo Completed run_customAssemblersOnOxley.py
	echo Starting run_diracOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_diracOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_diracOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_diracOnMultiRes.skipped || failed run_diracOnMultiRes.py
	echo Completed run_diracOnMultiRes.py
	echo Starting run_diracOnOxley.py
	date
	$PYTHONTESTRUNNER run_diracOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_diracOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_diracOnOxley.skipped || failed run_diracOnOxley.py
	echo Completed run_diracOnOxley.py
	echo Starting run_escriptOnMultiResolution.py
	date
	$PYTHONTESTRUNNER run_escriptOnMultiResolution.py -failfile=$BUILD_DIR/oxley/test/python/run_escriptOnMultiResolution.failed -skipfile=$BUILD_DIR/oxley/test/python/run_escriptOnMultiResolution.skipped || failed run_escriptOnMultiResolution.py
	echo Completed run_escriptOnMultiResolution.py
	echo Starting run_escriptOnOxley.py
	date
	$PYTHONTESTRUNNER run_escriptOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_escriptOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_escriptOnOxley.skipped || failed run_escriptOnOxley.py
	echo Completed run_escriptOnOxley.py
	echo Starting run_linearPDEsOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_linearPDEsOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_linearPDEsOnMultiRes.skipped || failed run_linearPDEsOnMultiRes.py
	echo Completed run_linearPDEsOnMultiRes.py
	echo Starting run_linearPDEsOnOxley.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_linearPDEsOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_linearPDEsOnOxley.skipped || failed run_linearPDEsOnOxley.py
	echo Completed run_linearPDEsOnOxley.py
	echo Starting run_mklSolversOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_mklSolversOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_mklSolversOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_mklSolversOnMultiRes.skipped || failed run_mklSolversOnMultiRes.py
	echo Completed run_mklSolversOnMultiRes.py
	echo Starting run_mklSolversOnRipley.py
	date
	$PYTHONTESTRUNNER run_mklSolversOnRipley.py -failfile=$BUILD_DIR/oxley/test/python/run_mklSolversOnRipley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_mklSolversOnRipley.skipped || failed run_mklSolversOnRipley.py
	echo Completed run_mklSolversOnRipley.py
	echo Starting run_mumpsComplexSolverOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_mumpsComplexSolverOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_mumpsComplexSolverOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_mumpsComplexSolverOnMultiRes.skipped || failed run_mumpsComplexSolverOnMultiRes.py
	echo Completed run_mumpsComplexSolverOnMultiRes.py
	echo Starting run_mumpsComplexSolverOnOxley.py
	date
	$PYTHONTESTRUNNER run_mumpsComplexSolverOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_mumpsComplexSolverOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_mumpsComplexSolverOnOxley.skipped || failed run_mumpsComplexSolverOnOxley.py
	echo Completed run_mumpsComplexSolverOnOxley.py
	echo Starting run_mumpsSolverOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_mumpsSolverOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_mumpsSolverOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_mumpsSolverOnMultiRes.skipped || failed run_mumpsSolverOnMultiRes.py
	echo Completed run_mumpsSolverOnMultiRes.py
	echo Starting run_mumpsSolverOnOxley.py
	date
	$PYTHONTESTRUNNER run_mumpsSolverOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_mumpsSolverOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_mumpsSolverOnOxley.skipped || failed run_mumpsSolverOnOxley.py
	echo Completed run_mumpsSolverOnOxley.py
	echo Starting run_nonlinearPDEOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_nonlinearPDEOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_nonlinearPDEOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_nonlinearPDEOnMultiRes.skipped || failed run_nonlinearPDEOnMultiRes.py
	echo Completed run_nonlinearPDEOnMultiRes.py
	echo Starting run_nonlinearPDEOnOxley.py
	date
	$PYTHONTESTRUNNER run_nonlinearPDEOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_nonlinearPDEOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_nonlinearPDEOnOxley.skipped || failed run_nonlinearPDEOnOxley.py
	echo Completed run_nonlinearPDEOnOxley.py
	echo Starting run_readWriteOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_readWriteOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_readWriteOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_readWriteOnMultiRes.skipped || failed run_readWriteOnMultiRes.py
	echo Completed run_readWriteOnMultiRes.py
	echo Starting run_readWriteOnOxley.py
	date
	$PYTHONTESTRUNNER run_readWriteOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_readWriteOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_readWriteOnOxley.skipped || failed run_readWriteOnOxley.py
	echo Completed run_readWriteOnOxley.py
	echo Starting run_refinementZones.py
	date
	$PYTHONTESTRUNNER run_refinementZones.py -failfile=$BUILD_DIR/oxley/test/python/run_refinementZones.failed -skipfile=$BUILD_DIR/oxley/test/python/run_refinementZones.skipped || failed run_refinementZones.py
	echo Completed run_refinementZones.py
	echo Starting run_splitworldOnOxley.py
	date
	$PYTHONTESTRUNNER run_splitworldOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_splitworldOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_splitworldOnOxley.skipped || failed run_splitworldOnOxley.py
	echo Completed run_splitworldOnOxley.py
	echo Starting run_tests.py
	date
	$PYTHONTESTRUNNER run_tests.py -failfile=$BUILD_DIR/oxley/test/python/run_tests.failed -skipfile=$BUILD_DIR/oxley/test/python/run_tests.skipped || failed run_tests.py
	echo Completed run_tests.py
	echo Starting run_trilinosComplexSolversOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_trilinosComplexSolversOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_trilinosComplexSolversOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_trilinosComplexSolversOnMultiRes.skipped || failed run_trilinosComplexSolversOnMultiRes.py
	echo Completed run_trilinosComplexSolversOnMultiRes.py
	echo Starting run_trilinosComplexSolversOnOxley.py
	date
	$PYTHONTESTRUNNER run_trilinosComplexSolversOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_trilinosComplexSolversOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_trilinosComplexSolversOnOxley.skipped || failed run_trilinosComplexSolversOnOxley.py
	echo Completed run_trilinosComplexSolversOnOxley.py
	echo Starting run_trilinosSolversOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_trilinosSolversOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_trilinosSolversOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_trilinosSolversOnMultiRes.skipped || failed run_trilinosSolversOnMultiRes.py
	echo Completed run_trilinosSolversOnMultiRes.py
	echo Starting run_trilinosSolversOnOxley.py
	date
	$PYTHONTESTRUNNER run_trilinosSolversOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_trilinosSolversOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_trilinosSolversOnOxley.skipped || failed run_trilinosSolversOnOxley.py
	echo Completed run_trilinosSolversOnOxley.py
	echo Starting run_umfpackSolversOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_umfpackSolversOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_umfpackSolversOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_umfpackSolversOnMultiRes.skipped || failed run_umfpackSolversOnMultiRes.py
	echo Completed run_umfpackSolversOnMultiRes.py
	echo Starting run_umfpackSolversOnOxley.py
	date
	$PYTHONTESTRUNNER run_umfpackSolversOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_umfpackSolversOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_umfpackSolversOnOxley.skipped || failed run_umfpackSolversOnOxley.py
	echo Completed run_umfpackSolversOnOxley.py
	echo Starting run_utilOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_utilOnMultiRes.py -failfile=$BUILD_DIR/oxley/test/python/run_utilOnMultiRes.failed -skipfile=$BUILD_DIR/oxley/test/python/run_utilOnMultiRes.skipped || failed run_utilOnMultiRes.py
	echo Completed run_utilOnMultiRes.py
	echo Starting run_utilOnOxley.py
	date
	$PYTHONTESTRUNNER run_utilOnOxley.py -failfile=$BUILD_DIR/oxley/test/python/run_utilOnOxley.failed -skipfile=$BUILD_DIR/oxley/test/python/run_utilOnOxley.skipped || failed run_utilOnOxley.py
	echo Completed run_utilOnOxley.py
}
ripley () {
	if [ ! -d $BUILD_DIR/ripley/test/python ]
	then
		mkdir -p $BUILD_DIR/ripley/test/python
	fi
	export RIPLEY_TEST_DATA=$BATCH_ROOT/ripley/test/python
	export RIPLEY_WORKDIR=$BUILD_DIR/ripley/test/python
	if [ ! -d $BATCH_ROOT/ripley/test/python ]
	then
		mkdir -p $BATCH_ROOT/ripley/test/python
	fi
	export PYTHONPATH=$BATCH_ROOT/escriptcore/test/python:$BATCH_ROOT/ripley/test/python:$OLD_PYTHON
	cd $BATCH_ROOT/ripley/test/python
	echo Starting run_customAssemblersOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_customAssemblersOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_customAssemblersOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_customAssemblersOnMultiRes.skipped || failed run_customAssemblersOnMultiRes.py
	echo Completed run_customAssemblersOnMultiRes.py
	echo Starting run_customAssemblersOnRipley.py
	date
	$PYTHONTESTRUNNER run_customAssemblersOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_customAssemblersOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_customAssemblersOnRipley.skipped || failed run_customAssemblersOnRipley.py
	echo Completed run_customAssemblersOnRipley.py
	echo Starting run_diracOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_diracOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_diracOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_diracOnMultiRes.skipped || failed run_diracOnMultiRes.py
	echo Completed run_diracOnMultiRes.py
	echo Starting run_diracOnRipley.py
	date
	$PYTHONTESTRUNNER run_diracOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_diracOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_diracOnRipley.skipped || failed run_diracOnRipley.py
	echo Completed run_diracOnRipley.py
	echo Starting run_escriptOnMultiResolution.py
	date
	$PYTHONTESTRUNNER run_escriptOnMultiResolution.py -failfile=$BUILD_DIR/ripley/test/python/run_escriptOnMultiResolution.failed -skipfile=$BUILD_DIR/ripley/test/python/run_escriptOnMultiResolution.skipped || failed run_escriptOnMultiResolution.py
	echo Completed run_escriptOnMultiResolution.py
	echo Starting run_escriptOnRipley.py
	date
	$PYTHONTESTRUNNER run_escriptOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_escriptOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_escriptOnRipley.skipped || failed run_escriptOnRipley.py
	echo Completed run_escriptOnRipley.py
	echo Starting run_linearPDEsOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_linearPDEsOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_linearPDEsOnMultiRes.skipped || failed run_linearPDEsOnMultiRes.py
	echo Completed run_linearPDEsOnMultiRes.py
	echo Starting run_linearPDEsOnRipley.py
	date
	$PYTHONTESTRUNNER run_linearPDEsOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_linearPDEsOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_linearPDEsOnRipley.skipped || failed run_linearPDEsOnRipley.py
	echo Completed run_linearPDEsOnRipley.py
	echo Starting run_mklSolversOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_mklSolversOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_mklSolversOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_mklSolversOnMultiRes.skipped || failed run_mklSolversOnMultiRes.py
	echo Completed run_mklSolversOnMultiRes.py
	echo Starting run_mklSolversOnRipley.py
	date
	$PYTHONTESTRUNNER run_mklSolversOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_mklSolversOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_mklSolversOnRipley.skipped || failed run_mklSolversOnRipley.py
	echo Completed run_mklSolversOnRipley.py
	echo Starting run_mumpsComplexSolverOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_mumpsComplexSolverOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_mumpsComplexSolverOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_mumpsComplexSolverOnMultiRes.skipped || failed run_mumpsComplexSolverOnMultiRes.py
	echo Completed run_mumpsComplexSolverOnMultiRes.py
	echo Starting run_mumpsComplexSolverOnRipley.py
	date
	$PYTHONTESTRUNNER run_mumpsComplexSolverOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_mumpsComplexSolverOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_mumpsComplexSolverOnRipley.skipped || failed run_mumpsComplexSolverOnRipley.py
	echo Completed run_mumpsComplexSolverOnRipley.py
	echo Starting run_mumpsSolverOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_mumpsSolverOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_mumpsSolverOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_mumpsSolverOnMultiRes.skipped || failed run_mumpsSolverOnMultiRes.py
	echo Completed run_mumpsSolverOnMultiRes.py
	echo Starting run_mumpsSolverOnRipley.py
	date
	$PYTHONTESTRUNNER run_mumpsSolverOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_mumpsSolverOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_mumpsSolverOnRipley.skipped || failed run_mumpsSolverOnRipley.py
	echo Completed run_mumpsSolverOnRipley.py
	echo Starting run_nonlinearPDEOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_nonlinearPDEOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_nonlinearPDEOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_nonlinearPDEOnMultiRes.skipped || failed run_nonlinearPDEOnMultiRes.py
	echo Completed run_nonlinearPDEOnMultiRes.py
	echo Starting run_nonlinearPDEOnRipley.py
	date
	$PYTHONTESTRUNNER run_nonlinearPDEOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_nonlinearPDEOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_nonlinearPDEOnRipley.skipped || failed run_nonlinearPDEOnRipley.py
	echo Completed run_nonlinearPDEOnRipley.py
	echo Starting run_pasoSolversOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_pasoSolversOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_pasoSolversOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_pasoSolversOnMultiRes.skipped || failed run_pasoSolversOnMultiRes.py
	echo Completed run_pasoSolversOnMultiRes.py
	echo Starting run_pasoSolversOnRipley.py
	date
	$PYTHONTESTRUNNER run_pasoSolversOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_pasoSolversOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_pasoSolversOnRipley.skipped || failed run_pasoSolversOnRipley.py
	echo Completed run_pasoSolversOnRipley.py
	echo Starting run_readWriteOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_readWriteOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_readWriteOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_readWriteOnMultiRes.skipped || failed run_readWriteOnMultiRes.py
	echo Completed run_readWriteOnMultiRes.py
	echo Starting run_readWriteOnRipley.py
	date
	$PYTHONTESTRUNNER run_readWriteOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_readWriteOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_readWriteOnRipley.skipped || failed run_readWriteOnRipley.py
	echo Completed run_readWriteOnRipley.py
	echo Starting run_trilinosComplexSolversOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_trilinosComplexSolversOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_trilinosComplexSolversOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_trilinosComplexSolversOnMultiRes.skipped || failed run_trilinosComplexSolversOnMultiRes.py
	echo Completed run_trilinosComplexSolversOnMultiRes.py
	echo Starting run_trilinosComplexSolversOnRipley.py
	date
	$PYTHONTESTRUNNER run_trilinosComplexSolversOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_trilinosComplexSolversOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_trilinosComplexSolversOnRipley.skipped || failed run_trilinosComplexSolversOnRipley.py
	echo Completed run_trilinosComplexSolversOnRipley.py
	echo Starting run_trilinosSolversOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_trilinosSolversOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_trilinosSolversOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_trilinosSolversOnMultiRes.skipped || failed run_trilinosSolversOnMultiRes.py
	echo Completed run_trilinosSolversOnMultiRes.py
	echo Starting run_trilinosSolversOnRipley.py
	date
	$PYTHONTESTRUNNER run_trilinosSolversOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_trilinosSolversOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_trilinosSolversOnRipley.skipped || failed run_trilinosSolversOnRipley.py
	echo Completed run_trilinosSolversOnRipley.py
	echo Starting run_umfpackSolversOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_umfpackSolversOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_umfpackSolversOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_umfpackSolversOnMultiRes.skipped || failed run_umfpackSolversOnMultiRes.py
	echo Completed run_umfpackSolversOnMultiRes.py
	echo Starting run_umfpackSolversOnRipley.py
	date
	$PYTHONTESTRUNNER run_umfpackSolversOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_umfpackSolversOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_umfpackSolversOnRipley.skipped || failed run_umfpackSolversOnRipley.py
	echo Completed run_umfpackSolversOnRipley.py
	echo Starting run_utilOnMultiRes.py
	date
	$PYTHONTESTRUNNER run_utilOnMultiRes.py -failfile=$BUILD_DIR/ripley/test/python/run_utilOnMultiRes.failed -skipfile=$BUILD_DIR/ripley/test/python/run_utilOnMultiRes.skipped || failed run_utilOnMultiRes.py
	echo Completed run_utilOnMultiRes.py
	echo Starting run_utilOnRipley.py
	date
	$PYTHONTESTRUNNER run_utilOnRipley.py -failfile=$BUILD_DIR/ripley/test/python/run_utilOnRipley.failed -skipfile=$BUILD_DIR/ripley/test/python/run_utilOnRipley.skipped || failed run_utilOnRipley.py
	echo Completed run_utilOnRipley.py
}
speckley () {
	if [ ! -d $BUILD_DIR/speckley/test/python ]
	then
		mkdir -p $BUILD_DIR/speckley/test/python
	fi
	export SPECKLEY_TEST_DATA=$BATCH_ROOT/speckley/test/python
	export SPECKLEY_WORKDIR=$BUILD_DIR/speckley/test/python
	if [ ! -d $BATCH_ROOT/speckley/test/python ]
	then
		mkdir -p $BATCH_ROOT/speckley/test/python
	fi
	export PYTHONPATH=$BATCH_ROOT/escriptcore/test/python:$BATCH_ROOT/speckley/test/python:$OLD_PYTHON
	cd $BATCH_ROOT/speckley/test/python
	echo Starting run_SpeckleyRipleyCoupler.py
	date
	$PYTHONTESTRUNNER run_SpeckleyRipleyCoupler.py -failfile=$BUILD_DIR/speckley/test/python/run_SpeckleyRipleyCoupler.failed -skipfile=$BUILD_DIR/speckley/test/python/run_SpeckleyRipleyCoupler.skipped || failed run_SpeckleyRipleyCoupler.py
	echo Completed run_SpeckleyRipleyCoupler.py
	echo Starting run_customAssemblersOnSpeckley.py
	date
	$PYTHONTESTRUNNER run_customAssemblersOnSpeckley.py -failfile=$BUILD_DIR/speckley/test/python/run_customAssemblersOnSpeckley.failed -skipfile=$BUILD_DIR/speckley/test/python/run_customAssemblersOnSpeckley.skipped || failed run_customAssemblersOnSpeckley.py
	echo Completed run_customAssemblersOnSpeckley.py
	echo Starting run_diracOnSpeckley.py
	date
	$PYTHONTESTRUNNER run_diracOnSpeckley.py -failfile=$BUILD_DIR/speckley/test/python/run_diracOnSpeckley.failed -skipfile=$BUILD_DIR/speckley/test/python/run_diracOnSpeckley.skipped || failed run_diracOnSpeckley.py
	echo Completed run_diracOnSpeckley.py
	echo Starting run_readWriteOnSpeckley.py
	date
	$PYTHONTESTRUNNER run_readWriteOnSpeckley.py -failfile=$BUILD_DIR/speckley/test/python/run_readWriteOnSpeckley.failed -skipfile=$BUILD_DIR/speckley/test/python/run_readWriteOnSpeckley.skipped || failed run_readWriteOnSpeckley.py
	echo Completed run_readWriteOnSpeckley.py
	echo Starting run_specialOnSpeckley.py
	date
	$PYTHONTESTRUNNER run_specialOnSpeckley.py -failfile=$BUILD_DIR/speckley/test/python/run_specialOnSpeckley.failed -skipfile=$BUILD_DIR/speckley/test/python/run_specialOnSpeckley.skipped || failed run_specialOnSpeckley.py
	echo Completed run_specialOnSpeckley.py
}
weipa () {
	if [ ! -d $BUILD_DIR/weipa/test/python ]
	then
		mkdir -p $BUILD_DIR/weipa/test/python
	fi
	export WEIPA_TEST_DATA=$BATCH_ROOT/weipa/test/python
	export WEIPA_WORKDIR=$BUILD_DIR/weipa/test/python
	if [ ! -d $BATCH_ROOT/weipa/test/python ]
	then
		mkdir -p $BATCH_ROOT/weipa/test/python
	fi
	export PYTHONPATH=$BATCH_ROOT/escriptcore/test/python:$BATCH_ROOT/weipa/test/python:$OLD_PYTHON
	cd $BATCH_ROOT/weipa/test/python
	echo Starting run_savevtk_tests.py
	date
	$PYTHONTESTRUNNER run_savevtk_tests.py -failfile=$BUILD_DIR/weipa/test/python/run_savevtk_tests.failed -skipfile=$BUILD_DIR/weipa/test/python/run_savevtk_tests.skipped || failed run_savevtk_tests.py
	echo Completed run_savevtk_tests.py
	echo Starting run_savesilo_tests.py
	date
	$PYTHONTESTRUNNER run_savesilo_tests.py -failfile=$BUILD_DIR/weipa/test/python/run_savesilo_tests.failed -skipfile=$BUILD_DIR/weipa/test/python/run_savesilo_tests.skipped || failed run_savesilo_tests.py
	echo Completed run_savesilo_tests.py
}
usersguide () {
	if [ ! -d $BATCH_ROOT/doc/examples/usersguide ]
	then
		mkdir -p $BATCH_ROOT/doc/examples/usersguide
	fi
	export PYTHONPATH=$OLD_PYTHON
	cd $BATCH_ROOT/doc/examples/usersguide
	if [ $MPIPROD -le 1 ]; then
		echo Starting trapezoid.py
		date
		$PYTHONRUNNER trapezoid.py || failed trapezoid.py
		echo Completed trapezoid.py
		echo Starting quad.py
		date
		$PYTHONRUNNER quad.py || failed quad.py
		echo Completed quad.py
		echo Starting brick.py
		date
		$PYTHONRUNNER brick.py || failed brick.py
		echo Completed brick.py
		echo Starting refine.py
		date
		$PYTHONRUNNER refine.py || failed refine.py
		echo Completed refine.py
		echo Starting poisson_matplotlib.py
		date
		$PYTHONRUNNER poisson_matplotlib.py || failed poisson_matplotlib.py
		echo Completed poisson_matplotlib.py
		echo Starting rosenbrock.py
		date
		$PYTHONRUNNER rosenbrock.py || failed rosenbrock.py
		echo Completed rosenbrock.py
		echo Starting MT.py
		date
		$PYTHONRUNNER MT.py || failed MT.py
		echo Completed MT.py
	fi
	echo Starting heatedblock.py
	date
	$PYTHONRUNNER heatedblock.py || failed heatedblock.py
	echo Completed heatedblock.py
	echo Starting helmholtz.py
	date
	$PYTHONRUNNER helmholtz.py || failed helmholtz.py
	echo Completed helmholtz.py
	echo Starting poisson.py
	date
	$PYTHONRUNNER poisson.py || failed poisson.py
	echo Completed poisson.py
	echo Starting diffusion.py
	date
	$PYTHONRUNNER diffusion.py || failed diffusion.py
	echo Completed diffusion.py
	echo Starting poisson_vtk.py
	date
	$PYTHONRUNNER poisson_vtk.py || failed poisson_vtk.py
	echo Completed poisson_vtk.py
	echo Starting dirac.py
	date
	$PYTHONRUNNER dirac.py || failed dirac.py
	echo Completed dirac.py
	echo Starting int_save.py
	date
	$PYTHONRUNNER int_save.py || failed int_save.py
	echo Completed int_save.py
	echo Starting wave.py
	date
	$PYTHONRUNNER wave.py || failed wave.py
	echo Completed wave.py
}
cookbook () {
	if [ ! -d $BATCH_ROOT/doc/examples/cookbook ]
	then
		mkdir -p $BATCH_ROOT/doc/examples/cookbook
	fi
	export PYTHONPATH=$OLD_PYTHON
	cd $BATCH_ROOT/doc/examples/cookbook
	if [ $MPIPROD -le 1 ]; then
		echo Starting example01c.py
		date
		$PYTHONRUNNER example01c.py || failed example01c.py
		echo Completed example01c.py
		echo Starting example02.py
		date
		$PYTHONRUNNER example02.py || failed example02.py
		echo Completed example02.py
		echo Starting example03a.py
		date
		$PYTHONRUNNER example03a.py || failed example03a.py
		echo Completed example03a.py
		echo Starting example04a.py
		date
		$PYTHONRUNNER example04a.py || failed example04a.py
		echo Completed example04a.py
		echo Starting example04b.py
		date
		$PYTHONRUNNER example04b.py || failed example04b.py
		echo Completed example04b.py
		echo Starting example05a.py
		date
		$PYTHONRUNNER example05a.py || failed example05a.py
		echo Completed example05a.py
		echo Starting example05b.py
		date
		$PYTHONRUNNER example05b.py || failed example05b.py
		echo Completed example05b.py
		echo Starting example05c.py
		date
		$PYTHONRUNNER example05c.py || failed example05c.py
		echo Completed example05c.py
		echo Starting example06.py
		date
		$PYTHONRUNNER example06.py || failed example06.py
		echo Completed example06.py
		echo Starting example07a.py
		date
		$PYTHONRUNNER example07a.py || failed example07a.py
		echo Completed example07a.py
		echo Starting example07b.py
		date
		$PYTHONRUNNER example07b.py || failed example07b.py
		echo Completed example07b.py
		echo Starting example08a.py
		date
		$PYTHONRUNNER example08a.py || failed example08a.py
		echo Completed example08a.py
		echo Starting example08b.py
		date
		$PYTHONRUNNER example08b.py || failed example08b.py
		echo Completed example08b.py
		echo Starting example08c.py
		date
		$PYTHONRUNNER example08c.py || failed example08c.py
		echo Completed example08c.py
		echo Starting example09m.py
		date
		$PYTHONRUNNER example09m.py || failed example09m.py
		echo Completed example09m.py
		echo Starting example09a.py
		date
		$PYTHONRUNNER example09a.py || failed example09a.py
		echo Completed example09a.py
		echo Starting example10a.py
		date
		$PYTHONRUNNER example10a.py || failed example10a.py
		echo Completed example10a.py
		echo Starting example10b.py
		date
		$PYTHONRUNNER example10b.py || failed example10b.py
		echo Completed example10b.py
		echo Starting example10m.py
		date
		$PYTHONRUNNER example10m.py || failed example10m.py
		echo Completed example10m.py
		echo Starting example11a.py
		date
		$PYTHONRUNNER example11a.py || failed example11a.py
		echo Completed example11a.py
		echo Starting example11b.py
		date
		$PYTHONRUNNER example11b.py || failed example11b.py
		echo Completed example11b.py
	fi
	echo Starting example01a.py
	date
	$PYTHONRUNNER example01a.py || failed example01a.py
	echo Completed example01a.py
	echo Starting example01b.py
	date
	$PYTHONRUNNER example01b.py || failed example01b.py
	echo Completed example01b.py
	echo Starting example03b.py
	date
	$PYTHONRUNNER example03b.py || failed example03b.py
	echo Completed example03b.py
}
if [ $# -gt 2 ]; then
	eval $3
else
	escript
	escript
	finley
	oxley
	ripley
	speckley
	weipa
	usersguide
	cookbook
fi
find $BUILD_DIR -name '*.failed' | xargs cat; find $BUILD_DIR -name '*.failed' | xargs cat | diff -q - /dev/null >/dev/null
