#
# $Id$
#
#######################################################
#
#           Copyright 2003-2007 by ACceSS MNRF
#       Copyright 2007 by University of Queensland
#
#                http://esscc.uq.edu.au
#        Primary Business: Queensland, Australia
#  Licensed under the Open Software License version 3.0
#     http://www.opensource.org/licenses/osl-3.0.php
#
#######################################################
#

import os
Import('*')

try:
  local_env = env.Clone()	# scons-98.03
except AttributeError:
  local_env = env.Copy()	# scons-96.92

latexmode='-interaction=nonstopmode'

tex_dir = local_env.Dir('.').srcnode().abspath
tex= [ env.File(x) for x in os.listdir(tex_dir) if not x.startswith('.') and not os.path.isdir(tex_dir+os.path.sep+x) and os.path.splitext(x)[1] in ['.tex', '.bib', '.sty', '.cfg', '.cls'] ] + \
     [ env.File('figures'+os.path.sep+x) for x in os.listdir(tex_dir+os.path.sep+'figures') if not x.startswith('.') ]

env.Command(env['prefix']+'/release/doc/user/guide.pdf',tex,
            [ "latex %s guide.tex"%latexmode,  \
              "bibtex guide",                  \
              "makeindex guide",               \
              "latex %s guide"%latexmode,      \
              "latex %s guide"%latexmode,      \
              "dvipdf guide.dvi %s"%env['prefix']+'/release/doc/user/guide.pdf' ],
            chdir=tex_dir)
env.Alias('guide_pdf', env['prefix']+'/release/doc/user/guide.pdf')


env.Command(env['prefix']+'/release/doc/user/html/index.htm',tex,			      \
		        ["latex2html -top_navigation                                  \
                        -bottom_navigation                                            \
                        -index_in_navigation                                          \
                        -contents_in_navigation                                       \
                        -next_page_in_navigation                                      \
                        -previous_page_in_navigation                                  \
                        -title \"esys users guide\"                                   \
                        -noshow_section_numbers                                       \
                        -dir \"../../release/doc/user/html\" -mkdir		      \
                        -address \"esys@esscc.uq.edu.au\"                             \
                        -antialias_text -antialias -transparent                       \
                        -noshort_extn                                                 \
                        -up_url \"http://www.access.edu.au/escript\",		      \
			-up_title \"escript\" guide.tex"], chdir=tex_dir)
env.Alias('guide_html', env['prefix']+'/release/doc/user/html/index.htm')

