{% set version = "5.9" %}

package:
    name: esys-escript
    version: {{ version }}
source:
    - url: https://github.com/Unidata/netcdf-cxx4/archive/v4.3.1.tar.gz
      sha256: e3fe3d2ec06c1c2772555bf1208d220aab5fee186d04bd265219b0bc7a978edc
      folder: netcdf-cxx4
      patches: netcdf-cxx4.patch
    - url: https://github.com/esys-escript/esys-escript.github.io/archive/refs/tags/5.9pre.tar.gz
      sha256: 076ffae508aa7b1d9e4b2075e3592a0743146a48e31d3489c892ff223b9ec6a6
      folder: escript
build:
    skip: True  # [win]
    skip: True  # [osx]
    number: 0
requirements:
    build:
        - {{ compiler('cxx') }}
        - scons >3.0.5 
        - cmake
        - make
        - python
        - numpy
        - mumps
        - git
    host:
        - boost-cpp
        - boost
        - libboost
        - numpy
        - python 
        - matplotlib
        - hdf5  # [linux]
        - libblas  # [linux]
        - scipy 
        - suitesparse  # [linux]
        - sympy
        - mumps
        - libblas <=3.8.0   # [linux and py==38]
        - libblas <=3.8.0   # [linux and py==37]
    run:
        - boost-cpp
        - boost
        - libboost
        - numpy
        - python 
        - matplotlib
        - hdf5  # [linux]
        - libblas  # [linux]
        - scipy 
        - suitesparse  # [linux]
        - sympy
        - mumps
        - libblas <=3.8.0   # [linux and py==38]
        - libblas <=3.8.0   # [linux and py==37]
test:
    commands:
        - run-escript -c
        - run-escript /tmp/release_sanity.py  # [linux]
        - run-escript %TEMP%/release_sanity.py  # [win]
about:
    home: https://github.com/LutzGross/esys-escript.github.io
    summary: esys-escript is a programming tool for implementing mathematical 
        models in python using the finite element method (FEM).
    license: Apache-2.0
    license_file: LICENSE
    description: esys-escript is a programming tool for implementing 
        mathematical models in python using the finite element method (FEM). 
        As users do not access the data structures it is very easy to use and 
        scripts can run on desktop computers as well as highly parallel
        supercomputer without changes. Application areas for escript include 
        earth mantle convection, geophysical inversion, earthquakes, 
        porous media flow, reactive transport, plate subduction, erosion, 
        and tsunamis.
    dev_url: https://github.com/LutzGross/esys-escript.github.io
    doc_url: https://github.com/LutzGross/esys-escript.github.io
    doc_source_url: https://github.com/LutzGross/esys-escript.github.io

extra:
    recipe-maintainers:
        - esys-escript
