libinstall = None

Import('*')

import os
import string

bruce_path = str(esysroot) + '/bruce/inc'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'

cpp_path = [bruce_path,
            escript_path,
            esysUtils_path,
            python_path,
            boost_path]

lib = 'brucecpp'
sources = ['Bruce.cpp',
           'BruceFactory.cpp',
           'brucecpp.cpp']

bruce_env = Environment(ENV = os.environ)

bruce_env.Replace(CXX = cxx)
bruce_env.Replace(SHOBJSUFFIX = '.lo')
bruce_env.Replace(CXXFLAGS = cxx_flags)
bruce_env.Replace(CPPPATH = cpp_path)

bruce_lib = bruce_env.SharedLibrary(lib, sources)
bruce_env.Install(libdir, bruce_lib)

if libinstall != None:
  bruce_env.Install(libinstall, bruce_lib)
