Import('*')

local_env=env.Copy()

src_dir = local_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
sources = [x for x in filenames if os.path.splitext(x)[1] in ['.cpp', '.c']]
headers = [x for x in filenames if os.path.splitext(x)[1] in ['.h']]
# Filter out sources that should not be in the list automatically

lib_name = 'CppUnitTest'

local_env.Append(CPPPATH=['#/tools/CppUnitTest/inc',])

lib = local_env.StaticLibrary(lib_name, sources)

local_env.Install(libinstall, lib)
