
##############################################################################
#
# Copyright (c) 2003-2012 by University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development since 2012 by School of Earth Sciences
#
##############################################################################

Import('*')
local_env = env.Clone()

# get the test source file names
sources = Glob('*.py')

# compile
pyc = local_env.PyCompile(sources)
local_env.Depends(pyc, py_wrapper_lib)

# install
py_inst = local_env.Install(local_env['pyinstall']+'/weipa', pyc)
env.Alias('install_weipa_py', py_inst)

