#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       

import os
Import('*')

tmp = env.Command(env['prefix']+'/release/doc/doxygen', env['pyinstall'], [Mkdir(env['prefix']+'/release/doc/doxygen'), "doxygen doc/doxygen/doxygen_esys"])
env.Alias('api_doxygen', env['prefix']+'/release/doc/doxygen')

