Import('*')

import os
import string

mmio_path = str(esysroot) + '/tools/mmio/inc'

cpp_path = [mmio_path]

lib = 'mmio'
sources = ['mmio.c']

mmio_env = Environment(ENV = os.environ)

mmio_env.Replace(CC = cc)
mmio_env.Replace(CCFLAGS = cc_flags)
mmio_env.Replace(CPPPATH = cpp_path)

mmio_lib = mmio_env.StaticLibrary(lib, sources)
mmio_env.Install(libdir, mmio_lib)
