#!/bin/env bash
# $Id$
# simple script to run all escript unit tests

MODULES="DataEmpty DataConstant DataTagged DataExpanded DataFactory DataArray DataArrayView DataBlocks2D DataVector Taipan DataC DataAlgorithmAdapter FunctionSpace Data"

for module in $MODULES ; do \
	(echo Testing: $module; cd $module; ./unit_test) \
done
