# Scons configuration file for escript

import os
import sys

#
# ensure correct versions of python and scons

EnsurePythonVersion(2,3)
EnsureSConsVersion(0,96)

#
# set appropriate defaults for configuration variables

esysroot = Dir('#..')
libinstall = None
dodebug = 0
usegcc = 0

#
# import configuration variables passed in from
# calling SConscript (if any)

Import('*')

#
# retreive command-line arguments if any

if ARGUMENTS.get('libinstall',0):
  libinstall = ARGUMENTS.get('libinstall',0)
Export(["libinstall"])

if ARGUMENTS.get('debug',0):
  dodebug = 1

if ARGUMENTS.get('usegcc',0):
  usegcc = 1

#
# determine platform

env = Environment(ENV = os.environ)
platform = env['PLATFORM']

#
# determine hostname

hostname = os.environ['HOSTNAME']

#
# export esysroot

Export(["esysroot"])

#
# set and export library directory

libdir = Dir(str(esysroot) + '/escript/lib')
Export(["libdir"])

#
# load and export configuration settings

options_dir = str(esysroot) + '/scons'
sys.path.append(options_dir)

if hostname=='ess':
  from ess_options import *

if usegcc==1:
  from gcc_options import *

if dodebug==1:
  cxx_flags=cxx_flags_debug

Export(["python_path"])
Export(["boost_path"])
Export(["cxx"])
Export(["cxx_flags"])

#
# print out build configuration for this module

print "############################################"
print "Build configuration for module: escript"
print "         dodebug: ", dodebug
print "          usegcc: ", usegcc
print "             cxx: ", cxx
print "        platform: ", platform
print "        hostname: ", hostname
print "      libinstall: ", libinstall
print "############################################"

#
# call the SConscript to do the actual build

SConscript('src/Data/SConscript', src_dir='src/Data', build_dir='obj', duplicate=0)
