# Scons configuration file for doxygen C and C++ docs

#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       
#                                                          
#
#

import os
Import('*')

env.Command(api_doxygen, pyinstall, "doxygen doc/doxygen/doxygen_esys")

