Import('*')

local_env=env.Copy()

src_dir = local_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
python_src = [x for x in filenames if os.path.splitext(x)[1] in ['.py']]

pyc = local_env.PyCompile(python_src)
# env.SConscript(dirs = ['renderers'],duplicate=0)

# local_env.Depends(pyc, dep_lib)
local_env.Install(pyinstall+'/pycad', pyc)

# get all the python files in the release tar file
release_py = [ env.File("SConscript"), ] + [ env.File(x) for x in python_src ]
env.Zip(src_zipfile, release_py)
env.Tar(src_tarfile, release_py)

# Call the unit tests SConscript
local_env.SConscript(dirs = ['#/pycad/test/python'], build_dir='#/build/$PLATFORM/pycad/test/python', duplicate=0)


