#!/bin/sh 
set -e

if [ "$1" = remove ] || [ "$1" = upgrade ]
then
	install-docs -r /usr/share/doc-base/escript-pde-userguide \
			/usr/share/doc-base/escript-pde-install \
			/usr/share/doc-base/escript-pde-pythonapi \
			/usr/share/doc-base/escript-pde-cookbook
fi
