# Scons configuration file for esysUtils

#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       
#                                                          
#
#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

Export(["python_path"])
Export(["boost_path"])
Export(["cxx"])
Export(["cxx_flags"])
Export(["ar_flags"])

#
# print out build configuration for this module

print "Build configuration for module: esysUtils"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

# set and export library directory
libdir = Dir(str(esysroot) + '/esysUtils/lib')
Export(["libdir"])

#
# call the SConscript to do the actual build

SConscript(dirs=['src'], build_dir='obj/src', duplicate=0)
SConscript(dirs=['test/EsysException'], build_dir='obj/test/EsysException', duplicate=0)
