#
# $Id$
#
#######################################################
#
#           Copyright 2003-2007 by ACceSS MNRF
#       Copyright 2007 by University of Queensland
#
#                http://esscc.uq.edu.au
#        Primary Business: Queensland, Australia
#  Licensed under the Open Software License version 3.0
#     http://www.opensource.org/licenses/osl-3.0.php
#
#######################################################
#

import os
Import('*')

try:
  local_env = env.Clone()	# scons-98.03
except AttributeError:
  local_env = env.Copy()	# scons-96.92

sources = """
	TestCase.cpp
	TestFailure.cpp
	TestResult.cpp
	TestRunner.cpp
	TestSuite.cpp
	TextTestResult.cpp
""".split()
headers = """
	CppUnitException.h
	CppUnitTestNamespace.h
	Guards.h
	Test.h
	TestCaller.h
	TestCase.h
	TestFailure.h
	TestResult.h
	TestRunner.h
	TestSuite.h
	TextTestResult.h
	estring.h
""".split()

lib = local_env.StaticLibrary('CppUnitTest', sources)
env.Alias('target_cppunittest_a', lib)

include_path = Dir('tools/CppUnitTest', incinstall)

tmp1 = local_env.Install(include_path, headers )
env.Alias('target_install_cppunittest_headers', [tmp1])

tmp2 = local_env.Install(libinstall, lib)
env.Alias('target_install_cppunittest_a', [tmp2])

