import os
Import('*')

local_env=env.Copy()

sources = """
	TestCase.cpp
	TestFailure.cpp
	TestResult.cpp
	TestRunner.cpp
	TestSuite.cpp
	TextTestResult.cpp
""".split()
headers = """
	CppUnitException.h
	CppUnitTestNamespace.h
	Guards.h
	Test.h
	TestCaller.h
	TestCase.h
	TestFailure.h
	TestResult.h
	TestRunner.h
	TestSuite.h
	TextTestResult.h
	estring.h
""".split()

lib = local_env.StaticLibrary('CppUnitTest', sources)
env.Alias('target_cppunittest_a', lib)

include_path = Dir('tools/CppUnitTest', incinstall)

tmp1 = local_env.Install(include_path, headers )
env.Alias('target_install_cppunittest_headers', [tmp1])

tmp2 = local_env.Install(libinstall, lib)
env.Alias('target_install_cppunittest_a', [tmp2])

