# Scons configuration file for paso
esysroot=str(Dir('./..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))
# set and export library directories

libdir = Dir(str(esysroot) + '/paso/lib')
Export(["libdir"])
libdir2 = Dir(str(esysroot) + '/lib')
Export(["libdir2"])

#
# load and export configuration settings

Export(["scsl_path","scsl_libs"])
Export(["mkl_path","mkl_libs"])
Export(["umfpack_path","umfpack_libs"])
Export(["python_path"])
Export(["boost_path"])
Export(["cc"])
Export(["cc_flags"])
Export(["ar_flags"])

#
# print out build configuration for this module

print "Build configuration for module: paso"
print "              cc: ", cc
print "        cc_flags: ", cc_flags
# call the SConscript to do the actual build

SConscript('src/SConscript', src_dir='src', build_dir='obj', duplicate=0)
