#!/bin/bash
#          Copyright 2006 by ACcESS MNRF
#
#              http://www.access.edu.au
#       Primary Business: Queensland, Australia
#  Licensed under the Open Software License version 3.0
#     http://www.opensource.org/licenses/osl-3.0.php
#
#
#
# $Id: autotest-scons 162 2005-11-11 00:09:59Z svn $
# An explicit testing script for esys using the scons build system

# list of users to email test results to
MAIL_RECIPIENTS="gross@esscc.uq.edu.au elspeth@esscc.uq.edu.au matt@esscc.uq.edu.au robert.woodcock@csiro.au Peter.Hornby@csiro.au"

# the python tests to run
BRUCE_PYTESTS="ImportTest.passed BruceTest.passed test_utilOnBruce.py"
ESCRIPT_PYTESTS="ImportTest.passed BinaryOps.passed UnaryOps.passed SliceGetting.passed SliceSetting.passed MiscTests.passed ArchiveTests.passed newEscriptTests.passed test_xml.passed insituTests.passed s2.passed"
FINLEY_PYTESTS="ImportTest.passed finleyTest.passed SimpleSolve.passed RecTest.passed test_linearPDEsOnFinley.passed test_generators.passed test_visualization_interface.passed test_utilOnFinley.passed"

echo "===> cd $1"
cd $1
if [ $? != 0 ]
then
  echo "couldnt cd $1"
  echo "couldnt cd $1" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  exit 1
fi

PWD=`pwd`
echo "===> working in: $PWD"

# Setup the environment
. ${MODULESHOME}/init/sh
module load intel_cc.9.0.026
export MODULEPATH=${MODULEPATH}:/data/raid2/toolspp4/modulefiles/gcc-3.3.6
module load python/2.4.1
module load boost/1.33.0/python-2.4.1
module load numarray/1.3.3

# set openmp settings
export OMP_NUM_THREADS=4

echo "===> svn update"
svn update
if [ $? != 0 ]
then
  echo "svn update failed"
  echo "svn update failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  exit 2
fi

echo "===> scons building esys"
scons
if [ $? != 0 ]
then
  echo "scons build failed"
  echo "scons build failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  exit 3
fi

echo "===> building unit_tests"
scons build_all_tests
if [ $? != 0 ]
then
  echo "build_tests failed"
  echo "build_tests failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  exit 3
fi

FAIL=0

echo "===> running unit_tests"
scons run_all_tests
if [ $? != 0 ]
then
  echo "run_all_tests failed"
  echo "run_all_tests failed" | mail -s "esys autotest-scons results" $MAIL_RECIPIENTS
  exit 4
fi
