--- !ditz.rubyforge.org,2008-03-06/project 
name: p4est
version: "1.1"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: p4est
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :released
  release_time: 2010-07-07 16:06:55.540168 Z
  log_events: 
  - - 2008-10-16 17:36:04.252955 Z
    - Carsten Burstedde <carsten@ices.utexas.edu>
    - created
    - Release 0.3 should have full 2D and 3D functionality.
  - - 2010-07-07 16:06:55.540184 Z
    - Carsten Burstedde <carsten@ices.utexas.edu>
    - released
    - This has been done on 2010-01-22.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.4"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-10-16 19:05:39.234410 Z
    - Carsten Burstedde <carsten@ices.utexas.edu>
    - created
    - Implement and test all code necessary for inclusion in Deal.II.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.5"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-10-30 17:02:26.232138 Z
    - Carsten Burstedde <carsten@ices.utexas.edu>
    - created
    - This release contains extra features added after public release.
