Import('*')

local_env=env.Copy()

src_dir = local_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
python_src = [x for x in filenames if os.path.splitext(x)[1] in ['.py']]

pyc = local_env.PyCompile(python_src)

local_env.Depends(pyc, dep_lib)

tmp1 = local_env.Install(pyinstall+'/pyvisi', pyc)
env.Alias('target_install_pyvisi_py', [tmp1])

local_env.SConscript(dirs = ['#/pyvisi/test/python'], build_dir='#/build/$PLATFORM/pyvisi/test/python', duplicate=0)


