"""
This file contains all of the classes for the various plotting objects.

@var __author__: name of author
@var __license__: licence agreement
@var __copyright__: copyrights
@var __url__: url entry point on documentation
@var __version__: version
@var __date__: date of the version
"""

__copyright__="""  Copyright (c) 2006 by ACcESS MNRF
                    http://www.access.edu.au
                Primary Business: Queensland, Australia"""
__license__="""Licensed under the Open Software License version 3.0
             http://www.opensource.org/licenses/osl-3.0.php"""
__author__="Paul Cochrane"
__url__="http://www.iservo.edu.au/esys"
__version__="$Revision$"
__date__="$Date$"


from common import debugMsg

from plot import Plot

class LinePlot(Plot):
    """
    Line Plots
    """

    def __init__(self, scene):
        """
        Initialisation of LinePlot class

        @param arg: The scene with which to associate the plot
        @type arg: Scene object
        """
        debugMsg("Called LinePlot.__init__()")
        Plot.__init__(self, scene)  # initialisation of base class
    
        self.renderer = scene.renderer

        self.title = None
        self.xlabel = None
        self.ylabel = None
        self.zlabel = None

        self.linestyle = None   # pyvisi-defined linestyle
        self._linestyle = None  # renderer-specific linestyle

        # is the LinePlot data offset (vertically) from each other?
        self.offset = False

        # now add the object to the scene
        scene.add(self)

    def setData(self, *dataList, **options):
        """
        Sets the data to the given plot object.

        @param dataList: list of data objects to plot
        @type dataList: tuple

        @param options: keyword options
        @type options: dict
        """
        debugMsg("Called setData() in LinePlot()")
        
        self.renderer.runString("# LinePlot.setData()")

        # grab the options if any
        if options.has_key('offset'):
            self.offset = options['offset']
        else:
            self.offset = False

        # do some sanity checking on the data
        for i in range(len(dataList)):
            if len(dataList[0]) != len(dataList[i]):
                raise ValueError, "Input vectors must all be the same length"

        # this is a really dodgy way to get the data into the renderer
        # I really have to find a better, more elegant way to do this
        
        # if have more than one array to plot, the first one is the x data
        if len(dataList) > 1:
            xData = dataList[0]
            ## pass around the x data
            self.renderer.renderDict['_x'] = copy.deepcopy(xData)
            # don't need the first element of the dataList, so get rid of it
            dataList = dataList[1:]
        # if only have one array input, then autogenerate xData
        elif len(dataList) == 1:
            xData = range(1, len(dataList[0])+1)
            if len(xData) != len(dataList[0]):
                errorString = "Autogenerated xData array length not "
                errorString += "equal to input array length"
                raise ValueError, errorString
                        
            ## pass around the x data
            self.renderer.renderDict['_x'] = copy.deepcopy(xData)

        # range over the data, printing what the expansion of the array is
        # and regenerate the data within the eval
        for i in range(len(dataList)):
            yDataVar = "_y%d" % i
            data = dataList[i]
            # check that the data here is a 1-D array
            if len(data.shape) != 1:
                raise ValueError, "Can only handle 1D arrays at present"
            
            self.renderer.renderDict[yDataVar] = copy.deepcopy(data)

        # if offset is true, then shift the data up accordingly
        if self.offset:
            # concatenate the data
            evalString = "_yAll = concatenate(["
            for i in range(len(dataList)-1):
                evalString += "_y%d," % i
            evalString += "_y%d])" % int(len(dataList)-1)
            self.renderer.runString(evalString)

            # find its min and max
            self.renderer.runString("_yMin = min(_yAll)")
            self.renderer.runString("_yMax = max(_yAll)")

            # keep the data apart a bit with a constant
            self.renderer.runString("_const = 0.1*(_yMax - _yMin)")

            # shift the data up
            self.renderer.runString("_shift = _yMax - _yMin + _const")

            for i in range(len(dataList)):
                evalString = "_y%d = _y%d + %d*_shift" % (i, i, i)
                self.renderer.runString(evalString)

        # determine the min and max of the x and y data
        evalString = "_xMin = min(_x)\n"
        evalString += "_xMax = max(_x)"
        self.renderer.runString(evalString)

        if self.offset:
            ### don't need to recalculate _yMin and _yMax
            # but do need to take into account the shift
            evalString = "_yMax = _yMax + %d*_shift" % len(dataList)
            self.renderer.runString(evalString)
            pass
        else:
            ### but if not offset, do have to

            # concatenate the data
            evalString = "_yAll = concatenate(["
            for i in range(len(dataList)-1):
                evalString += "_y%d," % i
            evalString += "_y%d])" % int(len(dataList)-1)
            self.renderer.runString(evalString)

            # calculate the min and max
            evalString = "_yMin = min(_yAll)\n"
            evalString += "_yMax = max(_yAll)"
            self.renderer.runString(evalString)

        # return the number of data objects to plot
        self.renderer.numDataObjects = len(dataList)

        return

    def render(self):
        """
        Does LinePlot object specific rendering stuff
        """
        debugMsg("Called LinePlot.render()")

        self.renderer.runString("# LinePlot.render()")

        # initialise plplot 
        self.renderer.runString("plplot.plinit()")

        # set up the viewport for plotting
        evalString = "plplot.plenv(_xMin,_xMax,_yMin,_yMax, 0, 1)"
        self.renderer.runString(evalString)

        # set up the evalString to use for plotting
        for i in range(self.renderer.numDataObjects):
            evalString = "plplot.plline(_x, _y%d)" % i
            self.renderer.runString(evalString)

        # if a title is not set, set it to a null string
        # (this will help keep plplot happy)
        if self.title is None:
            self.title = ""

        # if an xlabel is not set, set it to a null string
        if self.xlabel is None:
            self.xlabel = ""

        # if a ylabel is not set, set it to a null string
        if self.ylabel is None:
            self.ylabel = ""

        # put the labels (if any) on the graph.
        evalString = "plplot.pllab(\"%s\", \"%s\", \"%s\")" % \
                (self.xlabel, self.ylabel, self.title)
        self.renderer.runString(evalString)

        # finish stuff off
        self.renderer.runString("plplot.plend()")

        return

    def setLineStyle(self, linestyle):
        """
        Sets the linestyle of the LinePlot

        Linestyles may be either a word in the Gnuplot style, or a symbol 
        shortcut in the Matlab style.  Some of the options do not have a
        Matlab equivalent but do have a Gnuplot equivalent, or vice versa.

        What this method does, is take the linestyles possible as defined by
        PyVisi, and then does some conversion as best it can to get the
        relevant output from (in this case) plplot.
        
        Possible linestyles are:
            1. lines ('-')
            2. points ('o')
            3. linespoints ('-o')
            4. dots ('.')
            5. dotted (':')
            6. dashes ('--')
            7. dotdashes ('-.')

        @param linestyle: the style to use for the lines
        @type linestyle: string
        """
        debugMsg("Called LinePlot.setLineStyle()")

        # now implement the gnuplot-specific way to do this
        if linestyle == 'lines' or linestyle == '-':
            self._linestyle = 'lines'
        elif linestyle == 'points' or linestyle == 'o':
            self._linestyle = 'points'
        elif linestyle == 'linespoints' or linestyle == '-o':
            self._linestyle = 'linespoints'
        elif linestyle == 'dots' or linestyle == '.':
            self._linestyle = 'dots'
        elif linestyle == 'dotted' or linestyle == ':':
            print "linestyle = %s" % linestyle
            raise NotImplementedError, \
                    "Sorry, haven't implemented this style yet."
        elif linestyle == 'dashes' or linestyle == '--':
            print "linestyle = %s" % linestyle
            raise NotImplementedError, \
                    "Sorry, haven't implemented this style yet."
        elif linestyle == 'dotdashes' or linestyle == '-.':
            print "linestyle = %s" % linestyle
            raise NotImplementedError, \
                    "Sorry, haven't implemented this style yet."
        else:
            raise ValueError, "Unknown linestyle!  I got \'%s\'" % linestyle

        return

    def getLineStyle(self):
        """
        Gets the current linestyle of the LinePlot

        @return: the linestyle as a string
        """
        debugMsg("Called LinePlot.getLineStyle()")

        return self.linestyle


# vim: expandtab shiftwidth=4:
