
########################################################
#
# Copyright (c) 2003-2011 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################

Import('*')
local_env = env.Clone()

# get the source file names
sources = Glob('*.py')

# compile
pyc = local_env.PyCompile(sources)

# install
py_inst = local_env.Install(local_env['pyinstall']+'/pyvisi', pyc)
env.Alias('install_pyvisi_py', py_inst)

# configure tests
local_env.SConscript(dirs = ['#/pyvisi/test/python'], variant_dir='$BUILD_DIR/$PLATFORM/pyvisi/test/python', duplicate=0)

