# Package config file for external package/TPL 'Boost'
#
# Generated by CMake, do not edit!

# Guard against multiple inclusion
if (TARGET Boost::all_libs)
  return()
endif()

add_library(Boost::all_libs INTERFACE IMPORTED)
target_include_directories(Boost::all_libs SYSTEM
  INTERFACE "/usr/include"
  )


# Standard TriBITS-compliant external package variables
set(Boost_IS_TRIBITS_COMPLIANT TRUE)
set(Boost_TRIBITS_COMPLIANT_PACKAGE_CONFIG_FILE "${CMAKE_CURRENT_LIST_FILE}")
set(Boost_TRIBITS_COMPLIANT_PACKAGE_CONFIG_FILE_DIR "${CMAKE_CURRENT_LIST_DIR}")
