# Package config file for external package/TPL 'Boost'
#
# Generated by CMake, do not edit!

if (TRIBITS_FINDING_RAW_Boost_PACKAGE_FIRST)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()

# Currently there is no version information
set(PACKAGE_VERSION UNKNOWN)
set(PACKAGE_VERSION_EXACT FALSE)
