
#define HAVE_MUELU_EXPLICIT_INSTANTIATION
/* #undef HAVE_MUELU_EXPERIMENTAL */

/* #undef HAVE_MUELU_INST_FLOAT_INT_INT */
#define HAVE_MUELU_INST_DOUBLE_INT_INT
/* #undef HAVE_MUELU_INST_DOUBLE_INT_LONGINT */
/* #undef HAVE_MUELU_INST_DOUBLE_INT_LONGLONGINT */
#define HAVE_MUELU_INST_COMPLEX_INT_INT
/* #undef HAVE_MUELU_INST_PCE_INT_INT */
