
########################################################
#
# Copyright (c) 2003-2010 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################

Import('*')
local_env = env.Clone()

# get the test source file names
sources = Glob('*.cpp')+Glob('*.c')
testname='weipa_UnitTest'

# build the executable
local_env.Append(LIBS=['weipa', 'escript', 'dudley', 'finley', 'CppUnitTest'])
if local_env['silo']:
  local_env.Append(CPPDEFINES = ['USE_SILO'])
  local_env.AppendUnique(LIBS = [env['silo_libs']])
program = local_env.Program(testname, sources)

# run the tests - but only if test_targets are stale
local_env.RunUnitTest(testname)

# add unit test to target alias
Alias('build_tests', program)
Alias("run_tests", testname+'.passed')

# configure python unit tests
local_env.SConscript(dirs = ['#/weipa/test/python'], variant_dir='python', duplicate=0)

# add a group of tests
from grouptest import *
tgroup=GroupTest("$BINRUNNER ", (), "", "$BUILD_DIR/weipa/test", ('./'+testname,))
TestGroups.append(tgroup)

