
# Python 2.3 Static - include files plus library to link with

PKG_CC_INC_DIRS  += /raid2/tools/python-2.3.4/include/python2.3
PKG_CPP_INC_DIRS += /raid2/tools/python-2.3.4/include/python2.3

PKG_LD_LIB_DIRS += /raid2/tools/python-2.3.4/lib

PKG_LD_LIBS += python2.3 dl util

