# top-level Scons configuration file for all bruce unit tests

# this is not fully implemented - just a placeholder script for now

import os

#
# ensure correct versions of python and scons

EnsurePythonVersion(2,3)
EnsureSConsVersion(0,96)

#
# retreive command-line arguments if any
# these are passed through to SConscripts

if ARGUMENTS.get('usegcc',0):
  usegcc = 1
else:
  usegcc = 0
Export(["usegcc"])

#
# set and export esysroot

esysroot = Dir('#..')
Export(["esysroot"])

#
# call appropriate SConscripts

target_scripts = ['Bruce/SConstruct',
                  'BruceFactory/SConstruct']

SConscript(target_scripts, duplicate=0)
