# Scons configuration file for DataVariable unit tests

#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./../../../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

cxx_flags=cxx_flags_debug

print "Build configuration for module: DataVariable unit tests"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# do the actual build

datavariable_test_path = str(esysroot) + '/escript/test/DataVariable'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/src'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

escript_lib = str(esys_lib_path) + '/libescriptcpp.so'

install_dir = str(esysroot) + '/escript/test'

cpp_path = [datavariable_test_path,
            escript_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'dl',
        'util']

libs.extend(sys_libs)

sources = ['DataVariableTestCase.cpp',
           'DataVariableTest.cpp']

target = 'DataVariableTest.exe'

import os
datavariable_env = Environment(ENV = os.environ)

datavariable_env.Replace(CXX = cxx)
datavariable_env.Replace(CXXFLAGS = cxx_flags)
datavariable_env.Replace(CPPPATH = cpp_path)
datavariable_env.Replace(LIBPATH = lib_path)
datavariable_env.Replace(LIBS = libs)

datavariable_test_exe = datavariable_env.Program(target, sources)

Depends(datavariable_test_exe, escript_lib)

Alias("build_tests", datavariable_env.Install(install_dir, datavariable_test_exe))

import scons_extensions
runUnitTest_builder = Builder(action = scons_extensions.runUnitTest, suffix = '.passed', single_source=True)
datavariable_env.Append(BUILDERS = {'RunUnitTest' : runUnitTest_builder});

Alias("run_tests", datavariable_env.RunUnitTest(target))
