
##############################################################################
#
# Copyright (c) 2003-2014 by University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

import os
Import('*')

local_env = env.Clone()

# 
#  files defining test runs (passing in a release)
# 
testruns = ['run_utilOnRipley.py']
testruns += ['run_escriptOnRipley.py']
testruns += ['run_simplesolve.py']
testruns += ['run_linearPDEsOnRipley1.py']
testruns += ['run_nlpde2dOnRipley.py']
testruns += ['run_nlpde3dOnRipley.py']
testruns += ['run_customAssemblers.py']

#Add Unit Test to target alias
local_env.PrependENVPath('PYTHONPATH', Dir('.').abspath)
local_env.PrependENVPath('PYTHONPATH', env.Dir('$BUILD_DIR/$PLATFORM/escriptcore/test/python').abspath)
local_env['ENV']['RIPLEY_TEST_DATA']=Dir('.').srcnode().abspath
local_env['ENV']['RIPLEY_WORKDIR']=Dir('.').abspath
# needed for a test from the util base class in escript
local_env['ENV']['ESCRIPT_WORKDIR']=Dir('.').abspath
env.Alias('local_py_tests',[os.path.splitext(x)[0]+'.passed' for x in testruns])
env.Alias('py_tests', [os.path.splitext(x)[0]+'.passed' for x in testruns])

# run all tests
program = local_env.RunPyUnitTest(testruns)
Depends(program, py_wrapper_lib)
Depends(program, 'build_py_tests')

# Add a group of tests
from grouptest import *
tgroup=GroupTest("$PYTHONRUNNER ",(("RIPLEY_TEST_DATA","$BATCH_ROOT/ripley/test/python"),('RIPLEY_WORKDIR','$BUILD_DIR/ripley/test/python')),"$BATCH_ROOT/escriptcore/test/python:$BATCH_ROOT/ripley/test/python","$BATCH_ROOT/ripley/test/python",testruns)
tgroup.makeDir("$BUILD_DIR/ripley/test/python")
TestGroups.append(tgroup)

