# $Id$

# CPPUnitTest

PKG_CC_INC_DIRS += $(ESYS_ROOT)/tools/CppUnitTest/inc
PKG_CPP_INC_DIRS += $(ESYS_ROOT)/tools/CppUnitTest/inc
PKG_LD_LIB_DIRS += $(ESYS_ROOT)/tools/CppUnitTest/lib
PKG_LD_LIBS += CppUnitTest

# $Log$
# Revision 1.1  2004/10/26 06:53:58  jgs
# Initial revision
#
# Revision 1.1  2004/08/02 11:23:09  gross
# some progress toward slicing
#
#
