# $Id$

# lapack 3.0

PKG_CC_INC_DIRS += ${NULL}	# standard directory
PKG_CPP_INC_DIRS += ${NULL}	# standard directory
PKG_LD_LIB_DIRS += ${NULL}	# standard directory
PKG_LD_LIBS += ${NULL}

# $Log$
# Revision 1.1  2004/10/26 06:53:58  jgs
# Initial revision
#
# Revision 1.1  2004/08/02 11:23:10  gross
# some progress toward slicing
#
#
