# $Id$

# mmio

PKG_CC_INC_DIRS  += $(ESYS_ROOT)/tools/mmio/inc
PKG_CPP_INC_DIRS += $(ESYS_ROOT)/tools/mmio/inc

PKG_LD_LIB_DIRS += $(ESYS_ROOT)/tools/mmio/lib

PKG_LD_LIBS += mmio

# $Log$
# Revision 1.1  2004/10/26 06:53:58  jgs
# Initial revision
#
# Revision 1.1.2.2  2004/09/28 07:03:14  jgs
# *** empty log message ***
#
# Revision 1.1.2.1  2004/09/27 06:37:54  jgs
# restructured make files
#
# Revision 1.1  2004/07/02 04:21:54  gross
# Finley C code has been included
#
