
########################################################
#
# Copyright (c) 2003-2008 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################


import os
Import('*')

local_env = clone_env(env_mpi)

sources = ["ScriptMPI.cpp"]
sources_redirect = ["ScriptMPIredirect.cpp"]

local_env.Append(LIBS = ["paso"] + env['sys_libs'])

include_path = Dir('pythonMPI', local_env['incinstall'])

prog = local_env.Program('pythonMPI', sources)
prog_redirect = local_env.Program('pythonMPIredirect', sources_redirect)

env.Alias('target_pythonMPI_exe', [ prog, sources_redirect ] )

tmp1 = local_env.Install(local_env['libinstall'], prog)
tmp2 = local_env.Install(local_env['libinstall'], prog_redirect)
env.Alias('target_install_pythonMPI_exe', [ tmp1, tmp2 ] )

