
########################################################
#
# Copyright (c) 2003-2009 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################


import os
Import('*')
#
# these are the release examples in example sub directory:
#
example_files_allow_mpi = [
 'geotutorial/steadystate_variablek.py', 
 'geotutorial/steadystate.py', 
 'geotutorial/forward_euler.py', 
 'geotutorial/myfirstscript.py', 
 'geotutorial/backward_euler.py', 
 'usersguide/lit_driven_cavity.py',
 'usersguide/mount.py',
 'usersguide/wave.py',
 'usersguide/heatedblock.py',
 'usersguide/helmholtz.py',
 'usersguide/fluid.py',
 'usersguide/poisson.py',
 'usersguide/diffusion.py',
 'usersguide/poisson_matplotlib.py'
]

example_files_no_mpi = [
'usersguide/poisson_matplotlib.py'
'usersguide/poisson.py'
]

example_files= example_files_allow_mpi + example_files_no_mpi


ex2=[ os.path.join("examples",str(x)) for x in example_files] 

#==========================================================================================

local_env = clone_env(env)
src_dir = local_env.Dir('.').srcnode().abspath
release_dir=local_env.Dir('#/release/doc/').srcnode().abspath

tmp1 = env.Command("#/release/doc/escript_examples.zip", None, 
"zip "+os.path.join(release_dir,"escript_examples.zip ") +" ".join(ex2),chdir=src_dir)
env.Alias('examples_zipfile', tmp1)


#Need to use explicit tar rather than the tar builder due to problems getting it not to put
#unwanted path components in the tar file
#--transform on tar is not supported on savanna
tmp2 = env.Command("#/release/doc/escript_examples.tar.gz", None, "tar -czf "+os.path.join(release_dir,"escript_examples.tar.gz ")+"  ".join(ex2), chdir=src_dir)
env.Alias('examples_tarfile',tmp2)

#env=Environment(TARFLAGS = "-c -z",chdir=src_dir)
#if 'Tar' in dir(env): env.Tar('#/release/doc/escript_examples.tar.gz', example_files,chdir=src_dir)
#env.Alias('examples_tarfile', '#release/doc/escript_examples.tar.gz')

local_env.SConscript(dirs = ['#/doc/user'], build_dir='#/build/$PLATFORM/doc/user', duplicate=1)
local_env.SConscript(dirs = ['#/doc/epydoc'], build_dir='#/build/$PLATFORM/doc/epydoc', duplicate=1)
local_env.SConscript(dirs = ['#/doc/doxygen'], build_dir='#/build/$PLATFORM/doc/doxygen', duplicate=1)
local_env.SConscript(dirs = ['#/doc/install'], build_dir='#/build/$PLATFORM/doc/install', duplicate=1)
local_env.SConscript(dirs = ['#/doc/examples'], build_dir='#/build/$PLATFORM/doc/examples', duplicate=1, exports=[ 'example_files_allow_mpi' , 'example_files_no_mpi' ])


