##############################################################################
#
# Copyright (c) 2003-2016 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

import os
Import('*')

local_env = env.Clone()

sources = """
  TrilinosMatrixAdapter.cpp
""".split()

headers = """
  TrilinosAdapterException.h
  TrilinosMatrixAdapter.h
  types.h
""".split()

local_env.Prepend(LIBS = ['escript'] + env['trilinos_libs'])

module_name = 'trilinoswrap'

# specify to build shared object

lib = local_env.SharedLibrary(module_name, sources)
env.Alias('build_trilinoswrap_lib', lib)

include_path = Dir('trilinoswrap', local_env['incinstall'])
hdr_inst = local_env.Install(include_path, headers)
env.Alias('install_trilinoswrap_headers', hdr_inst)

lib_inst = local_env.Install(local_env['libinstall'], lib)
env.Alias('install_trilinoswrap_lib', lib_inst)

# configure unit tests
#local_env.SConscript(dirs = ['#/trilinoswrap/test'], variant_dir='test', duplicate=0)

