# $Id$

# CPPUnitTest

PKG_CC_INC_DIRS += /usr/include/boost/
PKG_CPP_INC_DIRS += /usr/include/boost/

# $Log$
# Revision 1.1  2004/10/26 06:53:58  jgs
# Initial revision
#
# Revision 1.1  2004/08/02 11:23:08  gross
# some progress toward slicing
#
#
