# $Id$

PKG_CC_INC_DIRS += $(ESYS_ROOT)/esysUtils/inc
PKG_CPP_INC_DIRS += $(ESYS_ROOT)/esysUtils/inc
PKG_LD_LIB_DIRS += $(ESYS_ROOT)/esysUtils/lib
PKG_LD_LIBS += esysUtils

# $Log$
# Revision 1.1  2004/10/26 06:53:58  jgs
# Initial revision
#
# Revision 1.1  2004/08/02 11:23:10  gross
# some progress toward slicing
#
#
