# Scons configuration file for modellib

import os
import sys

#
# ensure correct versions of python and scons

EnsurePythonVersion(2,3)
EnsureSConsVersion(0,96)

#
# set appropriate defaults for configuration variables

esysroot = Dir('#..')
pyinstall = None

#
# import configuration variables passed in from
# calling SConscript (if any)

Import('*')

#
# retreive command-line arguments if any

if ARGUMENTS.get('pyinstall',0):
  pyinstall = ARGUMENTS.get('pyinstall',0)
Export(["pyinstall"])

#
# determine platform

env = Environment(ENV = os.environ)
platform = env['PLATFORM']

#
# determine hostname

hostname = os.environ['HOSTNAME']

#
# export esysroot

Export(["esysroot"])

#
# set and export python directory

pydir = Dir(str(esysroot) + '/modellib/lib/py_src')
Export(["pydir"])
pydir2 = Dir(str(esysroot) + '/esys/modellib')
Export(["pydir2"])

#
# print out build configuration for this module

print "Build configuration for module: modellib"
print "        platform: ", platform
print "        hostname: ", hostname
print "       pyinstall: ", pyinstall

#
# call the SConscript to do the actual build

SConscript(dirs=['py_src'], build_dir='obj/py_src', duplicate=0)
