
##############################################################################
#
# Copyright (c) 2003-2026 by the esys.escript Group
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
# Development from 2019 by School of Earth and Environmental Sciences
#
##############################################################################

Import('*')
local_env = env.Clone()

# get the test source file names
sources = Glob('*.py')

# compile
pyc = local_env.PyCompile(sources)
local_env.Depends(pyc, 'build_weipa')

# install
py_inst = local_env.Install(Dir('weipa', local_env['pyinstall']), pyc)
env.Alias('install_weipa', py_inst)

