# top-level Scons configuration file for all finley unit tests
#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       
#                                                          
#
# set appropriate configuration variable defaults
esysroot=str(Dir('./../../').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

#
# call appropriate SConscripts

target_scripts = ['MeshAdapter/SConscript']

SConscript(target_scripts, duplicate=0)
