Import('*')

local_env=env.Copy()

src_dir = local_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
python_src = [x for x in filenames if os.path.splitext(x)[1] in ['.py']]

local_env.RunPyUnitTest(python_src)

#Add Unit Test to target alias
test_targets = [os.path.splitext(x)[0]+'.passed' for x in python_src]

env.Alias('py_test',test_targets)
env.Alias('bruce_test', test_targets)