#!/bin/env bash
# $Id$
# simple script to run all finley unit tests

MODULES="MeshAdapter SystemMatrixAdapter MMtest"

for module in $MODULES ; do \
	(echo Testing: $module; cd $module; ./unit_test) \
done
