# Scons configuration file for BruceFactory unit tests

#
# set appropriate configuration variable defaults

esysroot=str(Dir('./../../../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

cxx_flags=cxx_flags_debug

print "Build configuration for module: BruceFactory unit tests"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# do the actual build

bruce_path = str(esysroot) + '/bruce/inc'
brucefactory_test_path = str(esysroot) + '/bruce/test/BruceFactory'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

bruce_lib = str(esys_lib_path) + '/libbrucecpp.so'

install_dir = str(esysroot) + '/bruce/test'

cpp_path = [bruce_path,
            brucefactory_test_path,
            escript_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['brucecpp',
        'escriptcpp',
        'esysUtils',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'dl',
        'util']

libs.extend(sys_libs)

sources = ['BruceFactoryTestCase.cpp',
           'BruceFactoryTest.cpp']

target = 'BruceFactoryTest.exe'

import os
brucefactory_env = Environment(ENV = os.environ)

brucefactory_env.Replace(CXX = cxx)
brucefactory_env.Replace(CXXFLAGS = cxx_flags)
brucefactory_env.Replace(CPPPATH = cpp_path)
brucefactory_env.Replace(LIBPATH = lib_path)
brucefactory_env.Replace(LIBS = libs)

brucefactory_test_exe = brucefactory_env.Program(target, sources)

Depends(brucefactory_test_exe, bruce_lib)

Alias("build_tests", brucefactory_env.Install(install_dir, brucefactory_test_exe))

import scons_extensions
runUnitTest_builder = Builder(action = scons_extensions.runUnitTest, suffix = '.passed', single_source=True)
brucefactory_env.Append(BUILDERS = {'RunUnitTest' : runUnitTest_builder});

Alias("run_tests", brucefactory_env.RunUnitTest(target))
