#!/usr/bin/env python
# 
# run all of the examples
#
# $Id: runall,v 1.11 2005/11/30 04:27:47 paultcochrane Exp $

# process arguments if any
import sys
numArgs = len(sys.argv)
if numArgs == 1:
    renderer = "vtk"
else:
    renderer = sys.argv[1]

# the list of files to process
Files = (
    "arrowPlot.py",
    "arrowPlot2D.py",
    "arrowPlot3D.py",
    "ballPlot.py",
    "contourPlot.py",
    #"contourPlotMovie.py",
    "ellipsoidPlot.py",
    "isosurfacePlot.py",
    "meshPlot.py",
    "multiCurveLinePlot.py",
    "offsetLinePlot.py",
    "offsetPlot.py",
    "randomLinePlot.py",
    "seismicOffsetPlot1.py",
    "seismicOffsetPlot2.py",
    "seismicOffsetPlot3.py",
    "simpleLinePlot.py",
    #"simpleLinePlotMovie.py",
    "singleArrayLinePlot.py",
    "surfaceAndContourPlot.py",
    "surfacePlot.py",
    "scatterPlot.py",
    "scatterPlot3D.py",
)

print "Running all examples"

# run the examples
import os
err = open("runall.errs", "w")
for file in Files:
    print ""
    print 70*"#"
    print "Running %s" % file
    print 70*"#"
    print ""
    result = os.system("python %s %s" % (file,renderer) )
    if result != 0:
        print "Error running example script: %s" % file
        err.write("Error running example script: %s\n" % file)

err.close()

# vim: expandtab shiftwidth=4:
