# Scons configuration file for doxygen docs

import os

#
# set appropriate defaults for configuration variables

esysroot=str(Dir('../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

#
# construct the script to run doxygen

rundoxygen_script = open(str(File(esysroot+"/doc/doxygen/rundoxygen")), 'w')
rundoxygen_script.write(str("#!/bin/bash\n"))
rundoxygen_script.write(str(doxygen_path+"/doxygen doxygen/doxygen_esys > "+esysroot+"/doc/doxygen_msgs.txt 2>&1\n"))
rundoxygen_script.close()

os.chmod(str(File(esysroot+"/doc/doxygen/rundoxygen")), 0700)

#
# do the actual build

import scons_extensions

source = 'rundoxygen'

doxygen_env = Environment(ENV = os.environ)

runDoxygen_builder = Builder(action = scons_extensions.build_doxygen, suffix = ".run", single_source = True)
doxygen_env.Append(BUILDERS = {'RunDoxygen' : runDoxygen_builder})

Default(doxygen_env.RunDoxygen(source))
