Import('*')

local_env=env.Copy()

src_dir = local_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
sources = [x for x in filenames if os.path.splitext(x)[1] in ['.cpp', '.c']]
headers = [x for x in filenames if os.path.splitext(x)[1] in ['.h']]
# Filter out sources that should not be in the list automatically

lib_name = 'brucecpp'

local_env.Append(LIBS = [boost_lib, 'esysUtils', 'escriptcpp'])

lib = local_env.SharedLibrary(lib_name, sources)

include_path = Dir(lib_name, incinstall)

local_env.Install(include_path, headers )
local_env.Install(libinstall, lib)

# FIXME: OLD STUFF
#libs.extend(sys_libs)

#Depends(bruce_lib, esysUtils_lib)
#Depends(bruce_lib, escript_lib)
