# Scons configuration file for epydoc docs

import os

#
# set appropriate defaults for configuration variables

esysroot=str(Dir('../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

import scons_extensions

#
# do the actual build

source = 'runepydoc'

epydoc_env = Environment(ENV = os.environ)

runEpydoc_builder = Builder(action = scons_extensions.build_epydoc, suffix = ".run")
epydoc_env.Append(BUILDERS = {'RunEpydoc' : runEpydoc_builder})

Default(epydoc_env.RunEpydoc(source))
