#
# $Id$
#
#######################################################
#
#           Copyright 2003-2007 by ACceSS MNRF
#       Copyright 2007 by University of Queensland
#
#                http://esscc.uq.edu.au
#        Primary Business: Queensland, Australia
#  Licensed under the Open Software License version 3.0
#     http://www.opensource.org/licenses/osl-3.0.php
#
#######################################################
#

import os
Import('*')

try:
  local_env = env_mpi.Clone()	# scons-98.03
except AttributeError:
  local_env = env_mpi.Copy()	# scons-96.92

sources = ["ScriptMPI.cpp"]

local_env.Append(LIBS = ["paso"] + env['sys_libs'])

include_path = Dir('pythonMPI', local_env['incinstall'])

prog = local_env.Program('pythonMPI', sources)
env.Alias('target_pythonMPI_exe', prog)

tmp1 = local_env.Install(local_env['libinstall'], prog)
env.Alias('target_install_pythonMPI_exe', tmp1)

