import os
Import('*')

local_env=env_mpi.Copy()

sources = ["ScriptMPI.cpp"]
headers = []

if local_env['useMPI']:
    local_env.Append(LIBS = local_env['mpi_libs'])

local_env.Append(LIBS = ["paso"] + [local_env['python_lib']] + sys_libs)
lib_name = 'pythonMPI'
lib = local_env.Program(lib_name, sources)
include_path = Dir(lib_name, incinstall)

local_env.Install(include_path, headers )
local_env.Install(libinstall, lib)

