##############################################################################
#
# Copyright (c) 2003-2026 by the esys.escript Group
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
#
##############################################################################

Import('*')
local_env = env.Clone()

# get the source file names
sources = Glob('*.py')

# compile
pyc = local_env.PyCompile(sources)

# install
py_inst = local_env.Install(Dir('oxley', local_env['pyinstall']), pyc)
env.Alias('install_oxley', py_inst)

