Import('*')

local_env=env.Copy()

src_dir = local_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
python_src = [x for x in filenames if os.path.splitext(x)[1] in ['.py']]

pyc = local_env.PyCompile(python_src)

local_env.Depends(pyc, dep_lib)
local_env.Install(pyinstall+'/pyvisi', pyc)

# get all the python files in the release tar file
release_py = [ env.File("SConscript"), ] + [ env.File(x) for x in python_src ]
env.Zip(src_zipfile, release_py)
try:
   env.Tar(src_tarfile, release_py)
except AttributeError:
   pass
# Call the unit tests SConscript
local_env.SConscript(dirs = ['#/pyvisi/test/python'], build_dir='#/build/$PLATFORM/pyvisi/test/python', duplicate=0)


