# Scons configuration file for DataArray unit tests

#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./../../../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

cxx_flags=cxx_flags_debug 

print "Build configuration for module: DataArray unit tests"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# do the actual build

dataarray_test_path = str(esysroot) + '/escript/test/DataArray'
escript_path = str(esysroot) + '/escript/src'
esysUtils_path = str(esysroot) + '/esysUtils/src'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

escript_lib = str(esys_lib_path) + '/libescriptcpp.so'

install_dir = str(esysroot) + '/escript/test'

cpp_path = [dataarray_test_path,
            escript_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'dl',
        'util']

libs.extend(sys_libs)

sources = ['DataArrayTestCase.cpp',
           'DataArrayTest.cpp']

target = 'DataArrayTest.exe'

import os
dataarray_env = Environment(ENV = os.environ)

dataarray_env.Replace(CXX = cxx)
dataarray_env.Replace(CXXFLAGS = cxx_flags)
dataarray_env.Replace(CPPPATH = cpp_path)
dataarray_env.Replace(LIBPATH = lib_path)
dataarray_env.Replace(LIBS = libs)

dataarray_test_exe = dataarray_env.Program(target, sources)

Depends(dataarray_test_exe, escript_lib)

Alias("build_tests", dataarray_env.Install(install_dir, dataarray_test_exe))

import scons_extensions
runUnitTest_builder = Builder(action = scons_extensions.runUnitTest, suffix = '.passed', single_source=True)
dataarray_env.Append(BUILDERS = {'RunUnitTest' : runUnitTest_builder});

Alias("run_tests", dataarray_env.RunUnitTest(target))
