Import('*')

import os
import string

cxx_flags = '-O0 -openmp -openmp_report0 -tpp2 -ansi -ansi_alias -no-gcc -fpic -w1'

finley_path = str(esysroot) + '/finley/inc'
paso_path = str(esysroot) + '/paso/inc'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'
python_path = '/raid2/tools/python-2.3.4/include/python2.3'
boost_path = '/raid2/tools/boost/include/boost-1_31'

cpp_path = [escript_path,
            esysUtils_path,
            finley_path,
            paso_path,
            python_path,
            boost_path]

lib = 'finleycpp'
sources = ['FinleyError.cpp',
           'MeshAdapter.cpp',
           'MeshAdapterFactory.cpp',
           'SystemMatrixAdapter.cpp',
           'finleycpp.cpp']

finleycpp_env = Environment(ENV = os.environ)

finleycpp_env.Replace(CXX = 'icc')
finleycpp_env.Replace(SHOBJSUFFIX = '.lo')
finleycpp_env.Replace(CXXFLAGS = cxx_flags)
finleycpp_env.Replace(CPPPATH = cpp_path)

finleycpp_lib = finleycpp_env.SharedLibrary(lib, sources)
finleycpp_env.Install(libdir, finleycpp_lib)
