debian/copyright				usr/share/doc/python-escript-doc
#debian/tmp3/posix/doc/cookbook/cookbook.pdf	usr/share/doc/python-escript-doc
#debian/stage3/release/doc/doxygen/html/* 		usr/share/doc/python-escript-doc/c++_html
#debian/tmp3/posix/doc/inversion/inversion.pdf	usr/share/doc/python-escript-doc/
#debian/stage3/release/doc/sphinx_api/* 		usr/share/doc/python-escript-doc/python_html
#debian/stage3/release/doc/sphinx_api/_static/basic.css	usr/share/doc/python-escript-doc/python_html/_static
#debian/tmp3/posix/doc/user/user.pdf		usr/share/doc/python-escript-doc
#Using this instead of python-escript-doc.docs because I want to rename the c++ doco from "doxygen"
#debian/tmp3/posix/doc/install/install.pdf	usr/share/doc/python-escript-doc
