# Scons configuration file for modellib

#
# set appropriate configuration variable defaults
esysroot=str(Dir('./..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

pydir = Dir(str(esysroot) + '/modellib/lib/py_src')
Export(["pydir"])
pydir2 = Dir(str(esysroot) + '/esys/modellib')
Export(["pydir2"])

#
# print out build configuration for this module

print "Build configuration for module: modellib"

#
# call the SConscript to do the actual build

SConscript(dirs=['py_src'], build_dir='obj/py_src', duplicate=0)
