
# Python 2.3 Static - include files plus library to link with

PKG_CC_INC_DIRS  += /opt/py24/include/python2.4
PKG_CPP_INC_DIRS += /opt/py24/include/python2.4

PKG_LD_LIB_DIRS += /opt/py24/lib

PKG_LD_LIBS += python2.4 dl util

