#!/bin/bash
# $Id$
# simple script to run all escript unit tests

MODULES="DataEmpty DataConstant DataTagged DataExpanded DataFactory DataArray DataArrayView DataBlocks2D DataVector Taipan DataVariable DataC DataAlgorithmAdapter FunctionSpace DataProf Data"

for module in $MODULES ; do
  echo Testing: $module
  cd $module
  scons
  scons -c
  if [ $? != 0 ]
  then
    echo Unit Testing FAILED for module: $module
    exit 1
  fi
  cd ..
done
exit 0
