#!/bin/bash
# $Id: unit_test 244 2005-11-29 00:27:10Z jgs $
# simple script to run all escript unit tests

MODULES="DataEmptyTest.exe DataConstantTest.exe DataTaggedTest.exe DataExpandedTest.exe DataFactoryTest.exe DataArrayTest.exe DataArrayViewTest.exe DataBlocks2DTest.exe DataVectorTest.exe TaipanTest.exe DataVariableTest.exe DataCTest.exe DataAlgorithmAdapterTest.exe FunctionSpaceTest.exe DataProfTest.exe DataTest.exe"

for module in $MODULES ; do
  echo Testing: $module
  ./$module
  if [ $? != 0 ]
  then
    echo Unit Testing FAILED for module: $module
    exit 1
  fi
done
exit 0
