#!/bin/bash
# $Id: unit_test 153 2005-10-25 01:51:20Z jgs $
# simple script to run all bruce unit tests

MODULES="BruceTest.exe BruceFactoryTest.exe"

for module in $MODULES ; do
  echo Testing: $module
  $module
  if [ $? != 0 ]
  then
    echo Unit Testing FAILED for module: $module
    exit 1
  fi
done
exit 0
