
########################################################
#
# Copyright (c) 2003-2010 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################


import os
Import('*')

local_env = env.Clone()

# 
#  files defining test runs (passing in a release)
# 
testruns = []
testruns += ['run_escriptOnDudley.py']
testruns += ['run_inputOutput.py']
testruns += ['run_linearPDEsOnDudley1.py']
testruns += ['run_linearPDEsOnDudley2.py']
testruns += ['run_models.py']
testruns += ['run_simplesolve.py']
testruns += ['run_utilOnDudley.py']
testruns += ['run_visualization_interface.py']
# 
#  files defining a few tests for a quick test
# 
scalable_tests = []
scalable_tests += ['run_inputOutput.py']
scalable_tests += ['run_simplesolve.py']
#
# files defining tests run locally (not as part of a release)
#
localtestruns = [x for x in Glob('*.py', strings=True) if not x.startswith('run_')]

#
# all test 
#
alltestruns = testruns + localtestruns
#
# test files are just compiled:
#
#sources = Glob('test_*.py')
#test_pyc = env.PyCompile(sources)
#env.Alias('build_py_tests', test_pyc)

#Add Unit Test to target alias
local_env.PrependENVPath('PYTHONPATH',str(env.Dir('#/build/$PLATFORM/dudley/test/python')))
local_env.PrependENVPath('PYTHONPATH',str(env.Dir('#/build/$PLATFORM/escript/test/python')))
local_env['ENV']['DUDLEY_TEST_DATA']=env.Dir('#/dudley/test/python').srcnode().abspath
local_env['ENV']['DUDLEY_WORKDIR']=env.Dir('#/build/$PLATFORM/dudley/test/python').srcnode().abspath
env.Alias('local_py_tests',[os.path.splitext(x)[0]+'.passed' for x in alltestruns])
env.Alias('py_tests', [os.path.splitext(x)[0]+'.passed' for x in testruns ])
env.Alias('scalable_tests', [os.path.splitext(x)[0]+'.passed' for x in scalable_tests ])

#
# run all tests:
#
# run all tests
program = local_env.RunPyUnitTest(alltestruns)
Depends(program, py_wrapper_lib)

# Add a group of tests
from grouptest import *
tgroup=GroupTest("$PYTHONRUNNER ",(("DUDLEY_TEST_DATA","$BATCH_ROOT/dudley/test/python"),('DUDLEY_WORKDIR','$BUILD_DIR/dudley/test/python')),"$BUILD_DIR/escript/test/python:$BUILD_DIR/dudley/test/python","$BATCH_ROOT/dudley/test/python",testruns)
tgroup.makeDir("$BUILD_DIR/dudley/test/python")
TestGroups.append(tgroup)

