# Scons configuration file for finley MeshAdapter unit tests

#
# set appropriate configuration variable defaults
esysroot=str(Dir('./../../../../').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

cxx_flags=cxx_flags_debug

print "Build configuration for module: MeshAdapter unit tests"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# do the actual build

meshadapter_test_path = str(esysroot) + '/finley/test/MeshAdapter'
escript_path = str(esysroot) + '/escript/src'
finley_path = str(esysroot) + '/finley/src'
finley_cppadapter_path = str(esysroot) + '/finley/src/CPPAdapter'
paso_path = str(esysroot) + '/paso/src'
mmio_path = str(esysroot) + '/tools/mmio/inc'
esysUtils_path = str(esysroot) + '/esysUtils/src'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
finley_lib_path = str(esysroot) + '/finley/lib'
mmio_lib_path = str(esysroot) + '/tools/mmio/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

finley_lib = str(esys_lib_path) + '/libfinleycpp.so'

install_dir = str(esysroot) + '/finley/test'

cpp_path = [meshadapter_test_path,
            escript_path,
            finley_path,
            finley_cppadapter_path,
            paso_path,
            mmio_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            finley_lib_path,
            mmio_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'finleycpp',
        'paso',
        'mmio',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'dl',
        'util']

sources = ['MeshAdapterTestCase.cpp',
           'MeshAdapterTest.cpp']

target = 'MeshAdapterTest.exe'

import os
meshadapter_env = Environment(ENV = os.environ)

meshadapter_env.Replace(CXX = cxx)
meshadapter_env.Replace(CXXFLAGS = cxx_flags)
meshadapter_env.Replace(CPPPATH = cpp_path)
meshadapter_env.Replace(LIBPATH = lib_path)
meshadapter_env.Replace(LIBS = libs)

meshadapter_test_exe = meshadapter_env.Program(target, sources)

Depends(meshadapter_test_exe, finley_lib)

Alias("build_tests", meshadapter_env.Install(install_dir, meshadapter_test_exe))

import scons_extensions
runUnitTest_builder = Builder(action = scons_extensions.runUnitTest, suffix = '.passed', single_source=True)
meshadapter_env.Append(BUILDERS = {'RunUnitTest' : runUnitTest_builder});

Alias("run_tests", meshadapter_env.RunUnitTest(target))
