# Scons configuration file for finley MeshAdapter unit tests

import os
import sys

#
# ensure correct versions of python and scons

EnsurePythonVersion(2,3)
EnsureSConsVersion(0,96)

#
# set appropriate defaults for configuration variables

esysroot = Dir('#../../..')
usegcc = 0

#
# retreive command-line arguments if any

if ARGUMENTS.get('usegcc',0):
  usegcc = 1

#
# determine platform

env = Environment(ENV = os.environ)
platform = env['PLATFORM']

#
# determine hostname

hostname = os.environ['HOSTNAME']

#
# load configuration settings

options_dir = str(esysroot) + '/scons'
sys.path.append(options_dir)

if hostname=='ess':
  from ess_options import *

if usegcc==1:
  from gcc_options import *

cxx_flags=cxx_flags_debug

#
# print out build configuration for this module

print "######################################################"
print "Build configuration for module: MeshAdapter unit tests"
print "         dodebug:  1"
print "          usegcc: ", usegcc
print "             cxx: ", cxx
print "        platform: ", platform
print "        hostname: ", hostname
print "######################################################"

#
# do the actual build

meshadapter_test_path = str(esysroot) + '/finley/test/MeshAdapter'
escript_path = str(esysroot) + '/escript/inc'
finley_path = str(esysroot) + '/finley/src/finley'
finley_cppadapter_path = str(esysroot) + '/finley/src/finley/CPPAdapter'
paso_path = str(esysroot) + '/paso/inc'
mmio_path = str(esysroot) + '/tools/mmio/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
finley_lib_path = str(esysroot) + '/finley/lib'
mmio_lib_path = str(esysroot) + '/tools/mmio/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

cpp_path = [meshadapter_test_path,
            escript_path,
            finley_path,
            finley_cppadapter_path,
            paso_path,
            mmio_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            finley_lib_path,
            mmio_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'finleycpp',
        'paso',
        'mmio',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'scs_mp',
        'dl',
        'util',
        'guide',
        'irc']

sources = ['MeshAdapterTestCase.cpp',
           'MeshAdapterTest.cpp']

target = 'MeshAdapterTest.exe'

meshadapter_env = Environment(ENV = os.environ)

meshadapter_env.Replace(CXX = cxx)
meshadapter_env.Replace(CXXFLAGS = cxx_flags)
meshadapter_env.Replace(CPPPATH = cpp_path)
meshadapter_env.Replace(LIBPATH = lib_path)
meshadapter_env.Replace(LIBS = libs)

meshadapter_test_exe = meshadapter_env.Program(target, sources)
