
##############################################################################
#
# Copyright (c) 2003-2016 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

Import('*')
local_env = env.Clone()

sources = """
    pyerr.cpp
""".split()

headers = """
    IndexList.h
    index.h
    pyerr.h
    first.h
""".split()

lib_name = 'esysUtils'

include_path = Dir(lib_name, local_env['incinstall'])
hdr_inst = local_env.Install(include_path, headers)

if local_env['build_shared']:
    lib = local_env.SharedLibrary(lib_name, sources)
else:
    lib = local_env.StaticLibrary(lib_name, sources)

lib_inst = local_env.Install(local_env['libinstall'], lib)

env.Alias('build_esysUtils_lib', lib)
env.Alias('install_esysUtils_headers', hdr_inst)
env.Alias('install_esysUtils_lib', lib_inst)

