#!/bin/bash
# $Id$
if [ ! -e Makefile ]; then ln -s ./SystemMatrixAdapterTest.mk Makefile; fi
make -f ./Makefile clean
make -f ./Makefile DODEBUG=YES
./SystemMatrixAdapterTest.exe
make -f ./Makefile clean
