##############################################################################
#
# Copyright (c) 2003-2018 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
#
##############################################################################

Import('env')

# configure C++ library
env.SConscript('src/SConscript', duplicate=0)

# configure python module
env.SConscript('py_src/SConscript', variant_dir='py', duplicate=0)

# configure unit tests
env.SConscript('test/SConscript', duplicate=0)

