
##############################################################################
#
# Copyright (c) 2003-2014 by University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

Import('*')
local_env = env.Clone()

lib_name = 'paso'

sources = """
    AMG.cpp
    AMG_Interpolation.cpp
    AMG_Prolongation.cpp
    AMG_Restriction.cpp
    AMG_Root.cpp
    BiCGStab.cpp
    BlockOps.cpp
    Coupler.cpp
    Distribution.cpp
    FCT_Solver.cpp
    FluxLimiter.cpp
    Functions.cpp
    GMRES.cpp
    GMRES2.cpp
    LocalAMG.cpp
    LocalAMG_Prolongation.cpp
    MergedSolver.cpp
    MKL.cpp
    NewtonGMRES.cpp
    Options_getPackage.cpp
    Options_getSolver.cpp
    Options_setDefaults.cpp
    PCG.cpp
    PasoUtil.cpp
    Pattern.cpp
    Pattern_mis.cpp
    Pattern_reduceBandwidth.cpp
    Preconditioner.cpp
    ReactiveSolver.cpp
    SchurComplement.cpp
    Smoother.cpp
    Solver.cpp
    Solver_Function.cpp
    SparseMatrix.cpp
    SparseMatrix_getSubmatrix.cpp
    SparseMatrix_nullifyRowsAndCols.cpp
    SparseMatrix_saveHB.cpp
    SparseMatrix_MatrixMatrix.cpp
    SparseMatrix_MatrixMatrixTranspose.cpp
    SparseMatrix_MatrixVector.cpp
    SystemMatrix.cpp
    SystemMatrix_MatrixVector.cpp
    SystemMatrix_copyRemoteCoupleBlock.cpp
    SystemMatrix_debug.cpp
    SystemMatrix_extendedRows.cpp
    SystemMatrix_loadMM.cpp
    SystemMatrix_mergeMainAndCouple.cpp
    SystemMatrixPattern.cpp
    SystemMatrixPattern_unrollBlocks.cpp
    Transport.cpp
    Transport_solve.cpp
    BOOMERAMG.cpp
    ILU.cpp
    MINRES.cpp
    RILU.cpp
    TFQMR.cpp
    UMFPACK.cpp
    mmio.cpp
    performance.cpp
    solve.cpp
""".split()

headers = """
    BlockOps.h
    Common.h
    Coupler.h
    Distribution.h
    FluxLimiter.h
    Functions.h
    MergedSolver.h
    MKL.h
    Options.h
    Paso.h
    PasoUtil.h
    Pattern.h
    Preconditioner.h
    SharedComponents.h
    Solver.h
    Transport.h
    FCT_Solver.h
    ReactiveSolver.h
    SparseMatrix.h
    SystemMatrix.h
    SystemMatrixPattern.h
    BOOMERAMG.h
    UMFPACK.h
    mmio.h
    performance.h
""".split()

# And just for blocktimer cancer.....
local_env.Prepend(LIBS = ['esysUtils'])
if IS_WINDOWS:
    local_env.Append(CPPDEFINES = ['PASO_EXPORTS'])

if local_env['build_shared']:
    lib = local_env.SharedLibrary(lib_name, sources)
else:
    lib = local_env.StaticLibrary(lib_name, sources)

env.Alias('build_paso_lib', lib)

include_path = Dir('paso', local_env['incinstall'])
solvers_include_path = Dir('Solvers', include_path)

hdr_inst = local_env.Install(include_path, headers)
env.Alias('install_paso_headers', hdr_inst)

lib_inst = local_env.Install(local_env['libinstall'], lib)
env.Alias('install_paso_lib', lib_inst)

