#
# $Id$
#
#######################################################
#
#           Copyright 2003-2007 by ACceSS MNRF
#       Copyright 2007 by University of Queensland
#
#                http://esscc.uq.edu.au
#        Primary Business: Queensland, Australia
#  Licensed under the Open Software License version 3.0
#     http://www.opensource.org/licenses/osl-3.0.php
#
#######################################################
#

import os
Import('*')

try:
  local_env = env.Clone()	# scons-98.03
except AttributeError:
  local_env = env.Copy()	# scons-96.92

# get all the file names in doc/examples:
src_dir = local_env.Dir('examples').srcnode().abspath
example_files = os.popen("find " + src_dir + " -name .svn -prune -o -type f -print").read().split(None)

env.Zip('#release/doc/escript_examples.zip', example_files)
env.Alias('examples_zipfile', '#release/doc/escript_examples.zip')

env.Tar('#release/doc/escript_examples.tar.gz', example_files)
env.Alias('examples_tarfile', '#release/doc/escript_examples.tar.gz')

local_env.SConscript(dirs = ['#/doc/user'], build_dir='#/build/$PLATFORM/doc/user', duplicate=1)
local_env.SConscript(dirs = ['#/doc/epydoc'], build_dir='#/build/$PLATFORM/doc/epydoc', duplicate=1)
local_env.SConscript(dirs = ['#/doc/doxygen'], build_dir='#/build/$PLATFORM/doc/doxygen', duplicate=1)

