# Scons configuration file for paso

import os
import sys

#
# ensure correct versions of python and scons

EnsurePythonVersion(2,3)
EnsureSConsVersion(0,96)

#
# set appropriate defaults for configuration variables

esysroot = Dir('#..')
libinstall = None
dodebug = 0
usegcc = 0
options = None

#
# import configuration variables passed in from
# calling SConscript (if any)

Import('*')

#
# retreive command-line arguments if any

if ARGUMENTS.get('libinstall',0):
  libinstall = ARGUMENTS.get('libinstall',0)
Export(["libinstall"])

if ARGUMENTS.get('debug',0):
  dodebug = 1

if ARGUMENTS.get('usegcc',0):
  usegcc = 1

if ARGUMENTS.get('options',0):
  options = ARGUMENTS.get('options',0)

#
# determine platform

env = Environment(ENV = os.environ)
platform = env['PLATFORM']

#
# determine hostname

import socket
hostname = socket.gethostname()

#
# export esysroot

Export(["esysroot"])

#
# set and export library directories

libdir = Dir(str(esysroot) + '/paso/lib')
Export(["libdir"])
libdir2 = Dir(str(esysroot) + '/lib')
Export(["libdir2"])

#
# load and export configuration settings

options_dir = str(esysroot) + '/scons'
sys.path.append(options_dir)

from default_options import *

if hostname=='ess':
  from ess_options import *

if usegcc==1:
  from gcc_options import *

if options!=None:
  exec "from " + options + " import *"

if dodebug==1:
  cc_flags=cc_flags_debug

Export(["python_path"])
Export(["boost_path"])
Export(["cc"])
Export(["cc_flags"])
Export(["ar_flags"])

#
# print out build configuration for this module

print "Build configuration for module: paso"
print "         dodebug: ", dodebug
print "          usegcc: ", usegcc
print "              cc: ", cc
print "        platform: ", platform
print "        hostname: ", hostname
print "      libinstall: ", libinstall

#
# call the SConscript to do the actual build

SConscript('src/SConscript', src_dir='src', build_dir='obj', duplicate=0)
