# Scons configuration file for DataVector unit tests

#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./../../../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

cxx_flags=cxx_flags_debug

print "Build configuration for module: DataVector unit tests"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# do the actual build

datavector_test_path = str(esysroot) + '/escript/test/DataVector'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/src'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

escript_lib = str(esys_lib_path) + '/libescriptcpp.so'

install_dir = str(esysroot) + '/escript/test'

cpp_path = [datavector_test_path,
            escript_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'dl',
        'util']

libs.extend(sys_libs)

sources = ['DataVectorTestCase.cpp',
           'DataVectorTest.cpp']

target = 'DataVectorTest.exe'

import os
datavector_env = Environment(ENV = os.environ)

datavector_env.Replace(CXX = cxx)
datavector_env.Replace(CXXFLAGS = cxx_flags)
datavector_env.Replace(CPPPATH = cpp_path)
datavector_env.Replace(LIBPATH = lib_path)
datavector_env.Replace(LIBS = libs)

datavector_test_exe = datavector_env.Program(target, sources)

Depends(datavector_test_exe, escript_lib)

Alias("build_tests", datavector_env.Install(install_dir, datavector_test_exe))

import scons_extensions
runUnitTest_builder = Builder(action = scons_extensions.runUnitTest, suffix = '.passed', single_source=True)
datavector_env.Append(BUILDERS = {'RunUnitTest' : runUnitTest_builder});

Alias("run_tests", datavector_env.RunUnitTest(target))
