Import('*')
local_env=env.Copy()

program_name = 'bruce_UnitTest'
local_env.Append(LIBS=[boost_lib_name, 'brucecpp', 'escriptcpp', 'esysUtils', 'CppUnitTest'])

src_dir = local_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
sources = [x for x in filenames if os.path.splitext(x)[1] in ['.cpp', '.c']]

if env['PLATFORM'] == "win32":
   local_env['PDB'] = program_name+'.pdb'


program = local_env.Program(program_name, sources)
# TODO: Need to decide on how the library paths etc are going to be handled
# TODO: For now just install the program to the same location as the libraries so things can run at least
local_env.Install(esys_lib, program)

# run the tests
local_env.RunUnitTest(program_name)

#Add Unit Test to target alias
test_targets = os.path.splitext(program_name)[0]+'.passed'
env.Alias('bruce_test', test_targets)

local_env.Export('program_name')
local_env.SConscript(dirs = ['#/bruce/test/python'], build_dir='py', duplicate=0)
