
########################################################
#
# Copyright (c) 2003-2012 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################

Import('*')
local_env = env.Clone()

if local_env['cppunit']:
    # get the test source file names
    sources = Glob('*.cpp')+Glob('*.c')
    testname='EsysExceptionTest'

    # build the executable
    local_env.Append(LIBS=['esysUtils']+env['cppunit_libs'])
    program = local_env.Program(testname, sources)

    # run the tests - but only if test_targets are stale
    local_env.RunUnitTest(testname)

    # add unit test to target alias
    Alias('build_tests', program)
    Alias("run_tests", testname+'.passed')

    # add a group of tests
    from grouptest import *
    tgroup=GroupTest("$BINRUNNER ", (), "", "$BUILD_DIR/esysUtils/test", ('./'+testname,))
    TestGroups.append(tgroup)

