package:
  name: esys-escript
  version: 3.5

source:
  - svn_url: https://svn.geocomp.uq.edu.au/svn/esys13/trunk
    svn_rev: 6805
    folder: escript

build:
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - esys-escript-dev-deps
    - gcc_linux-64      [unix]
    - gdal
    - gxx_linux-64      [unix]
    - hdf4
    - hdf5
    - libgcc            [unix]
    - libnetcdf
    - matplotlib
    - m2w64-gcc >5.3.0                 [win]
    - m2w64-gcc-fortran >5.3.0         [win]
    - m2w64-gcc-libs >5.3.0            [win]
    - m2w64-gcc-libgfortran >5.3.0     [win]
    - netcdf4
    - numpy
    - python =2.7
    - pyproj
    - scipy
    - scons
    - sympy
    - svn
    
  run:
    - esys-escript-dev-deps
    - gdal
    - hdf4
    - hdf5
    - libnetcdf
    - matplotlib
    - netcdf4
    - numpy
    - python =2.7
    - pyproj
    - scipy
    - suitesparse
    - sympy

about:
  home: https://launchpad.net/escript-finley
  license: Apache2
  summary: esys-escript is a programming tool for implementing mathematical 
    models in python using the finite element method (FEM).
  description: esys-escript is a programming tool for implementing mathematical 
    models in python using the finite element method (FEM). As users
    do not access the data structures it is very easy to use and 
    scripts can run on desktop computers as well as highly parallel
    supercomputer without changes. Application areas for escript 
    include earth mantle convection, geophysical inversion, 
    earthquakes, porous media flow, reactive transport, plate 
    subduction, erosion, and tsunamis.
  dev_url: https://launchpad.net/escript-finley
  doc_url: https://launchpad.net/escript-finley
  doc_source_url: https://launchpad.net/escript-finley