
##############################################################################
#
# Copyright (c) 2003-2020 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
# Development from 2019 by School of Earth and Environmental Sciences
#
##############################################################################

Import('*')
local_env = env.Clone()

# get the source file names
sources = Glob('*.py')
fmsources = Glob('forwardmodels/*.py')
appsources = Glob('apps/*.py')

# compile
pyc = local_env.PyCompile(sources)
fmpyc = local_env.PyCompile(fmsources)
apppyc = local_env.PyCompile(appsources)

# install
py_inst = local_env.Install(local_env['pyinstall']+'/downunder', pyc)
fmpy_inst = local_env.Install(local_env['pyinstall']+'/downunder/forwardmodels', fmpyc)
apppy_inst = local_env.Install(local_env['pyinstall']+'/downunder/apps', apppyc)
env.Alias('install_downunder_py', [py_inst, fmpy_inst, apppy_inst])

# configure unit tests
local_env.SConscript(dirs = ['#/downunder/test/python'], variant_dir='$BUILD_DIR/$PLATFORM/downunder/test/python', duplicate=0)

