#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       

import os
Import('*')

env.Command(env['prefix']+'/release/doc/epydoc', env['pyinstall'], [Mkdir(env['prefix']+'/release/doc/epydoc'), "epydoc --html -o $TARGET esys"])
env.Alias('api_epydoc', env['prefix']+'/release/doc/epydoc')

