
##############################################################################
#
# Copyright (c) 2003-2015 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

import os
Import('*')
local_env = env.Clone()

if not local_env['IS_WINDOWS']:
    prog = local_env.Program('escript-overlord', ['overlord.c'])
    env.Alias('build_overlord', prog)
    install_overlord = local_env.Install(local_env['bininstall'], prog)
    env.Alias('install_overlord', install_overlord) #oh no! our freedoms!

