# top-level Scons configuration file for all finley unit tests
esysroot=str(Dir('./../../').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

#
# call appropriate SConscripts

target_scripts = ['MeshAdapter/SConscript']

SConscript(target_scripts, duplicate=0)
