# Scons configuration file for documentation

#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       
#                                                          
#
#
# builds the user's guide

# command to run:
# epydoc --html -o doc/epydoc -n esys esys > /tmp/epydoc_msgs.txt 2>&1

import os
Import('*')

#local_env.PrependENVPath('PYTHONPATH',str(pyinstall))
env.Command(api_epydoc, pyinstall,"epydoc --html -o $TARGET esys esys")

