
# boostStatic - include directories plus library to link with

PKG_CC_INC_DIRS  += /opt/tools/boost_1_31-gcc3.4/include/boost-1_31
PKG_CPP_INC_DIRS += /opt/tools/boost_1_31-gcc3.4/include/boost-1_31

PKG_LD_LIB_DIRS += /opt/tools/boost_1_31-gcc3.4/lib
PKG_LD_LIBS += boost_python-gcc-1_31

