#!/bin/bash
# $Id$
if [ ! -e Makefile ]; then ln -s ./DataAlgorithmAdapterTest.mk Makefile; fi
make -f ./Makefile clean
make -f ./Makefile DODEBUG=YES
./DataAlgorithmAdapterTest.exe
make -f ./Makefile clean
