
########################################################
#
# Copyright (c) 2003-2008 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################


import os
Import('*')

local_env = clone_env(env)

# get all the file names in doc/examples:
src_dir = local_env.Dir('examples').srcnode().abspath
example_files = os.popen("find " + src_dir + " -name .svn -prune -o -type f -print").read().split(None)

if 'Zip' in dir(env): env.Zip('#release/doc/escript_examples.zip', example_files)
env.Alias('examples_zipfile', '#release/doc/escript_examples.zip')

env=Environment(TARFLAGS = '-c -z')
if 'Tar' in dir(env): env.Tar('#release/doc/escript_examples.tar.gz', example_files)
env.Alias('examples_tarfile', '#release/doc/escript_examples.tar.gz')

local_env.SConscript(dirs = ['#/doc/user'], build_dir='#/build/$PLATFORM/doc/user', duplicate=1)
local_env.SConscript(dirs = ['#/doc/epydoc'], build_dir='#/build/$PLATFORM/doc/epydoc', duplicate=1)
local_env.SConscript(dirs = ['#/doc/doxygen'], build_dir='#/build/$PLATFORM/doc/doxygen', duplicate=1)

