
##############################################################################
#
# Copyright (c) 2003-2014 by University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

import os
Import('*')
local_env = env.Clone()

if local_env['silo']:
    local_env.Append(CPPDEFINES = ['USE_SILO'])
    local_env.AppendUnique(LIBS = env['silo_libs'])

local_env.Prepend(LIBS = ['weipa', 'dudley', 'finley', 'ripley', 'escript', 'esysUtils'])
prog = local_env.Program('escriptconvert', ['escriptconvert.cpp'])
env.Alias('build_escriptconvert', prog)
inst_escriptconvert = local_env.Install(local_env['bininstall'], prog)
env.Alias('install_escriptconvert', inst_escriptconvert)

# esdcreate has no other dependencies
local_env = env.Clone()
prog = local_env.Program('esdcreate', 'esdcreate.cpp')
env.Alias('build_esdcreate', prog)
inst_esdcreate = local_env.Install(local_env['bininstall'], prog)
env.Alias('install_esdcreate', inst_esdcreate)

