
########################################################
#
# Copyright (c) 2003-2010 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################


import os
Import('*')

local_env = clone_env(env_mpi)
if local_env['silo']:
  local_env.Append(CPPDEFINES = ['USE_SILO'])
  local_env.AppendUnique(LIBS = [env['silo_libs']])

local_env.AppendUnique(LIBS = ['weipa','finley','escript'])
prog = local_env.Program('escriptconvert', ['escriptconvert.cpp'])
env.Alias('target_escriptconvert', prog)
inst_escriptconvert = local_env.Install(local_env['bininstall'], prog)
env.Alias('target_install_escriptconvert', inst_escriptconvert)

# esdcreate has no other dependencies
local_env = clone_env(env)
prog = local_env.Program('esdcreate', 'esdcreate.cpp')
env.Alias('target_esdcreate', prog)
inst_esdcreate = local_env.Install(local_env['bininstall'], prog)
env.Alias('target_install_esdcreate', inst_esdcreate)

