
##############################################################################
#
# Copyright (c) 2003-2026 by the esys.escript Group
# https://github.com/LutzGross/esys-escript.github.io
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
# Development from 2019 by School of Earth and Environmental Sciences
#
##############################################################################

import os
Import('*')
local_env = env.Clone()

if local_env['silo']:
    local_env.AppendUnique(LIBS = env['silo_libs'])

local_env.Prepend(LIBS = ['weipa', 'finley', 'ripley', 'escript'])
prog = local_env.Program('escriptconvert', ['escriptconvert.cpp'])
env.Alias('build_escriptconvert', prog)
inst_escriptconvert = local_env.Install(local_env['bininstall'], prog)
env.Alias('install_escriptconvert', inst_escriptconvert)

# esdcreate has no other dependencies
local_env = env.Clone()
prog = local_env.Program('esdcreate', 'esdcreate.cpp')
env.Alias('build_esdcreate', prog)
inst_esdcreate = local_env.Install(local_env['bininstall'], prog)
env.Alias('install_esdcreate', inst_esdcreate)

