#!/bin/sh
###
### This is a example of PBS scripti, you can modify to submit your job
###
### Job name
#PBS -N Tst
### Specify a queue
#PBS -q workq
### Specify required resources
#PBS -l ncpus=10
#PBS -l mem=10gb
#PBS -l walltime=2:00
### Redirecting Output and Error files
#PBS -e ./out.err
#PBS -o ./out.log
### Mailing ALerts: a -abort, b -begin execution and e -end execution
#PBS -m abe
 
###
### This section is for debuging the script (it is not essentail)
###
# This job's working directory

echo Working directory is $PBS_O_WORKDIR
 
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`

export LD_LIBRARY_PATH=/opt/intel/cmplrs/80.058/intel_cc_80/lib:/raid2/john/newEsys/esys/tools/boost/bin/boost/libs/python/build/libboost_python.so/intel-ia64/debug/shared-linkable-true
export PATH=/usr/local/bin:${PATH}
export PYTHON_LIB_PATH=/usr/local/lib/python2.2
export PYTHON_INCLUDE=/usr/local/include/python2.2

python $PBS_O_WORKDIR/escriptTest.py

echo Done
