# Scons configuration file for mmio

#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

libdir = Dir(str(esysroot) + '/tools/mmio/lib')
Export(["libdir"])

Export(["cc"])
Export(["cc_flags"])
Export(["ar_flags"])

#
# print out build configuration for this module

print "Build configuration for module: mmio"
print "         ccflags: ", cc_flags
print "              cc: ", cc

#
# call the SConscript to do the actual build

SConscript('src/SConscript', src_dir='src', build_dir='obj', duplicate=0)
