# Scons configuration file for mmio

import os

#
# ensure correct versions of python and scons

EnsurePythonVersion(2,3)
EnsureSConsVersion(0,96)

#
# set appropriate defaults for configuration variables

esysroot = Dir('#../..')
dodebug = 0
usegcc = 0

#
# import configuration variables passed in from
# calling SConscript (if any)

Import('*')

#
# retreive command-line arguments if any

if ARGUMENTS.get('debug',0):
  dodebug = 1

if ARGUMENTS.get('usegcc',0):
  usegcc = 1

#
# determine platform

env = Environment(ENV = os.environ)
platform = env['PLATFORM']

#
# determine hostname

hostname = os.environ['HOSTNAME']

#
# export esysroot

Export(["esysroot"])

#
# set and export library directory

libdir = Dir(str(esysroot) + '/tools/mmio/lib')
Export(["libdir"])

#
# load and export configuration settings

cc_flags = '-O0 -openmp -openmp_report0 -tpp2 -ansi -ansi_alias -no-gcc -fpic -w1'

Export(["cc_flags"])

#
# print out build configuration for this module

print "############################################"
print "Build configuration for module: mmio"
print "         dodebug: ", dodebug
print "          usegcc: ", usegcc
print "        platform: ", platform
print "        hostname: ", hostname
print "############################################"

#
# call the SConscript to do the actual build

SConscript('src/SConscript', src_dir='src', build_dir='obj', duplicate=0)
