
##############################################################################
#
# Copyright (c) 2003-2026 by the esys.escript Group
# https://github.com/LutzGross/esys-escript.github.io
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
# Development from 2019 by School of Earth and Environmental Sciences
#
##############################################################################

import os
Import('*')
local_env = env.Clone()

if not local_env['IS_WINDOWS']:
    prog = local_env.Program('escript-overlord', ['overlord.cpp'])
    env.Alias('build_overlord', prog)
    install_overlord = local_env.Install(local_env['bininstall'], prog)
    env.Alias('install_overlord', install_overlord) #oh no! our freedoms!

