# Scons configuration file for pyvisi

#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

Export(["python_path"])
Export(["pyinstall"])

#
# set and export python directories

pydir = Dir(str(esysroot) + '/pyvisi/lib/py_src')
Export(["pydir"])
pydir2 = Dir(str(esysroot) + '/esys/pyvisi')
Export(["pydir2"])
if pyinstall != None:
  pyinstall = Dir(str(pyinstall) + '/pyvisi')
  Export(["pyinstall"])

SConscript(dirs=['py_src'], build_dir='obj/py_src', duplicate=0)
SConscript(dirs=['py_src/renderers'], build_dir='obj/py_src/renderers', duplicate=0)
SConscript(dirs=['py_src/renderers/gnuplot'], build_dir='obj/py_src/renderers/gnuplot', duplicate=0)
SConscript(dirs=['py_src/renderers/opendx'], build_dir='obj/py_src/renderers/opendx', duplicate=0)
SConscript(dirs=['py_src/renderers/plplot'], build_dir='obj/py_src/renderers/plplot', duplicate=0)
SConscript(dirs=['py_src/renderers/povray'], build_dir='obj/py_src/renderers/povray', duplicate=0)
SConscript(dirs=['py_src/renderers/vtk'], build_dir='obj/py_src/renderers/vtk', duplicate=0)
