# Scons configuration file for pyvisi

#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

Export(["python_path"])
Export(["pyinstall"])

#
# set and export python directories

pydir = Dir(str(esysroot) + '/pyvisi/lib/py_src')
Export(["pydir"])
pydir2 = Dir(str(esysroot) + '/esys/pyvisi')
Export(["pydir2"])
if pyinstall != None:
  pyinstall = Dir(str(pyinstall) + '/pyvisi')
  Export(["pyinstall"])

SConscript(dirs=['py_src'], build_dir='obj/py_src', duplicate=0)
SConscript(dirs=['py_src/renderers'], build_dir='obj/py_src/renderers', duplicate=0)
# SConscript(dirs=['test/MeshAdapter'], build_dir='obj/test/MeshAdapter', duplicate=0)
