#!/bin/env bash
# $Id$
# simple script to run all bruce unit tests

MODULES="Bruce BruceFactory"

for module in $MODULES ; do
  echo Testing: $module
  cd $module
  ./unit_test
  if [ $? != 0 ]
  then
    echo Unit Testing FAILED for module: $module
    exit 1
  fi
  cd ..
done
exit 0
