Import('*')

paso_env=env.Copy()

src_dir = paso_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
sources = [x for x in filenames if os.path.splitext(x)[1] in ['.cpp', '.c']]
headers = [x for x in filenames if os.path.splitext(x)[1] in ['.h']]

# Paso has additional source in the Solvers sub-directory. Append these to the list
solver_filenames = os.listdir(src_dir+'/Solvers');
sources += ['Solvers/'+x for x in solver_filenames if os.path.splitext(x)[1] in ['.cpp', '.c']]
headers += ['Solvers/'+x for x in solver_filenames if os.path.splitext(x)[1] in ['.h']]

# TODO: if building with SCSL then the appropriate sources need to be appended to the above.                         
                         
if env['PLATFORM'] == "win32":
   paso_env.Append(CPPDEFINES=['_WINDOWS', '_USRDLL', 'PASO_EXPORTS'])
   paso_env.Append(LIBS='mmio')
   paso_env['PDB'] = 'paso.pdb'

paso_lib = paso_env.SharedLibrary( 'paso', sources)

include = Dir('Paso', esys_inc)

paso_env.Install( include, headers)
paso_env.Install( esys_lib, paso_lib)
