
##############################################################################
#
# Copyright (c) 2003-2018 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
#
##############################################################################

from os.path import splitext
Import('*')

local_env = env.Clone()

#  files defining test runs (passing in a release)
testruns = []
testruns += ['run_units.py']
testruns += ['run_data_access.py']
testruns += ['run_testdomain.py']
if env['sympy']:
    testruns += ['run_symbolic.py']


# files defining tests run locally (not as part of a release)
localtestruns = [x for x in Glob('*.py', strings=True) if not x.startswith('run_')]

# all test
alltestruns = testruns + localtestruns

# test files are just compiled
sources = Glob('test_*.py')
test_pyc = env.PyCompile(sources)
env.Alias('build_py_tests', test_pyc)

# add unit test to target alias
local_env.PrependENVPath('PYTHONPATH', Dir('.').abspath)
local_env.PrependENVPath('PYTHONPATH', '.')
local_env['ENV']['ESCRIPT_TEST_DATA_ROOT']=Dir('.').srcnode().abspath
local_env['ENV']['ESCRIPT_WORKDIR']=Dir('.').abspath
env.Alias('local_py_tests',[splitext(x)[0]+'.passed' for x in alltestruns])
env.Alias('py_tests', [splitext(x)[0]+'.passed' for x in testruns])

# run all tests
program = local_env.RunPyUnitTest(alltestruns)
Requires(program, ['install_escript', 'build_py_tests'])
if env['usempi']:
    Requires(program, ['install_pythonMPI'])

# add a group of tests
from grouptest import GroupTest
tgroup=GroupTest("escript", "$PYTHONRUNNER ", (("ESCRIPT_TEST_DATA_ROOT","$BATCH_ROOT/escriptcore/test/python"),('ESCRIPT_WORKDIR','$BUILD_DIR/escriptcore/test/python')), "$BATCH_ROOT/escriptcore/test/python","$BUILD_DIR/escriptcore/test/python", testruns)
TestGroups.append(tgroup)

