#!/bin/bash

# Escript/Finley wrapper for python
# Sets LD_LIBRARY_PATH and PYTHONPATH and then runs either python or the MPI launcher

#Extra paths can be configured about a page further down
#Search for EXTRA_PATH=""

#set to 1 if performing this is a standalone build and /packages contains the relevant tools
STANDALONE=0

#Now we find the location of this script
#Note that this location should be absolute but does not need to be unique
scriptdir=""
CURDIR=`pwd`

#Need to match if the name contains /
if [[ $0 =~ / ]]
then
    # We are not using the PATH to find the script
    cd `dirname $0`
    scriptdir=`pwd`
    cd $CURDIR
else
    # name does not contain / therefore we are using 
    tscriptdir=`which $0`
    if [ $? != 0 ]
    then
        echo "Error unable to determine script directory. Exiting."
	exit 1
    fi
    scriptdir=`dirname $tscriptdir`
fi

cd $scriptdir/..
ESCRIPT_ROOT=`pwd`
cd ..
ESCRIPT_PARENT=`pwd`
cd $CURDIR

##### End finding ESCRIPT_ROOT  ########

# if possible please express paths relative to $ESCRIPT_ROOT unless
# they are in an unrelated location

EXTRA_PATH=""
EXTRA_LD_LIBRARY_PATH=""
EXTRA_DYLD_LIBRARY_PATH=""
EXTRA_PYTHONPATH=""

if [ $STANDALONE == 1 ]
then
    EXTRA_PATH=$ESCRIPT_PARENT/packages/python/bin:$EXTRA_PATH
    EXTRA_LD_LIBRARY_PATH=$ESCRIPT_PARENT/packages/boost/lib:$ESCRIPT_PARENT/packages/netcdf/lib/:$EXTRA_LD_LIBRARY_PATH
    EXTRA_LD_LIBRARY_PATH=$ESCRIPT_PARENT/packages/vtk/lib/vtk-5.2:$ESCRIPT_PARENT/packages/mesa/lib:$EXTRA_LD_LIBRARY_PATH
    EXTRA_LD_LIBRARY_PATH=$ESCRIPT_PARENT/packages/python/lib:$EXTRA_LD_LIBRARY_PATH
    EXTRA_PYTHONPATH=$ESCRIPT_PARENT/packages/numarray/lib:$ESCRIPT_PARENT/packages/vtk/lib/python2.6/site-packages:$EXTRA_PYTHONPATH
fi

# For stand-alone builds this will need to be changed
PYTHON_CMD=python

EXTRA_PYTHONPATH=$ESCRIPT_ROOT:$EXTRA_PYTHONPATH
EXTRA_LD_LIBRARY_PATH=$ESCRIPT_ROOT/lib:$EXTRA_LD_LIBRARY_PATH


HELP_TEXT="
Usage: escript [options] script.py [arguments...]
	-O N		Use N OpenMP threads (OMP_NUM_THREADS=N)
	-M K		Use K MPI processes
	-l 'launcher'	MPI launcher, usually -l 'mpirun -np' or -l 'mpiexec -n'
	-L /path	Prepend /path to library search path
	-P /path	Prepend /path to python module search path
	-e		Print export statements for environment and exit
	script.py	Your python script
	arguments...	The optional command-line arguments to your python script
"

if [ "$1" = "--help" ]; then
  echo "$HELP_TEXT"
  exit 0
fi



# Avoid bug in hybrid runs with MPT MPI
export MPI_NUM_MEMORY_REGIONS=0

# Try to guess the MPI launcher (mpirun unless in PBS batch job in which case mpiexec)
mpi_launcher='mpirun -np'
if [ $?PBS_ENVIRONMENT ]; then
  if [ "X_$PBS_ENVIRONMENT" = "X_PBS_BATCH" ]; then
    mpi_launcher='mpiexec -n'
  fi  
fi

PYTHON_MPI="$ESCRIPT_ROOT/lib/pythonMPI"
OMP_NUM_THREADS=1
MPI_NUM_PROCS=1

# Parse the command-line options
# option e should not be followed by a :
while getopts 'L:P:O:M:l:e' option
do
	case "$option" in
	  "L")	EXTRA_LD_LIBRARY_PATH="$OPTARG:$EXTRA_LD_LIBRARY_PATH"
		;;
	  "P")	EXTRA_PYTHONPATH="$OPTARG:$EXTRA_PYTHONPATH"
		;;
	  "O")	OMP_NUM_THREADS="$OPTARG"
		;;
	  "M")	MPI_NUM_PROCS="$OPTARG"
		;;
	  "l")	mpi_launcher="$OPTARG"
		;;
	  "e")  echo "export LD_LIBRARY_PATH=$EXTRA_LD_LIBRARY_PATH:\$LD_LIBRARY_PATH"
		echo "export PYTHONPATH=$EXTRA_PYTHONPATH:\$PYTHONPATH"
		echo "export PATH=$EXTRA_PATH:\$PATH"
		if [ `uname` == Darwin ]
		then
		    echo "export DYLD_LIBRARY_PATH=$EXTRA_DYLD_LIBRARY_PATH:$EXTRA_LD_LIBRARY_PATH:\$DYLD_LIBRARY_PATH"
		fi
		exit 0
		;;
	  ?)	echo "$HELP_TEXT"
		exit 1
		;;
	esac
done
shift `expr $OPTIND - 1`

export PATH=$EXTRA_PATH:$PATH
export LD_LIBRARY_PATH=$EXTRA_LD_LIBRARY_PATH:$LD_LIBRARY_PATH
export PYTHONPATH=$EXTRA_PYTHONPATH:$PYTHONPATH
if [ `uname` == Darwin ]
then
    export DYLD_LIBRARY_PATH=$EXTRA_DYLD_LIBRARY_PATH:$EXTRA_LD_LIBRARY_PATH:$DYLD_LIBRARY_PATH
fi

# Check to see if the python version we were compiled with matches the one of PYTHON_CMD
if [ -f $ESCRIPT_ROOT/lib/pyversion ]
then
   compversion=`cat $ESCRIPT_ROOT/lib/pyversion`
   intversion=`python --version 2>&1`
   if [ "$compversion" != "$intversion" ]
   then
      echo "Python versions do not match. Escript was compiled for "$compversion"."
      echo "Current version of Python appears to be "$intversion"."
      exit 1
   fi
fi

# Must have at least one command-line arg: the python script
if [ $# -eq 0 ]; then
  echo "No python script specified. Starting python interpreter."
#   echo "Missing python script"
#   echo "$HELP_TEXT"
#   exit 1
fi

# Using OpenMP?
OMP_OPTIONS=''
if [ -f "$ESCRIPT_ROOT/lib/Compiled.with.openmp" ]; then
#  PYTHON_CMD="$mpi_launcher $MPI_NUM_PROCS $PYTHON_MPI"
  OMP_OPTIONS="env OMP_NUM_THREADS=$OMP_NUM_THREADS"
fi

# Using MPI?
if [ -f "$ESCRIPT_ROOT/lib/Compiled.with.mpi" ]; then
  PYTHON_CMD="$mpi_launcher $MPI_NUM_PROCS $PYTHON_MPI"
else
  if [ "$MPI_NUM_PROCS" -ne 1 ]; then
    echo "Escript/Finley was not compiled for MPI so you must use -M 1"
    exit 1
  fi
fi

set -x
$OMP_OPTIONS $PYTHON_CMD "$@"

