#!/bin/bash

# Escript/Finley wrapper for python
# Sets LD_LIBRARY_PATH and PYTHONPATH and then runs either python or the MPI launcher

#Extra paths can be configured about a page further down
#Search for EXTRA_PATH=""

#set to 1 if performing this is a standalone build and /packages contains the relevant tools
STANDALONE=0

#Now we find the location of this script
#Note that this location should be absolute but does not need to be unique
scriptdir=""
CURDIR=`pwd`

#Environment vars which control operations:
# ESCRIPT_NUM_NODES, ESCRIPT_NUM_PROC, ESCRIPT_NUM_THREADS, ESCRIPT_HOSTFILE, ESCRIPT_CREATESTDFILES

HOSTFILE=/tmp/escript.$$


#Need to match if the name contains /
if [[ $0 =~ / ]]
then
    # We are not using the PATH to find the script
    cd `dirname $0`
    scriptdir=`pwd`
    cd $CURDIR
else
    # name does not contain / therefore we are using 
    tscriptdir=`which $0`
    if [ $? != 0 ]
    then
        echo "Error unable to determine script directory. Exiting."
	exit 1
    fi
    scriptdir=`dirname $tscriptdir`
fi

cd $scriptdir/..
ESCRIPT_ROOT=`pwd`
cd ..
ESCRIPT_PARENT=`pwd`
cd $CURDIR
##### End finding ESCRIPT_ROOT  ########

PYTHON_MPI="$ESCRIPT_ROOT/lib/pythonMPI"
PYTHON_CMD=python

# if possible please express paths relative to $ESCRIPT_ROOT unless
# they are in an unrelated location

EXTRA_DYLD_LIBRARY_PATH=""
EXTRA_PATH=$ESCRIPT_ROOT/bin
EXTRA_PYTHONPATH=$ESCRIPT_ROOT
EXTRA_LD_LIBRARY_PATH=$ESCRIPT_ROOT/lib

if [ $STANDALONE == 1 ]
then
    EXTRA_PATH=$ESCRIPT_PARENT/packages/python/bin:$EXTRA_PATH
    EXTRA_LD_LIBRARY_PATH=$ESCRIPT_PARENT/packages/boost/lib:$ESCRIPT_PARENT/packages/netcdf/lib/:$EXTRA_LD_LIBRARY_PATH
    EXTRA_LD_LIBRARY_PATH=$ESCRIPT_PARENT/packages/vtk/lib/vtk-5.2:$ESCRIPT_PARENT/packages/mesa/lib:$EXTRA_LD_LIBRARY_PATH
    EXTRA_LD_LIBRARY_PATH=$ESCRIPT_PARENT/packages/python/lib:$EXTRA_LD_LIBRARY_PATH
    EXTRA_PYTHONPATH=$ESCRIPT_PARENT/packages/numarray/lib:$ESCRIPT_PARENT/packages/vtk/lib/python2.6/site-packages:$EXTRA_PYTHONPATH
fi



HELP_TEXT="
Usage: escript [options] script.py [arguments...]
	-n nn		number of nodes to use
	-p np		number of MPI processes to spawn
	-t nt		number of OpenMP threads to use
	-f file		name of MPI hostfile
	-c 		print compile information for escript and exit
	-V		print escript version and exit
	-i		interactive mode 
	-b		do not invoke python (run non-python programs)
	-e		print export statements for environment and exit
	-o		redirect output from MPI to files
	-v		print diagnostics
	-x		..reserved for future use ..
	script.py	Your python script
	arguments...	The optional command-line arguments to your script
"

if [ "$1" = "--help" ]; then
  echo "$HELP_TEXT"
  exit 0
fi
#=======================================================================================

# Avoid bug in hybrid runs with MPT MPI


# Parse the command-line options
# option e should not be followed by a :
while getopts 'bn:p:t:f:h:ecVviox' option
do
	case "$option" in
	  "b")  DOBINARY=yes
		;;
	  "n")	ESCRIPT_NUM_NODES=$OPTARG
		;;
	  "p")	ESCRIPT_NUM_PROC=$OPTARG
		;;
	  "t")	ESCRIPT_NUM_THREADS=$OPTARG
		;;
	  "f")	ESCRIPT_HOSTFILE=$OPTARG
		;;
	  "c")  cat $ESCRIPT_ROOT/lib/buildvars
		exit 0
		;;
	  "V")	echo "escript-pre2.0(build "`grep svn_revision $ESCRIPT_ROOT/lib/buildvars |cut -d= -f2`")"
		exit 0
		;;
	  "h")  echo "$HELPTEXT"
		exit 0
		;;
	  "i")  DOINTERACTIVE=yes
		;;
	  "e")  echo "export LD_LIBRARY_PATH=$EXTRA_LD_LIBRARY_PATH:\$LD_LIBRARY_PATH"
		echo "export PYTHONPATH=$EXTRA_PYTHONPATH:\$PYTHONPATH"
		echo "export PATH=$EXTRA_PATH:\$PATH"
		if [ `uname` == Darwin ]
		then
		    echo "export DYLD_LIBRARY_PATH=$EXTRA_DYLD_LIBRARY_PATH:$EXTRA_LD_LIBRARY_PATH:\$DYLD_LIBRARY_PATH"
		fi
		exit 0
		;;
	  "o")  ESCRIPT_CREATESTDFILES="yes"
		;;
	  "v")  ESCRIPT_VERBOSE="yes"
		;;
	  "x")  echo "-x not implemented yet"
		exit 1
		;;
	  ?)	echo "$HELP_TEXT"
		exit 1
		;;
	esac
done
shift `expr $OPTIND - 1`
#==============================================
#
#   Read the MPI_FLAVOUR from the buildvars
#
MPI_FLAVOUR=`grep mpi_flavour $ESCRIPT_ROOT/lib/buildvars |cut -d= -f2`

if [ -f "$ESCRIPT_ROOT/lib/Compiled.with.mpi" ] && [ $MPI_FLAVOUR  == "none" ]
then
     echo "compiled with MPI but no MPI flavour specified."
     exit 1
fi

if [ ! -z $ESCRIPT_VERBOSE  ]; then echo "MPI flavor is $MPI_FLAVOUR."; fi
if [ -f "$ESCRIPT_ROOT/lib/Compiled.with.openmp" ]; 
then
    ESCRIPT_WITH_OPENMP="yes"
fi
if [ ! -z $ESCRIPT_VERBOSE ] && [ ! -z $ESCRIPT_WITH_OPENMP ]; then echo "OpenMP enbaled."; fi
#
#  extend path variables
#
export PATH=$EXTRA_PATH:$PATH
export LD_LIBRARY_PATH=$EXTRA_LD_LIBRARY_PATH:$LD_LIBRARY_PATH
export PYTHONPATH=$EXTRA_PYTHONPATH:$PYTHONPATH
EXPORT_ENV="PATH, LD_LIBRARY_PATH, PYTHONPATH"
if [ `uname` == Darwin ]
then
    export DYLD_LIBRARY_PATH=$EXTRA_DYLD_LIBRARY_PATH:$EXTRA_LD_LIBRARY_PATH:$DYLD_LIBRARY_PATH
    EXPORT_ENV="$EXPORT_ENV, DYLD_LIBRARY_PATH"
fi
if [ ! -z $ESCRIPT_VERBOSE  ] 
then 
    echo "PATH = $PATH "
    echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH "
    echo "PYTHONPATH = $PYTHONPATH "
    if [ ! -z $DYLD_LIBRARY_PATH ]; then echo "DYLD_LIBRARY_PATH = $DYLD_LIBRARY_PATH "; fi
fi
#==============================================
#
#  Ensure the variables have sensible values
#
if [ $MPI_FLAVOUR  == "none" ] 
then
    if [ ! -z $ESCRIPT_NUM_NODES ]
    then
        echo "Warning: MPI disabled but number of nodes set. Option ignored."
    fi
    if [ ! -z $ESCRIPT_NUM_PROCS ]
    then
        echo "Warning: MPI disabled but number of processors per node set. Option ignored."
    fi
    if [ ! -z $ESCRIPT_HOSTFILE ]
    then
        echo "Warning: MPI disabled but host file is given. Option ignored."
    fi
    ESCRIPT_NUM_NODES=1
    ESCRIPT_NUM_PROCS=1
else
    if [ ! -z $ESCRIPT_HOSTFILE ] 
    then
        if [ -f $ESCRIPT_HOSTFILE ]
        then
            cat $ESCRIPT_HOSTFILE | sort -u > $HOSTFILE
            NUM_HOSTS = `wc -l $HOSTFILE`
            if [ ! -z $ESCRIPT_NUM_NODES ] 
            then
                if [ $NUM_HOSTS -ne $ESCRIPT_NUM_NODES ]
                then
                    echo "number of hosts selected in the host file $ESCRIPT_HOSTFILE needs to match the requested number of nodes $ESCRIPT_NUM_NODES."
                    exit 1
                fi
             else
                ESCRIPT_NUM_NODES = $NUM_HOSTS
             fi
        else
           echo "cannot find hostfile $ESCRIPT_HOSTFILE."
           exit 1
        fi
    else
        HOSTFILE=''
    fi

    if [ -z $ESCRIPT_NUM_NODES ]
    then
      ESCRIPT_NUM_NODES=1
    fi

    if [ -z $ESCRIPT_NUM_PROCS ]
    then
      ESCRIPT_NUM_PROCS=1
    fi

    if [ ! -z $ESCRIPT_VERBOSE  ]
    then 
          echo "ESCRIPT_NUM_NODES = $ESCRIPT_NUM_NODES "
          echo "ESCRIPT_NUM_PROCS = $ESCRIPT_NUM_PROCS "
    fi
fi

if [ ! -z $ESCRIPT_WITH_OPENMP ]
then
   if [ -z $ESCRIPT_NUM_THREADS ]
     then
     ESCRIPT_NUM_THREADS=$OMP_NUM_THREADS
     if [ -z $ESCRIPT_NUM_THREADS ]
     then
       ESCRIPT_NUM_THREADS=1
     fi
     if [ ! -z $ESCRIPT_VERBOSE ]; then echo "Number of threads is $ESCRIPT_NUM_THREADS."; fi
   fi
else
   ESCRIPT_NUM_THREADS=1
fi
#
# Now we compute total number of Processes
#
(( TOTPROC=$ESCRIPT_NUM_NODES * $ESCRIPT_NUM_PROCS))
if [ $? -ne 0 ]		#Some compute error 
then			#This could happen if the args were not a number
  echo "expression of total number of processors = $ESCRIPT_NUM_NODES * $ESCRIPT_NUM_PROCS is not numerical."
  exit 1
fi
#
# Test to ensure people aren't trying to combine interactive and multi-process
#
if [[ ( ( -z $DOINTERACTIVE ) || ( $# -eq 0 ) ) && ( $TOTPROC -gt 1) ]]
then
  echo "Interactive mode cannot be used with more than one process"
  exit 1
fi
#=========================================================================================================
# Must have at least one command-line arg: the python script
if [ $# -eq 0 ]
then
  if [ ! -z $DOBINARY ]
  then
    echo "No program to run was specified. Exiting."
    exit 1
  fi
fi

#=========================================================================================================
if [ ! -z $DOBINARY ]
then
    EXEC_CMD="$@"
else
    if [ $MPI_FLAVOUR  == "none" ]
    then
        # Check to see if the python version we were compiled with matches the one of EXEC_CMD
        # We should only do this check if they are running a python script
        if [ -f $ESCRIPT_ROOT/lib/pyversion ]
        then
           compversion=`cat $ESCRIPT_ROOT/lib/pyversion`
           intversion=`$PYTHON_CMD --version 2>&1`
           if [ "$compversion" != "$intversion" ]
           then
              echo "Python versions do not match. Escript was compiled for "$compversion"."
              echo "Current version of Python appears to be "$intversion"."
              exit 1
           fi
        fi
	if [ ! -z $DOINTERACTIVE ]
        then
           EXEC_CMD="$PYTHON_CMD -i $@"
        else
           EXEC_CMD="$PYTHON_CMD $@"
        fi
    else
        EXEC_CMD="$PYTHONMPI $@"
    fi
fi
if [ ! -z $ESCRIPT_VERBOSE ]; then echo "Command to be executed is $EXEC_CMD."; fi
#===============================================================================================
#
#   now we start to spwan things:
#
if [ ! -z $ESCRIPT_WITH_OPENMP ]
then
   export OMP_NUM_THREADS=$ESCRIPT_NUM_THREADS
   EXPORT_ENV="$EXPORT_ENV, OMP_NUM_THREADS"
fi

#=============== no MPI ===================================
if [ $MPI_FLAVOUR  == "none" ] 
then
   $EXEC_CMD 

#=============== OpenMPI ===================================
elif [ $MPI_FLAVOUR == "OPENMPI" ] 
then 
   echo "OPENMPI not implemented yet."

#=============== Intel MPI ===================================
elif [ $MPI_FLAVOR == "INTEL" ]
then
   if [ -z $HOSTFILE ] 
   then
      mpdboot -n $ESCRIPT_NUM_PROCS -r ssh -f $HOSTFILE
      if [ $? -ne 0 ] 
      then
         echo "mpdboot with host file $ESCRIPT_HOSTFILE for $ESCRIPT_NUM_PROCS nodes failed."
         exit 1
      else 
          if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdboot was started with host file $ESCRIPT_HOSTFILE for $ESCRIPT_NUM_PROCS nodes."; fi
      fi
   fi
   $CMD="mpiexec -n $ESCRIPT_NUM_PROCS -perhost $ESCRIPT_NUM_PROCS -envall -$EXEC_CMD"
   if [ ! -z $ESCRIPT_VERBOSE ]; then echo "MPI command is $CMD."; fi
   $CMD
   if [ -z $HOSTFILE ]
   then
       mpdallexit
       if [ ! -z $ESCRIPT_VERBOSE ]; then echo "mpdallexit executed."; fi
   fi 
#=============== SGI's MPIMPT ===================================
elif [ $MPI_FLAVOR == "MPT" ]
then
   export MPI_NUM_MEMORY_REGIONS=0
   EXPORT_ENV="$EXPORT_ENV, MPI_NUM_MEMORY_REGIONS"
   if [ -z $HOSTFILE ] 
   then
      HOST_LIST=`awk 'BEGIN{S=""}{if (S == "") { S = $0 } else {S = S "," $0}}END{print S}' $HOSTFILE`
      CMD="mpiexec $HOST_LIST $ESCRIPT_NUM_PROCS $EXEC_CMD"
   else
      CMD="mpiexec -np $TOTPROC -$EXEC_CMD"
   fi 
   if [ ! -z $ESCRIPT_VERBOSE ]; then echo "MPI command is $CMD."; fi
   $CMD
#=============== SGI's MPICH ===================================
elif [ $MPI_FLAVOR == "MPICH" ]
then
   echo "MPICH not implemented yet."
else
   echo "unknown MPI falvour $MPI_FLAVOR."
   exit 1
fi
exit 0
# Using OpenMP?
#OMP_OPTIONS=''
#if [ -f "$ESCRIPT_ROOT/lib/Compiled.with.openmp" ]; then
#  EXEC_CMD="$mpi_launcher $MPI_NUM_PROCS $PYTHON_MPI"
#  ESCRIPT_NUM_THREADS=$OMP_NUM_THREADS
#  OMP_OPTIONS="env OMP_NUM_THREADS=$ESCRIPT_NUM_THREADS"
#fi

# Using MPI?
#if [ -f "$ESCRIPT_ROOT/lib/Compiled.with.mpi" ]; then
#  EXEC_CMD="$mpi_launcher $MPI_NUM_PROCS $PYTHON_MPI"
#else
#  if [ "$TOTPROC" -ne 1 ]; then
#    echo "Escript/Finley was not compiled for MPI. You can not use the -n and -p options."
#    exit 1
#  fi
#fi
