# Scons configuration file for paso

#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       
#                                                          
#
#
# set appropriate configuration variable defaults

esysroot=str(Dir('./..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

Export(["scsl_path","scsl_libs"])
Export(["mkl_path","mkl_libs"])
Export(["umfpack_path","umfpack_libs"])
Export(["papi_path","papi_libs"])
Export(["python_path"])
Export(["boost_path"])
Export(["papi_path"])
Export(["cc"])
Export(["cc_flags"])
Export(["ar_flags"])
Export(["libinstall"])
Export(["incinstall"])

# set and export library directories

libdir = Dir(str(esysroot) + '/paso/lib')
Export(["libdir"])
libdir2 = Dir(str(esysroot) + '/lib')
Export(["libdir2"])

#
# set and export include directories

incdir = Dir(str(esysroot) + '/paso/inc')
Export(["incdir"])
incdir2 = Dir(str(esysroot) + '/inc')
Export(["incdir2"])
if incinstall != None:
  Export(["incinstall"])

#
# print out build configuration for this module

print "Build configuration for module: paso"
print "              cc: ", cc
print "        cc_flags: ", cc_flags

# call the SConscript to do the actual build

SConscript('src/SConscript', src_dir='src', build_dir='obj', duplicate=0)
