
##############################################################################
#
# Copyright (c) 2014-2018 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
#
##############################################################################

import os
Import('*')
local_env = env.Clone()

directories = """
cusp
cusp/precond
cusp/precond/aggregation
cusp/precond/aggregation/detail
cusp/precond/detail
cusp/krylov
cusp/krylov/detail
cusp/io
cusp/io/detail
cusp/gallery
cusp/relaxation
cusp/relaxation/detail
cusp/graph
cusp/graph/detail
cusp/graph/detail/dispatch
cusp/graph/detail/device
cusp/graph/detail/host
cusp/opengl
cusp/opengl/spy
cusp/opengl/spy/detail
cusp/detail
cusp/detail/dispatch
cusp/detail/device
cusp/detail/device/generalized_spmv
cusp/detail/device/transposed_spmv
cusp/detail/device/spmm
cusp/detail/device/spmv
cusp/detail/device/detail
cusp/detail/host
cusp/detail/host/reference
cusp/detail/host/detail
""".split()

for dir in directories:
    headers = Glob(os.path.join(dir,"*.*"))
    include_path = Dir(dir, local_env['incinstall'])
    hdr_inst = local_env.Install(include_path, headers)
    env.Alias('install_cusp_headers', hdr_inst)

