# $Id$

# CPPUnitTest

PKG_CC_INC_DIRS  += $(ESYS_ROOT)/tools/CppUnitTest/inc
PKG_CPP_INC_DIRS += $(ESYS_ROOT)/tools/CppUnitTest/inc

PKG_LD_LIB_DIRS += $(ESYS_ROOT)/tools/CppUnitTest/lib

PKG_LD_LIBS += CppUnitTest
