#!/bin/sh

# on MacOS libtoolize is called glibtoolize
if test \! x`which glibtoolize` = x; then
    LIBTOOLIZE=glibtoolize
else
    LIBTOOLIZE=libtoolize
fi
  
aclocal
$LIBTOOLIZE --copy --force
automake --add-missing --copy --foreign
autoconf

