# Scons configuration file for documentation

#          Copyright 2006 by ACcESS MNRF                   
#                                                          
#              http://www.access.edu.au                    
#       Primary Business: Queensland, Australia            
#  Licensed under the Open Software License version 3.0    
#     http://www.opensource.org/licenses/osl-3.0.php       
#                                                          
#
#
# builds the user's guide
latexmode='-interaction=nonstopmode'
import os
Import('*')

local_env=env.Copy()
tex_dir = local_env.Dir('.').srcnode().abspath
tex= [ env.File(x) for x in os.listdir(tex_dir) if not x.startswith('.') and not os.path.isdir(tex_dir+os.path.sep+x) and os.path.splitext(x)[1] in ['.tex', '.bib', '.sty', '.cfg', '.cls'] ] + \
     [ env.File('figures'+os.path.sep+x) for x in os.listdir(tex_dir+os.path.sep+'figures') if not x.startswith('.') ]

env.Command(guide_pdf,tex,
            [ "latex %s guide.tex"%latexmode,  \
              "bibtex guide",                  \
              "makeindex guide",               \
              "latex %s guide"%latexmode,      \
              "latex %s guide"%latexmode,      \
              "dvipdf guide.dvi %s"%guide_pdf  ],
            chdir=tex_dir)


env.Command(guide_html_index,tex,
            "latex2html -top_navigation                                               \
                        -bottom_navigation                                            \
                        -index_in_navigation                                          \
                        -contents_in_navigation                                       \
                        -next_page_in_navigation                                      \
                        -previous_page_in_navigation                                  \
                        -title \"esys user's guide\"                                  \
                        -noshow_section_numbers                                       \
                        -dir %s -mkdir                                                \
                        -address \"esys@esscc.uq.edu.au\"                             \
                        -antialias_text -antialias -transparent                       \
                        -noshort_extn                                                 \
                        -up_url \"http://www.access.edu.au/escript\", -up_title \"escript\" guide.tex"%os.path.splitext(str(guide_html_index))[0],
            chdir=tex_dir)
