
##############################################################################
#
# Copyright (c) 2003-2018 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

import os
Import('*')

epy_dir=os.path.join(release_dir, 'epydoc')
env.Command(epy_dir, [], [Mkdir(epy_dir)])

env.Alias('api_epydoc', [env['pyinstall'], epy_dir], "epydoc --docformat restructuredtext -v --html -o "+epy_dir+" esys")

# This will need to be here at least until the output of api_epydoc properly
# depends on the libraries it uses as input
env.AlwaysBuild('api_epydoc')

