
# Python Static - include files plus library to link with

PKG_CC_INC_DIRS  += ${shell find /usr/include -name python\* -maxdepth 1}
PKG_CPP_INC_DIRS += ${shell find /usr/include -name python\* -maxdepth 1}

PKG_LD_LIB_DIRS += /usr/lib

PKG_LD_LIBS += ${patsubst /usr/include/%, %, ${shell find /usr/include -name python\* -maxdepth 1}}
PKG_LD_LIBS += dl util

