#
# $Id$
#
#######################################################
#
#           Copyright 2003-2007 by ACceSS MNRF
#       Copyright 2007 by University of Queensland
#
#                http://esscc.uq.edu.au
#        Primary Business: Queensland, Australia
#  Licensed under the Open Software License version 3.0
#     http://www.opensource.org/licenses/osl-3.0.php
#
#######################################################
#

import os
Import('*')

local_env = clone_env(env)

script_dir = Dir('#.').abspath + '/scripts/'

wrapper = local_env.Command('finleypython', 'finley_wrapper_template', [
	'/bin/sh ' + script_dir + 'finley_wrapper_writer.sh < $SOURCE > $TARGET',
	Chmod('$TARGET', 0755),
])
local_env.Alias('target_finley_wrapper', wrapper)

tmp1 = local_env.Install(local_env['bininstall'], wrapper)
local_env.Alias('target_install_finley_wrapper', tmp1)

