
##############################################################################
#
# Copyright (c) 2003-2026 by the esys.escript Group
# https://github.com/LutzGross/esys-escript.github.io
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
# Development from 2019 by School of Earth and Environmental Sciences
#
##############################################################################

import re
Import('*')
local_env = env.Clone()

if local_env['cppunit']:
    # get the test source file names
    sources = Glob('*.cpp')
    testname = 'escript_UnitTest'

    # build the executable
    local_env.AppendUnique(LIBS=env['escript_libs']+env['cppunit_libs'])
    # some of these test files are too large to optimize
    local_env['CCFLAGS'] = re.sub('-O[0-9]', '-g', str(local_env['CCFLAGS']))
    program = local_env.Program(testname, sources)

    # run the tests - but only if test_targets are stale
    local_env.RunUnitTest(testname)

    # add unit test to target alias
    Alias('build_tests', program)
    Alias("run_tests", testname+'.passed')

    # add a group of tests
    from grouptest import GroupTest
    tgroup = GroupTest("escriptcpp", "$BINRUNNER ", (), "", "$BUILD_DIR/escriptcore/test", ('./'+testname,))
    TestGroups.append(tgroup)

# configure python unit tests
local_env.SConscript('python/SConscript', duplicate=0)

