
########################################################
#
# Copyright (c) 2003-2011 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################

Import('*')
local_env = env.Clone()

# get the source file names
sources = Glob('*.py')

# compile
pyc = local_env.PyCompile(sources)

# install
runmodel_inst = local_env.Install(local_env['bininstall'], 'runmodel.py')
py_inst = local_env.Install(local_env['pyinstall']+'/escript', pyc)
env.Alias('install_escript_py', [runmodel_inst, py_inst])

