
########################################################
#
# Copyright (c) 2009-2010 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################

import os
Import('*')
local_env = env.Clone()

latexmode='-interaction=nonstopmode'

tex_dir = local_env.Dir('.').srcnode().abspath
dir_cmd = "cd "+tex_dir+" && "
tex= [ env.File(x) for x in os.listdir(tex_dir) if not x.startswith('.') and not os.path.isdir(tex_dir+os.path.sep+x) and os.path.splitext(x)[1] in ['.tex', '.bib', '.sty', '.cfg', '.cls'] ] + \
     [ env.File('figures'+os.path.sep+x) for x in os.listdir(tex_dir+os.path.sep+'figures') if not x.startswith('.') ]

latexcmd=dir_cmd+"pdflatex %s \\\\newcommand{\\\\RepVersion}{`svnversion`\\\\xspace}\\\\input{cookbook.tex}"%latexmode

local_env.Command(env['prefix']+'/doc/cookbook/cookbook.pdf',[tex], \
            [ latexcmd, \
#              "bibtex cookbook", \
              dir_cmd+"makeindex cookbook", \
              latexcmd, \
              latexcmd ] \
)

tmp=local_env.InstallAs(target=env['prefix']+'/release/doc/cookbook/cookbook.pdf', source=env['prefix']+'/doc/cookbook/cookbook.pdf')

env.Alias('cookbook_pdf', tmp)

