# top-level Scons configuration file for all escript unit tests

import os

#
# ensure correct versions of python and scons

EnsurePythonVersion(2,3)
EnsureSConsVersion(0,96)

#
# retreive command-line arguments if any
# these are passed through to SConscripts

if ARGUMENTS.get('usegcc',0):
  usegcc = 1
else:
  usegcc = 0
Export(["usegcc"])

if ARGUMENTS.get('options',0):
  options = ARGUMENTS.get('options',0)
else:
  options = None
Export(["options"])

#
# set and export esysroot

esysroot = Dir('#../..')
Export(["esysroot"])

#
# call appropriate SConscripts

target_scripts = ['Data/SConstruct',
                  'DataAlgorithmAdapter/SConstruct',
                  'DataArray/SConstruct',
                  'DataArrayView/SConstruct',
                  'DataBlocks2D/SConstruct',
                  'DataC/SConstruct',
                  'DataCached/SConstruct',
                  'DataConstant/SConstruct',
                  'DataEmpty/SConstruct',
                  'DataExpanded/SConstruct',
                  'DataFactory/SConstruct',
                  'DataProf/SConstruct',
                  'DataTagged/SConstruct',
                  'DataVariable/SConstruct',
                  'DataVector/SConstruct',
                  'FunctionSpace/SConstruct',
                  'Taipan/SConstruct']

SConscript(target_scripts, duplicate=0)
