#
# $Id$
#
#######################################################
#
#           Copyright 2003-2007 by ACceSS MNRF
#       Copyright 2007 by University of Queensland
#
#                http://esscc.uq.edu.au
#        Primary Business: Queensland, Australia
#  Licensed under the Open Software License version 3.0
#     http://www.opensource.org/licenses/osl-3.0.php
#
#######################################################
#

import os
Import('*')

if 'Clone' in dir(env): local_env = env.Clone() # scons-0.98
else:                   local_env = env.Copy()  # scons-0.96

src_dir = local_env.Dir('.').srcnode().abspath

filenames = os.listdir(src_dir)
python_src = [ x for x in filenames if os.path.splitext(x)[1] in ['.py'] ]

pyc = local_env.PyCompile(python_src)

local_env.Depends(pyc, dep_lib)

tmp1 = local_env.Install(local_env['pyinstall']+'/escript', pyc)
env.Alias('target_install_escript_py', [tmp1])

