
########################################################
#
# Copyright (c) 2011 by University of Queensland
# Earth Systems Science Computational Center (ESSCC)
# http://www.uq.edu.au/esscc
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
########################################################


Import('*')
local_env = env.Clone()

# C++ unit tests would go here but we don't have any at this point

# configure python unit tests
local_env.SConscript(dirs = ['#/buckley/test/python'], variant_dir='python', duplicate=0, exports=['py_wrapper_lib'])

