# Scons configuration file for DataAlgorithmAdapter unit tests

#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./../../../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

cxx_flags=cxx_flags_debug

# print out build configuration for this module

print "Build configuration for module: DataAlgorithmAdapter unit tests"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# do the actual build

dataalgorithmadapter_test_path = str(esysroot) + '/escript/test/DataAlgorithmAdapter'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

escript_lib = str(esys_lib_path) + '/libescriptcpp.so'

install_dir = str(esysroot) + '/escript/test'

cpp_path = [dataalgorithmadapter_test_path,
            escript_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'dl',
        'util']

libs.extend(sys_libs)

sources = ['DataAlgorithmAdapterTestCase.cpp',
           'DataAlgorithmAdapterTest.cpp']

target = 'DataAlgorithmAdapterTest.exe'

import os
dataalgorithmadapter_env = Environment(ENV = os.environ)

dataalgorithmadapter_env.Replace(CXX = cxx)
dataalgorithmadapter_env.Replace(CXXFLAGS = cxx_flags)
dataalgorithmadapter_env.Replace(CPPPATH = cpp_path)
dataalgorithmadapter_env.Replace(LIBPATH = lib_path)
dataalgorithmadapter_env.Replace(LIBS = libs)

dataalgorithmadapter_test_exe = dataalgorithmadapter_env.Program(target, sources)

Depends(dataalgorithmadapter_test_exe, escript_lib)

Alias("build_tests", dataalgorithmadapter_env.Install(install_dir, dataalgorithmadapter_test_exe))

import scons_extensions
runUnitTest_builder = Builder(action = scons_extensions.runUnitTest, suffix = '.passed', single_source=True)
dataalgorithmadapter_env.Append(BUILDERS = {'RunUnitTest' : runUnitTest_builder});

Alias("run_tests", dataalgorithmadapter_env.RunUnitTest(target))
