# Scons configuration file for DataArrayView unit tests

#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./../../../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

cxx_flags=cxx_flags_debug

print "Build configuration for module: DataArrayView unit tests"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# do the actual build

dataarrayview_test_path = str(esysroot) + '/escript/test/DataArrayView'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

escript_lib = str(esys_lib_path) + '/libescriptcpp.so'

install_dir = str(esysroot) + '/escript/test'

cpp_path = [dataarrayview_test_path,
            escript_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'dl',
        'util']

libs.extend(sys_libs)

sources = ['DataArrayViewTestCase.cpp',
           'DataArrayViewTest.cpp']

target = 'DataArrayViewTest.exe'

import os
dataarrayview_env = Environment(ENV = os.environ)

dataarrayview_env.Replace(CXX = cxx)
dataarrayview_env.Replace(CXXFLAGS = cxx_flags)
dataarrayview_env.Replace(CPPPATH = cpp_path)
dataarrayview_env.Replace(LIBPATH = lib_path)
dataarrayview_env.Replace(LIBS = libs)

dataarrayview_test_exe = dataarrayview_env.Program(target, sources)

Depends(dataarrayview_test_exe, escript_lib)

Alias("build_tests", dataarrayview_env.Install(install_dir, dataarrayview_test_exe))

import scons_extensions
runUnitTest_builder = Builder(action = scons_extensions.runUnitTest, suffix = '.passed', single_source=True)
dataarrayview_env.Append(BUILDERS = {'RunUnitTest' : runUnitTest_builder});

Alias("run_tests", dataarrayview_env.RunUnitTest(target))
