esysroot = None

Import('*')

import os
import string

if esysroot == None:
  esysroot = Dir('#../../..')

##### these will enventually be loaded from an external config file ########

cxx_flags = '-O0 -openmp -openmp_report0 -tpp2 -ansi -ansi_alias -no-gcc -fpic -w1'

python_path = '/raid2/tools/python-2.3.4/include/python2.3'
boost_path = '/raid2/tools/boost/include/boost-1_31'

python_lib_path = '/raid2/tools/python-2.3.4/lib'
boost_lib_path = '/raid2/tools/boost/lib'

############################################################################

dataarrayview_test_path = str(esysroot) + '/escript/test/DataArrayView'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

cpp_path = [dataarrayview_test_path,
            escript_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'CppUnitTest',
        'python2.3',
        'boost_python-intel-d-1_31',
        'dl',
        'util',
        'guide',
        'irc']

sources = ['DataArrayViewTestCase.cpp',
           'DataArrayViewTest.cpp']

target = 'DataArrayViewTest.exe'

dataarrayview_env = Environment(ENV = os.environ)

dataarrayview_env.Replace(CXX = 'icc')
dataarrayview_env.Replace(CXXFLAGS = cxx_flags)
dataarrayview_env.Replace(CPPPATH = cpp_path)
dataarrayview_env.Replace(LIBPATH = lib_path)
dataarrayview_env.Replace(LIBS = libs)

dataarrayview_test_exe = dataarrayview_env.Program(target, sources)
