# $Id$

# SCSL 

PKG_CC_DEFS += SCSL
PKG_CC_INC_DIRS += ${NULL}	# standard directory
PKG_CPP_DEFS += SCSL
PKG_CPP_INC_DIRS += ${NULL}	# standard directory
PKG_LD_LIB_DIRS += ${NULL}	# standard directory
PKG_LD_LIBS += scs_mp
