##############################################################################
#
# Copyright (c) 2003-2026 by the esys.escript Group
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# See CREDITS file for contributors and development history
# Development from 2019 by School of Earth and Environmental Sciences
#
##############################################################################

Import('env')

# configure python module
env.SConscript('py_src/SConscript', variant_dir='py', duplicate=0)

# configure unit tests
env.SConscript('test/python/SConscript', duplicate=0)

