esysroot = None

Import('*')

if esysroot == None:
  esysroot = Dir('#..')
Export(["esysroot"])

libdir = Dir(str(esysroot) + '/escript/lib')
Export(["libdir"])

SConscript('src/Data/SConscript', src_dir='src/Data', build_dir='obj', duplicate=0)
