Import('*')

lib_name = 'CppUnitTest'
cppunit_env=env.Copy()

src_dir = cppunit_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
sources = [x for x in filenames if os.path.splitext(x)[1] in ['.cpp', '.c']]

cppunit_env.SConscript(dirs = ['#tools/CppUnitTest/inc/CppUnitTest'], duplicate=0)

if env['PLATFORM'] <> "win32" and  env['PLATFORM'] <> "posix" :
   import os
   
   cxx_flags = '-O0 -openmp -openmp_report0 -tpp2 -ansi -ansi_alias -no-gcc -w1'
   
   cpp_path = ['#../CppUnitTest/inc']
   
   cppunit_env = Environment(ENV = os.environ)
   
   cppunit_env.Replace(CXX = 'icc')
   cppunit_env.Replace(CXXFLAGS = cxx_flags)
   cppunit_env.Replace(CPPPATH = cpp_path)
   esys_lib = libdir
   
cppunit_lib = cppunit_env.StaticLibrary(lib_name, sources)
cppunit_env.Install( esys_lib, cppunit_lib)
