esysroot = None

Import('*')

if esysroot == None:
  esysroot = Dir('#..')
Export(["esysroot"])

libdir = Dir(str(esysroot) + '/bruce/lib')
Export(["libdir"])

SConscript('src/Bruce/SConscript', src_dir='src/Bruce', build_dir='obj', duplicate=0)
