# Scons configuration file for bruce

import os

#
# ensure correct versions of python and scons

EnsurePythonVersion(2,3)
EnsureSConsVersion(0,96)

#
# set appropriate defaults for configuration variables

esysroot = Dir('#..')
libinstall = None
dodebug = 0
usegcc = 0

#
# import configuration variables passed in from
# calling SConscript (if any)

Import('*')

#
# retreive command-line arguments if any

if ARGUMENTS.get('libinstall',0):
  libinstall = ARGUMENTS.get('libinstall',0)
Export(["libinstall"])

if ARGUMENTS.get('debug',0):
  dodebug = 1

if ARGUMENTS.get('usegcc',0):
  usegcc = 1

#
# determine platform

env = Environment(ENV = os.environ)
platform = env['PLATFORM']

#
# determine hostname

hostname = os.environ['HOSTNAME']

#
# export esysroot

Export(["esysroot"])

#
# set and export library directory

libdir = Dir(str(esysroot) + '/bruce/lib')
Export(["libdir"])

#
# load and export configuration settings

python_path = '/raid2/tools/python-2.3.4/include/python2.3'
boost_path = '/raid2/tools/boost/include/boost-1_31'

cxx_flags = '-O0 -openmp -openmp_report0 -tpp2 -ansi -ansi_alias -no-gcc -fpic -w1'

Export(["python_path"])
Export(["boost_path"])
Export(["cxx_flags"])

#
# print out build configuration for this module

print "############################################"
print "Build configuration for module: bruce"
print "         dodebug: ", dodebug
print "          usegcc: ", usegcc
print "        platform: ", platform
print "        hostname: ", hostname
print "      libinstall: ", libinstall
print "############################################"

#
# call the SConscript to do the actual build

SConscript('src/Bruce/SConscript', src_dir='src/Bruce', build_dir='obj', duplicate=0)
