
##############################################################################
#
# Copyright (c) 2003-2014 by University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

from os.path import splitext
Import('*')

local_env = env.Clone()

# files defining test runs (passing in a release)
testruns = []
testruns += ['run_savevtk_tests.py']
testruns += ['run_savesilo_tests.py']

# files defining tests run locally (not as part of a release)
localtestruns = [x for x in Glob('*.py', strings=True) if not x.startswith('run_')]

# all tests
alltestruns = testruns + localtestruns

# add unit test to target alias
local_env.PrependENVPath('PYTHONPATH',str(Dir('.')))
local_env['ENV']['WEIPA_TEST_MESHES']=env.Dir('#/weipa/test/python/meshes').abspath
local_env['ENV']['WEIPA_WORKDIR']=Dir('.').abspath
env.Alias('local_py_tests',[splitext(x)[0]+'.passed' for x in alltestruns])
env.Alias('py_tests', [splitext(x)[0]+'.passed' for x in testruns])

# run all tests
program = local_env.RunPyUnitTest(alltestruns)

# add a group of tests
from grouptest import *
tgroup=GroupTest("$PYTHONRUNNER ",(("WEIPA_TEST_DATA","$BATCH_ROOT/weipa/test/python"),('WEIPA_WORKDIR','$BUILD_DIR/weipa/test/python')),"$BATCH_ROOT/escriptcore/test/python:$BATCH_ROOT/weipa/test/python","$BATCH_ROOT/weipa/test/python",testruns)
tgroup.makeDir("$BUILD_DIR/weipa/test/python")
TestGroups.append(tgroup)

