
##############################################################################
#
# Copyright (c) 2003-2012 by University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Open Software License version 3.0
# http://www.opensource.org/licenses/osl-3.0.php
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development since 2012 by School of Earth Sciences
#
##############################################################################

import os
Import('*')

epy_dir=os.path.join(release_dir, 'epydoc')
env.Command(epy_dir, [], [Mkdir(epy_dir)])

env.Alias('api_epydoc', [env['pyinstall'], epy_dir], "epydoc --docformat restructuredtext -v --html -o "+epy_dir+" esys")

# This will need to be here at least until the output of api_epydoc properly
# depends on the libraries it uses as input
env.AlwaysBuild('api_epydoc')

