#
# $Id$
#
#######################################################
#
#           Copyright 2003-2007 by ACceSS MNRF
#       Copyright 2007 by University of Queensland
#
#                http://esscc.uq.edu.au
#        Primary Business: Queensland, Australia
#  Licensed under the Open Software License version 3.0
#     http://www.opensource.org/licenses/osl-3.0.php
#
#######################################################
#

import os
Import('*')

try:
  local_env = env.Clone()	# scons-98.03
except AttributeError:
  local_env = env.Copy()	# scons-96.92

src_dir = local_env.Dir('.').srcnode().abspath

# get the relevant file names:
src_dir = local_env.Dir('.').srcnode().abspath
filenames = [ x for x in os.listdir(src_dir) if os.path.splitext(x)[1] in [".h", ".c", ".cpp"] ]

sources = [x for x in filenames if os.path.splitext(x)[1] in ['.cpp', '.c']]

local_env.Append(LIBS=[ 'esysUtils', 'CppUnitTest', sys_libs])

program = local_env.Program('EsysExceptionTest', sources)

#Add Unit Test to target alias

env.Alias('build_tests', program)

# run the tests - but only if test_targets are stale
local_env.RunUnitTest('EsysExceptionTest')
test_targets = os.path.splitext('EsysExceptionTest')[0]+'.passed'
Alias("run_tests", test_targets)

