Import('*')

import os
import string

esysUtils_path = str(esysroot) + '/esysUtils/inc'

cpp_path = [esysUtils_path,
            python_path,
            boost_path]

lib = 'esysUtils'
sources = ['EsysException.cpp',
           'esysExceptionTranslator.cpp']

utils_env = Environment(ENV = os.environ)

utils_env.Replace(CXX = cxx)
utils_env.Replace(CXXFLAGS = cxx_flags)
utils_env.Replace(ARFLAGS = ar_flags)
utils_env.Replace(CPPPATH = cpp_path)

utils_lib = utils_env.StaticLibrary(lib, sources)

Default(utils_env.Install(libdir, utils_lib))
