Import('*')

lib_name = 'escriptcpp'

escript_env=env.Copy()

src_dir = escript_env.Dir('.').srcnode().abspath

import os
filenames = os.listdir(src_dir)
sources = [x for x in filenames if os.path.splitext(x)[1] in ['.cpp', '.c']]
headers = [x for x in filenames if os.path.splitext(x)[1] in ['.h']]

include = Dir('escript/Data', esys_inc)
escript_env.Install( include, headers )

escript_env.Append(LIBS= [boost_lib_name, 'esysUtils'])

if env['PLATFORM'] == "win32":
   escript_env.Append(CPPDEFINES=['_WINDOWS', '_USRDLL', 'ESCRIPT_EXPORTS'])
   escript_env.Append(LIBS= ['ext_math'])
   escript_env['PDB'] = lib_name + '.pdb'
else:
   import os
   
   cxx_flags = '-O0 -openmp -openmp_report0 -tpp2 -ansi -ansi_alias -no-gcc -w1'
   
   cpp_path = ['#../escript/inc',
               '#../esysUtils/inc',
               '/raid2/tools/python-2.3.4/include/python2.3',
               '/raid2/tools/boost/include/boost-1_31']
   
   escript_env = Environment(ENV = os.environ)
   
   escript_env.Replace(CXX = 'icc')
   escript_env.Replace(SHOBJSUFFIX = '.lo')
   escript_env.Replace(CXXFLAGS = cxx_flags)
   escript_env.Replace(CPPPATH = cpp_path)
   
escript_lib = escript_env.SharedLibrary(lib_name, sources)
escript_env.Install(esys_lib, escript_lib)
