Import('*')

import os
import string

escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'

cpp_path = [escript_path,
            esysUtils_path,
            python_path,
            boost_path]

lib = 'escriptcpp'
sources = ['AbstractContinuousDomain.cpp',
           'AbstractDomain.cpp',
           'AbstractSystemMatrix.cpp',
           'DataAbstract.cpp',
           'DataArray.cpp',
           'DataArrayView.cpp',
           'DataBlocks2D.cpp',
           'DataCached.cpp',
           'DataC.cpp',
           'DataConstant.cpp',
           'Data.cpp',
           'DataEmpty.cpp',
           'DataExpanded.cpp',
           'DataFactory.cpp',
           'DataProf.cpp',
           'DataTagged.cpp',
           'DataVariable.cpp',
           'DataVector.cpp',
           'FunctionSpace.cpp',
           'FunctionSpaceFactory.cpp',
           'NullDomain.cpp',
           'Taipan.cpp',
           'escriptcpp.cpp']

escript_env = Environment(ENV = os.environ)

escript_env.Replace(CXX = 'icc')
escript_env.Replace(SHOBJSUFFIX = '.lo')
escript_env.Replace(CXXFLAGS = cxx_flags)
escript_env.Replace(CPPPATH = cpp_path)

escript_lib = escript_env.SharedLibrary(lib, sources)
escript_env.Install(libdir, escript_lib)
