name: Build Flatpak

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Installing dependencies
      run: sudo apt-get install -y flatpak-builder

    - name: Adding flatpak repo
      run: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Installing freedesktop platform and sdk
      run: flatpak install flathub org.freedesktop.Platform//18.08 org.freedesktop.Sdk//18.08
    
    - name: Building the flatpak...
      run: flatpak-builder ./build ./tools/flatpak/au.edu.uq.esys.escript.json
