name: Build Flatpak

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Installing dependencies
      run: sudo apt-get install -y flatpak-builder
    
    - name: Building the flatpak...
      run: flatpak-builder ./build ./tools/flatpak/au.edu.uq.esys.escript.json
