name: Build Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building the Docker image...
      run: docker build . --file ./tools/docker/docker_trilinos --tag esys-escript:$(date +%s)
