#This tests the code in the master branch on meerkat every day at 11:00 pm AEST
name: meerkat_omp

on:
  schedule:
    - cron: '0 13 * * *'
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: [self-hosted, linux, x64, meerkat]

    steps:
    - uses: actions/checkout@v2

    - name: Building escript...
      run: scons -j8 lapack=1 options_file=scons/meerkat_options.py build_full || cat config.log

    - name: Running unit tests...
      run: |
          export LD_LIBRARY_PATH=/usr/local/trilinos_nompi/lib:/usr/local/boost.1.73.0/lib:$LD_LIBRARY_PATH
          sh utest.sh `pwd`/build '-t8'
        
