name: Arch Trilinos unit testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: [self-hosted, linux, x64, capybara]

    steps:
    - uses: actions/checkout@v2
    - name: Building the Docker image...
      run: docker build . --file ./tools/unittesting/arch_trilinos_py3 --tag esys-escript:$(date +%s)
