# Scons configuration file for DataCached unit tests

#
# set appropriate defaults for configuration variables

esysroot=str(Dir('./../../../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

cxx_flags=cxx_flags_debug

print "Build configuration for module: DataCached unit tests"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# do the actual build

datacached_test_path = str(esysroot) + '/escript/test/DataCached'
escript_path = str(esysroot) + '/escript/src'
esysUtils_path = str(esysroot) + '/esysUtils/src'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

escript_lib = str(esys_lib_path) + '/libescriptcpp.so'

install_dir = str(esysroot) + '/escript/test'

cpp_path = [datacached_test_path,
            escript_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'dl',
        'util']

libs.extend(sys_libs)

sources = ['DataCachedTestCase.cpp',
           'DataCachedTest.cpp']

target = 'DataCachedTest.exe'

import os
datacached_env = Environment(ENV = os.environ)

datacached_env.Replace(CXX = cxx)
datacached_env.Replace(CXXFLAGS = cxx_flags)
datacached_env.Replace(CPPPATH = cpp_path)
datacached_env.Replace(LIBPATH = lib_path)
datacached_env.Replace(LIBS = libs)

datacached_test_exe = datacached_env.Program(target, sources)

Depends(datacached_test_exe, escript_lib)

Alias("build_tests", datacached_env.Install(install_dir, datacached_test_exe))

import scons_extensions
runUnitTest_builder = Builder(action = scons_extensions.runUnitTest, suffix = '.passed', single_source=True)
datacached_env.Append(BUILDERS = {'RunUnitTest' : runUnitTest_builder});

Alias("run_tests", datacached_env.RunUnitTest(target))
