
##############################################################################
#
# Copyright (c) 2003-2018 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

import os
Import('*')
local_env = env.Clone()

# get the source file names
sources = Glob('*.py')
sym_sources = Glob(os.path.join('symbolic','*.py'))

# compile
pyc = local_env.PyCompile(sources)
sym_pyc = local_env.PyCompile(sym_sources)
env.Alias('build_escript', [pyc, sym_pyc])

# install
runmodel_inst = local_env.Install(local_env['bininstall'], 'runmodel.py')
py_inst = local_env.Install(Dir('escriptcore', local_env['pyinstall']), pyc)
sym_py_inst = local_env.Install(os.path.join(local_env['pyinstall'],'escriptcore','symbolic'), sym_pyc)
env.Alias('install_escript', [runmodel_inst, py_inst, sym_py_inst])
