
##############################################################################
#
# Copyright (c) 2003-2017 by The University of Queensland
# http://www.uq.edu.au
#
# Primary Business: Queensland, Australia
# Licensed under the Apache License, version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# Development until 2012 by Earth Systems Science Computational Center (ESSCC)
# Development 2012-2013 by School of Earth Sciences
# Development from 2014 by Centre for Geoscience Computing (GeoComp)
#
##############################################################################

Import('*')

sources = ['ScriptMPI.cpp']
sources_redirect = ['ScriptMPIredirect.cpp']

local_env = env.Clone()
local_env.PrependUnique(LIBS = ['escript'])

progs = local_env.Program('pythonMPI', sources)
progs += local_env.Program('pythonMPIredirect', sources_redirect)

inst = local_env.Install(local_env['libinstall'], progs)

env.Alias('build_pythonMPI', progs)
env.Alias('install_pythonMPI', inst)

