# Scons configuration file for DataBlocks2D unit tests

#
# set appropriate defaults for configuration variables
esysroot=str(Dir('./../../../..').abspath)
execfile(str(File(esysroot+"/scons/esys_options.py")))

cxx_flags=cxx_flags_debug

print "Build configuration for module: DataBlocks2D unit tests"
print "             cxx: ", cxx
print "       cxx_flags: ", cxx_flags

#
# do the actual build

datablocks2d_test_path = str(esysroot) + '/escript/test/DataBlocks2D'
escript_path = str(esysroot) + '/escript/inc'
esysUtils_path = str(esysroot) + '/esysUtils/inc'
CppUnitTest_path = str(esysroot) + '/tools/CppUnitTest/inc'

esys_lib_path = str(esysroot) + '/lib'
esysUtils_lib_path = str(esysroot) + '/esysUtils/lib'
CppUnitTest_lib_path = str(esysroot) + '/tools/CppUnitTest/lib'

escript_lib = str(esys_lib_path) + '/libescriptcpp.so'

install_dir = str(esysroot) + '/escript/test'

cpp_path = [datablocks2d_test_path,
            escript_path,
            esysUtils_path,
            CppUnitTest_path,
            python_path,
            boost_path]

lib_path = [esys_lib_path,
            esysUtils_lib_path,
            CppUnitTest_lib_path,
            python_lib_path,
            boost_lib_path]

libs = ['escriptcpp',
        'esysUtils',
        'CppUnitTest',
        str(python_lib),
        str(boost_lib),
        'dl',
        'util']

libs.extend(sys_libs)

sources = ['DataBlocks2DTestCase.cpp',
           'DataBlocks2DTest.cpp']

target = 'DataBlocks2DTest.exe'

import os
datablocks2d_env = Environment(ENV = os.environ)

datablocks2d_env.Replace(CXX = cxx)
datablocks2d_env.Replace(CXXFLAGS = cxx_flags)
datablocks2d_env.Replace(CPPPATH = cpp_path)
datablocks2d_env.Replace(LIBPATH = lib_path)
datablocks2d_env.Replace(LIBS = libs)

datablocks2d_test_exe = datablocks2d_env.Program(target, sources)

Depends(datablocks2d_test_exe, escript_lib)

Alias("build_tests", datablocks2d_env.Install(install_dir, datablocks2d_test_exe))

import scons_extensions
runUnitTest_builder = Builder(action = scons_extensions.runUnitTest, suffix = '.passed', single_source=True)
datablocks2d_env.Append(BUILDERS = {'RunUnitTest' : runUnitTest_builder});

Alias("run_tests", datablocks2d_env.RunUnitTest(target))
